### ISSUE TITLE
adoptNode() should always return a node

### ISSUE THREAD

**Issue by TRowbotham** [whatwg/dom#1006]
In the [adoptNode()](https://dom.spec.whatwg.org/#dom-document-adoptnode) steps, step 3 says "If node is a DocumentFragment node whose host is non-null, then return.", but the [interface](https://dom.spec.whatwg.org/#ref-for-dom-document-adoptnode) defines `adoptNode()` as always returning a node. Shouldn't step 3 either return node or throw, or am I missing something from IDL that would allow returning nothing?

**Comment by annevk** [comment]
See #819.

**Comment by TRowbotham** [comment]
I clearly forgot to use the search function, thanks for the context and sorry for the noise
