### ISSUE TITLE
Is is supposed to say 'SHADOW ROOT' and not DOCUMENT FRAGMENT?

### ISSUE THREAD

**Issue by DougRoyer** [whatwg/dom#1007]
https://dom.spec.whatwg.org/commit-snapshots/f2a2dedd8831cbae9afeab87b915e1234c49cba1/#concept-node-adopt

It says: 
(3) If node is a DocumentFragment node whose host is non-null, then return. 

Problem:
A DocumentFragment node does not have a 'host', a SHADOW_ROOT_NODE has one.

**Comment by rniwa** [comment]
No, that host refers to the [template element](https://html.spec.whatwg.org/multipage/scripting.html#template-contents).
