### ISSUE TITLE
Renamed slotAssignment to slotAssignmentMode or slotMode

### ISSUE THREAD

**Issue by rniwa** [whatwg/dom#1012]
I think it would be regrettable to use the name "slotAssignment" to refer to the mode of slot assignment. You could conceivably imagine that we may want to introduce some kind of `SlotAssignment` object which lets script have more finer control over slot assignment.

**Comment by rniwa** [comment]
@domenic @annevk @mfreed7

**Comment by annevk** [comment]
Could you elaborate a bit? How would that be different from "manual"?

Also, I think the name used here is scoped to `ShadowRoot` instances, so it could mean something else elsewhere, but I agree it might end up being a tad confusing.

Having said all that, I don't think this can be changed at this point. It has shipped in at least two implementations as far as I know.

**Comment by rniwa** [comment]
@annevk : There was a discussion of slot assignment which uses worklet in the past. I'm not sure if anyone is seriously pursuing that it seems plausible that we may have more fine control over slot assignment in the future.

**Comment by domenic** [comment]
I think the current name is good.
