### ISSUE TITLE
[proposal]: getClientRects / getBoundingClientRect for pseudo elements

### ISSUE THREAD

**Issue by WilcoFiers** [whatwg/dom#1020]
One of the big challenges in automated accessibility testing is to test for color contrast. And one of the biggest challenges in testing for color contrast is to figure out what is going on with pseudo elements on the page. It would be very helpful if, similar to `window.getComputedStyle` the `Element.getClientRects` and `Element.getBoundingClientRect` methods could accept an argument which tells the browser to return rect(s) of the pseudo element instead. 

```js
const pseudoRects = elm.getClientRects(':after');
```

This would help tools like [axe-core](https://github.com/dequelabs/axe-core), and other accessibility tools, which currently just sort of have to guess what's going on with the pseudo elements based on computed styles.

**Comment by annevk** [comment]
Could you file this against CSSOM? These methods are not defined by the DOM Standard.

**Comment by WilcoFiers** [comment]
CSSOM? I did not realise that, but yes, absolutely.
