### ISSUE TITLE
DOM Comments don't align with HTML comments

### ISSUE THREAD

**Issue by josepharhar** [whatwg/dom#1023]
In the HTML spec, it says that comments must not contain `-->` among other things: https://html.spec.whatwg.org/multipage/syntax.html#comments

In the DOM spec, it says that you can create a `Comment` with any text, no restrictions: https://dom.spec.whatwg.org/#interface-comment

This was raised in a [chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1251069) where someone pointed out that you can create a `Comment` in script which contains a `-->`, put other things after the `-->`, and reassign `document.body.innerHTML = document.body.innerHTML` which will make everything after the `-->` get parsed as actual HTML instead of comments

@mfreed7

**Comment by annevk** [comment]
It's generally true that you can create node trees that cannot be serialized or that can be serialized and then when parsed result in a different tree. This is not a unique ability of comments. 

https://html.spec.whatwg.org/#serialising-html-fragments points this out in a warning.

https://html.spec.whatwg.org/#serialising-xhtml-fragments on the other hand does attempt to account for it, but I'm not sure how well tested that is.

Did you have a suggestion or do you think DOM should call this out more prominently?

**Comment by josepharhar** [comment]
> It's generally true that you can create node trees that cannot be serialized or that can be serialized and then when parsed result in a different tree. This is not a unique ability of comments.

With this in mind, I think it's OK to leave things as is.
