### ISSUE TITLE
Should AbortSignal.timeout only be exposed on (Window, Worker)?

### ISSUE THREAD

**Issue by shaseley** [whatwg/dom#1054]
The `AbortSignal` interface was [recently changed](https://github.com/whatwg/dom/pull/1024) to be exposed everywhere (`[Exposed=*]`).  But `AbortSignal.timeout()` queues a task, and IIUC this won't work with the simplified worklet event loop ([relevant discussion for `postTask`](https://github.com/WICG/scheduling-apis/pull/51#issuecomment-955039327)).

Should the IDL for `AbortSignal.timeout()` just expose the method to `(Window, Worker)`?

**Comment by domenic** [comment]
+1!
