### ISSUE TITLE
`AbortController` / `AbortSignal` was updated in a somewhat breaking way

### ISSUE THREAD

**Issue by getify** [whatwg/dom#1059]
I am not quite sure when this happened, but it seems like fairly recently...  the change to add `reason` to `AbortSignal` was done in a somewhat breaking way, and I'm just finding out about it given that this breakage propagated to one of my libraries that uses/extends `AbortController` and `AbortSignal`.

In particular, my concerns are:

1. The definition of `reason` as *READ-ONLY* breaks libraries (like [CAF](https://github.com/getify/caf)) that had previously been monkey-patching/polyfilling a `reason` property onto `AbortSignal` instances. More about the breakage can be read here: https://github.com/getify/CAF/issues/28

2. A **BREAKING CHANGE** was also made to the `abort(..)` method. The change is that prior, if a `abort()` call was made with no argument, nothing adverse happens. But now, if you call `abort()` with no arguments, the `reason` doesn't stay set as `undefined`, as one would expect from PRIOR behaviors... rather, it gets set to a non-falsy `DOMException` error. That is, in particular, rather surprising, given that `abort(undefined)` -- explicitly passing in `undefined` -- avoids the `DOMException` value for `reason`.

Both of these changes may indeed have valid rationale, and I would certainly appreciate seeing where such discussions happened (as my searches thus far haven't turned up anything).

However, they conspire together to create a breaking change that crashes my CAF library. CAF has been around for 4+ years, is downloaded over 5,000 times per week on npm, and has over 1,200 stars on GitHub. As such, there's clearly a decent amount of sites/apps out there using CAF, and all of them are now broken as a result of these two changes.

I've done a pre-release of CAF to try to fix this crashing in a backwards-compatible way -- will do a full release once affected users report that it addressed the breakage -- but I have no idea if, or how quickly, all those sites/apps who are using CAF will update to my newest library release.

I would like to ask if it's possible to unwind change, even if temporarily, so browsers (like Chrome) are not breaking CAF v14.0.0 and prior?

**Comment by Koka** [comment]
For a context:
The PR where reason was introduced https://github.com/whatwg/dom/pull/1027
Corresponding Chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=1263410

**Comment by annevk** [comment]
It's unfortunate this has happened, but those are not considered breaking changes. I thought it was somewhat widely known that patching objects can lead to issues in the JavaScript community?

Also, `abort()` and `abort(undefined)` behave identically. And I've no idea why one would expect anything about `reason` "PRIOR" as that was not a member of this object.

**Comment by getify** [comment]
I would typically never touch/extend built-in objects.

Cancelation has been such a HUGE gap in JS (and the web platform) for *decades* that I felt CAF had a responsibility to fix these gaps 4 years ago, mostly in response to `AbortController` finally being added.

But I was deeply dismayed that it wasn't added with something as obvious/helpful as a reason-tracking mechanism. I fished around for *why*, and I didn't find anything concrete.

Reluctantly, I decided CAF couldn't wait around in case a future change would address that gap. As it turned out, waiting 4 long years would have been, IMO, an unacceptable delay in addressing what people needed.

It was important to me to embrace the ecosystem, and (in particular) interop with things like `fetch(..)`. That unfortunately meant I couldn't just wrap around `AbortSignal` (as `fetch(..)` wouldn't recognize them). Also, I can't even sub-class `AbortSignal` because I don't control the creation (done inside of `AbortController` automatically). I don't see any other way I could have balanced all this other than to decorate `AbortSignal` instances. I didn't *want* to, because I didn't want to face a day like yesterday in the future. But it was a risk I felt I needed to take.

I had thoughts about what it would be like if `reason` was later added. I intentionally designed CAF to work seamlessly with such a change, or so I thought.

I did not anticipate the read-only bit, but again that turned out to be an easy'ish accommodation to work around. I honestly never would have even remotely dreamed of the DOMException-on-omission bit. That part in particular just feels so unlike how features are typically added to existing APIs, as it feels to me like deliberately "breaking".

Lessons learned, for sure. But honestly, the 4 year gap here in some ways validates my reluctant decisions back then.

Again, if there are strong motivations for read-only and DOMException-on-omission, they are not at all obvious to me thus far. I would appreciate links to any further historical context onnsuch decisions.

**Comment by annevk** [comment]
Before the change there was a singular reason, exposed in APIs that ended up rejecting a promise (i.e., an "AbortError" DOMException). So that's what `abort()` continues to do. Passing another reason will reject those promises with the given reason. You can find discussion and motivation in the PR linked above.

**Comment by getify** [comment]
> Before the change there was a singular reason, exposed in APIs that ended up rejecting a promise (i.e., an "AbortError" DOMException).

Just for posterity sake, this is not accurate as far as I know. Prior to the spec adding `reason`, the `signal.reason` access would always return `undefined`. I dunno if there was always an internal `AbortError` DOMException or not... but it wasn't exposed on the `reason` property. I maintain this was a breaking change. But I guess it doesn't matter anymore.

**Comment by annevk** [comment]
We add attributes to objects all the time. It's not generally known as a breaking change. Sometimes it does lead to breakage and in rare cases that warrants a rename (this mostly happens with JS objects, not platform objects).

**Comment by getify** [comment]
I understand that narrower stance, but I don't think this point has been fully groked:

The "breaking change" was not "adding the property", it's the combination of all 3 of these things together that constitutes the de facto (even if not official) "breaking change":

1. adding the property; AND

2.  enforcing that it always has to have an intentional value (meaning it's now "required" -- omitting it vs requiring an affirmative `undefined` argument value); AND

3. enforcing that if this new "required" property is not set (via the now "required" argument to `abort()`), in place of such value there's now a DOMException whose semantic meaning is *not* "this was aborted" but rather "you messed up and didn't provide a required reason value".

Those 3 things together constitute a "breaking change" by any meaningful definition that I (or any reasonable dev I know) would use for any software I maintain. I cannot imagine making that kind of a change to any library I maintain, and then with a straight face claiming "what, bro, it's not technically a breaking change!?" 

I understand you refuse to accept that since you're using a more academic definition of "breaking change" instead of a pragmatic one. But anyway, I dealt with the breakage it caused users of my library, I've said my piece, and this is long-past water under the bridge. I won't keep belaboring it anymore.

----

Sorry for the noise of ressurecting a dead thread. I somehow never saw those previous responses around the time of the thread resolution.
