### ISSUE TITLE
DOMTokenList validation for object creation and attribute updates

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#106]
@yoavweiss I think we forgot to cover this since the text wasn't present yet in the `DOMTokenList` section but instead sorta left to each individual element/attribute combination.

Do you agree that we should update https://dom.spec.whatwg.org/#interface-domtokenlist to validate the tokens coming from attribute sets?

(See the two paragraphs before the domintro box.)

**Comment by yoavweiss** [comment]
I agree that it should be validated, for the sake of consistency.

**Comment by ArkadiuszMichalski** [comment]
Two small things:
1. In IDL `void add(DOMString... tokens);` << now return boolean
2. In validation steps algo (step 1. If the associated attribute’s...) << missing reference for "attribute’s"

**Comment by yoavweiss** [comment]
Good catch, thanks!
