### ISSUE TITLE
Fix some references around Document interface.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#108]
https://dom.spec.whatwg.org/#concept-document-url
base URL(a `URL`) and URL (a `URL`) << both `URL` inside () refers to URL in DOM, should not be directed to URL specification (https://url.spec.whatwg.org/#concept-url)? Ohh now I see this was reported earlier https://github.com/whatwg/dom/issues/62.

https://dom.spec.whatwg.org/#dom-document-origin
Origin has wrong reference to "Unicode serialization" (should be #unicode-serialisation-of-an-origin). But this is a result of inconsistencies how some specs using terms, "serialization" vs "serialisation", ect., which form is correct, or more preferred? Just look dependencies from URL (https://html.spec.whatwg.org/multipage/infrastructure.html#concept-url-serialiser) and check how exactly this term was defined in URL spec.

And I have one quick question, what is the fast way to detect XML document or HTML document, if both of them will have the same Document interface? Internal type (https://dom.spec.whatwg.org/#concept-document-type) it's not exposed, so we should somehow analize `Document.contentType` by using regex?

Edit:
https://dom.spec.whatwg.org/#dom-document-characterset << `name` in step 1. has wrong references (should be `#name`).

Edit:
https://dom.spec.whatwg.org/#dom-domimplementation-createdocumenttype 
"No check is performed that publicId matches the PublicChar production or that..." << not `PublicChar` but `PubidChar` and can be linked to http://www.w3.org/TR/xml/#NT-PubidChar.

**Comment by annevk** [comment]
Thank you!

**Comment by annevk** [comment]
XML/HTML you can do through various methods that lowercase, e.g., `document.createElement()`.
