### ISSUE TITLE
Does `MutationObserver` `attributeFilter` accept itorators?

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#1092]
I can't tell from the DOM spec. [It says](https://dom.spec.whatwg.org/#dom-mutationobserverinit-attributefilter) that `attributeFilter` accepts a "sequence" which is further defined as a "list". TypeScript defines `attributeFilter` as `string[]`, however in Google Chrome I am able to pass the result of a `Map.keys()` (an `IterableIterator` in TypeScript terms) directly to the `attributeFilter` and it works.

Is this unique behavior to Chrome? Or does the spec allow iterator instances and I've missed how that reads in the spec?

**Comment by pshaughn** [comment]
The WebIDL spec guarantees conversion here, with the conversion algorithm described at https://webidl.spec.whatwg.org/#es-sequence
