### ISSUE TITLE
Nu HTML checker latest version updated, Running Nu HTML checker error on build result

### ISSUE THREAD

**Issue by JunLiangWangX** [whatwg/dom#1125]
### Nu HTML latest version updated

- latest version：https://github.com/validator/validator/releases/tag/latest
- update content：https://github.com/validator/validator/pull/1471

This update will result in errors running the Nu HTML checker on build results，The error message is as follows：
https://github.com/JunLiangWangX/DOM-Standard/actions/runs/3390951838/jobs/5635637119

**Comment by domenic** [comment]
This is being tracked and fixed in https://github.com/whatwg/whatwg.org/issues/401; let's consolidate there.

**Comment by JunLiangWangX** [comment]
Okay, thanks.

**Comment by JunLiangWangX** [comment]
> This is being tracked and fixed in [whatwg/whatwg.org#401](https://github.com/whatwg/whatwg.org/issues/401); let's consolidate there.

Okay, thanks.
