### ISSUE TITLE
Contradicting text regarding Document.ownerDocument?

### ISSUE THREAD

**Issue by karfau** [whatwg/dom#1126]
The spec currently states the following:

> The `ownerDocument` getter steps are to return null, if this is a document; otherwise this’s node document.

And as a "Note" right afterwards
> The node document of a document is that document itself. All nodes have a node document at all times.

"node document" points to https://dom.spec.whatwg.org/#concept-node-document which doesn't say which property it is pointing to.

According to the IDL definition of Document, it implements the Node interface.

Can you help me to understand how all of this can be correct, or decide what Document.ownerDocument should return?

**Comment by annevk** [comment]
What is the contradiction?

While the public and private API are related, they are not the same concept.

**Comment by karfau** [comment]
Do I understand correctly that the "node docement" refers to a concept/private API?
And `ownerDocument` is a public access to that private API forall nodes beside the Document, because for that the getter returns null?

**Comment by annevk** [comment]
Yes.

**Comment by karfau** [comment]
Thx for the clarification
