### ISSUE TITLE
Possible typo: "as a node tree" to "as node trees"

### ISSUE THREAD

**Issue by hunan-rostomyan** [whatwg/dom#113]
In [&sect; 4.1](https://dom.spec.whatwg.org/#introduction-to-the-dom): "These documents are presented as <strong><strike>a</strike></strong> node tree<strong>s</strong>".

That may not be the intended meaning, however. In which case, please ignore.

**Comment by annevk** [comment]
Probably better to make documents singular. And I guess that sentence should use represent rather than present.

**Comment by hunan-rostomyan** [comment]
What do you think about one of these alternatives:

1. "Each such document is represented as a node tree."
2. "Each of these documents is represented as a node tree."
3. "A document is represented as a node tree."

I feel like adding the determiner makes the sentence easier to read.

**Comment by annevk** [comment]
Thank you, went with 1.
