### ISSUE TITLE
namespaces: validate and extract uses the strictly split a string in a vague manner

### ISSUE THREAD

**Issue by dlrobertson** [whatwg/dom#1134]
Namespaces [validate and extract](https://dom.spec.whatwg.org/#validate-and-extract) uses strictly split a string in the following step:

> 5. If qualifiedName contains a U+003A (:), then [strictly split](https://infra.spec.whatwg.org/#strictly-split) the string on it and set prefix to the part before and localName to the part after.

[strictly-split](https://infra.spec.whatwg.org/#strictly-split) defines the result as a [list](https://infra.spec.whatwg.org/#lists), so "the part before" and "the part after" feels a bit vague. Due to the validation in step two and the branch condition the list will have two elements, but it would be a bit clearer to use list indexing.

**Comment by dlrobertson** [comment]
To what extent is it helpful to be explicit about things? When thinking about a step like this, I tend to think of something like:


  5. If _qualifiedName_ contains a U+003A (:), then run the following steps:
    1.  Let _splitResult_ be the result of [strictly split](https://infra.spec.whatwg.org/#strictly-split) givent _qualifiedName_.
    2. Set _prefix_ to _splitResult_[0].
    3. Set _localName_ to _splitResult_[1].

Unwrapping things like this feels a bit verbose. Is there a better way?

**Comment by annevk** [comment]
You can leave out " run the following steps".

@domenic did we start using

> Let [_prefix_, _localName_] be the result of ...

already?

Even without that though your version is clearer and I'd definitely support moving to that.

**Comment by domenic** [comment]
We've been doing it as "Let (_prefix_, _localName_) be the result of..." but only for tuples, not lists. (And it's not documented anywhere.)
