### ISSUE TITLE
Add cloneable option to ShadowRootInit

### ISSUE THREAD

**Issue by rniwa** [whatwg/dom#1137]
Splitting this from [declarative Shadow DOM discussion](https://github.com/whatwg/dom/issues/831). Also see See https://github.com/whatwg/dom/pull/892.

We should add `cloneable` boolean flag to `ShadowRootInit`, whose default is false. When this flag is set to true, [cloning](https://dom.spec.whatwg.org/#concept-node-clone) of the shadow host will clone the shadow root along with its descendants if *clone children flag* is set.

**Comment by rniwa** [comment]
@mfreed7 @domenic @annevk

**Comment by rniwa** [comment]
It seems pretty clear that mode, delegatesFocus, and slotAssignment should be copied. But what about other states like default ARIA role? We probably don't want to preserve ARIA node relationship since newly cloned node may have relationship with other cloned nodes but default ARIA role should probably be copied.

**Comment by rniwa** [comment]
It's also pretty clear that `element.attachShadow({mode: 'closed', cloneable: true}).cloneNode(true)` should continue to throw because that would result in a shadow root that's not attached to any host whereas `element.attachShadow({[~](mode: 'closed', cloneable: true)}); element.cloneNode(true)` should clone the shadow tree.

**Comment by mfreed7** [comment]
> Splitting this from [declarative Shadow DOM discussion](https://github.com/whatwg/dom/issues/831). Also see See #892.

See also https://github.com/whatwg/html/pull/5465.

> We should add `cloneable` boolean flag to `ShadowRootInit`, whose default is false. When this flag is set to true, [cloning](https://dom.spec.whatwg.org/#concept-node-clone) of the shadow host will clone the shadow root along with its descendants if _clone children flag_ is set.

I'm supportive of this proposal.



> It's also pretty clear that `element.attachShadow({mode: 'closed', cloneable: true}).cloneNode(true)` should continue to throw because that would result in a shadow root that's not attached to any host whereas `element.attachShadow({[~](mode: 'closed', cloneable: true)}); element.cloneNode(true)` should clone the shadow tree.

Seems reasonable to me, I think. I don't think we should allow direct cloning of the shadow root itself. That's more complicated, and I don't know what the use case is.

**Comment by mfreed7** [comment]
I should also have added that I've included `clonable` in https://github.com/whatwg/dom/pull/892.
