### ISSUE TITLE
 document.execCommand('copy') is deprecated so is it any other solution for support ios device.

### ISSUE THREAD

**Issue by bemes9226** [whatwg/dom#1144]
i used this document.execCommand('copy') but its not copied in ios devices, when i select rich text from webapp clicked on copytext button then pasted in word in desktop its working fine with styles, but in ios(ipad..) its not pasted any content.
need to work as desktop ,it will pasted with styles formatting.but not in ios.when i select text we are getting selectedtextRange 
as plain text so how we can get with styles.
let selectedText = RangeUtils.getPlainTextFromRange(this.selectedTextRange);

    this.clipboardService.copyFromContent(selectedText);
note:i found one solution but its giving white spaces and styles not applied in word.
.copyFromContent(selectedText);

**Comment by annevk** [comment]
This should go to https://feedbackassistant.apple.com/ or https://bugs.webkit.org/. This repository is for issues with the DOM Standard.
