### ISSUE TITLE
MutationObserver GC section looks bogus

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#1159]
As discovered in https://github.com/whatwg/dom/pull/1152#issuecomment-1424788407 by @shaseley.

1. Strong references are implied.
2. The weak reference is about a concept the specification doesn't acknowledge at all. I vaguely recall that it might have been refactored away.

**Comment by annevk** [comment]
This originated in https://www.w3.org/Bugs/Public/show_bug.cgi?id=16638.

I think the main problem is the handling around https://dom.spec.whatwg.org/#mutationobserver-node-list. We don't ever seem to empty it currently.

1. Should that be a list of weak references? I guess so.
2. Should we explicitly empty it when invoking `disconnect()`? I guess so.

With that I think we can remove https://dom.spec.whatwg.org/#garbage-collection as that seems largely bogus.

@rniwa @smaug---- thoughts?

**Comment by smaug----** [comment]
Is (2) needed? Nodes may disappear from the list at any point. Somehow the node list would need to be able handle weak references and that should be enough, no?

I don't know if https://dom.spec.whatwg.org/#garbage-collection  is bogus. Perhaps not very clear though.
But if the node list could just explicitly handle weak references, that should be enough, I think.
Doing also (2) might make the spec easier to understand.

(In Gecko MutationObserver has a strong list of MutationReceivers, which are the things bound to a node to observe some changes. MutationReceivers don't own the relevant node. A MutationReceiver will get notified when the Node is about to be deleted and at that point it asks MutationObserver to drop any references to itself. Calling disconnect() removes all the MutationReceivers from the MutationObserver)

**Comment by annevk** [comment]
I guess you're right that they'll automatically disappear anyway. I don't have a lot of experience with weak references so I don't know if clearing them proactively like that is bad/who cares/good.

There's also #713 (and #720) about the global list of `MutationObserver` objects being wrong. https://github.com/whatwg/dom/issues/713#issuecomment-443606097 still seems like the correct solution for that.

I'll try to create a PR for this and then get everyone involved to date to review.
