### ISSUE TITLE
Documents never have their node document set?

### ISSUE THREAD

**Issue by jyasskin** [whatwg/dom#1178]
Sorry if I'm just failing at reading the specification, but I couldn't find where a document node's [node document](https://dom.spec.whatwg.org/#concept-node-document) is initialized. Neither [`new Document()`](https://dom.spec.whatwg.org/#dom-document-document) nor [`createHTMLDocument()`](https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument) mention it.

This would normally be an odd thing to want, since the document's node document is always itself, but we're traversing that edge when we want to get the [node navigable](https://html.spec.whatwg.org/#node-navigable) of a Document, like in https://html.spec.whatwg.org/#doc-container-document.

**Comment by annevk** [comment]
I think you are correct. I'd suggest adding a paragraph below https://dom.spec.whatwg.org/#concept-document:

> A document's node document is itself.
