### ISSUE TITLE
Document.documentURI and Document.URL attributes behaviour

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#118]
Document has associated URL (https://dom.spec.whatwg.org/#concept-document-url), which is some URL from URL spec. But this internal state is directly represented as DOMString or is a more complex structure? I ask because Document.documentURI and Document.URL attributes must return the URL, without any serialization, what is oposite to "6.6. URL APIs elsewhere" (https://url.spec.whatwg.org/#url-apis-elsewhere).  In the other site URL spec has concept like URL string (https://url.spec.whatwg.org/#syntax-url).

**Comment by annevk** [comment]
Yeah, these should serialize.

**Comment by ArkadiuszMichalski** [comment]
The same story is for `Node.baseURI` (https://dom.spec.whatwg.org/#dom-node-baseuri). 
Bug https://www.w3.org/Bugs/Public/show_bug.cgi?id=20976 was closed, so I ask here: nullable for this attribute is necessary? Value for document's base URL is some URL (https://dom.spec.whatwg.org/#concept-document-base-url), and default value is "about:blank". Is there any mechanisms that set and return null value for `Node.baseURI`?

I test this behaviour in some methods that create new document (without touching parser HTML/XML) and see:
- Firefox always return `about:blank` what is correct per actual spec
- Chrome and Opera (Presto) always return null what is correct per older spec (but the same happen for `Document.URL` and `Document.documentURI`). Sometimes Chrome can produce correct result and return `about:blank`, for example when we create new IFRAME element, before loading any resources. 
- IE11 doesn't support `Node.baseURI`

**Comment by annevk** [comment]
That base URL bug had a different focus. I think you're correct that it might no longer need to be nullable.

**Comment by annevk** [comment]
The `baseURI` issue was fixed in #131.

**Comment by annevk** [comment]
Thank you!
