### ISSUE TITLE
Clarification on document tree and DOM tree

### ISSUE THREAD

**Issue by TKDev7** [whatwg/dom#1188]
The document tree and DOM tree are not the same thing, although they are related. The document tree refers to the hierarchical structure of an HTML or XML document. This structure is created by the author and is static. The DOM tree, on the other hand, is a representation of the document tree in memory, created by the browser when the document is loaded.

Is my understanding correct?

**Comment by annevk** [comment]
How does this question relate to the DOM Standard?

**Comment by annevk** [comment]
That might be worth cleaning up a bit. I recommend filing an issue against whatwg/html. It should say "node tree" instead.
