### ISSUE TITLE
Attribute change steps should run after setting the value, not before

### ISSUE THREAD

**Issue by emilio** [whatwg/dom#1190]
https://dom.spec.whatwg.org/#concept-element-attributes-change first runs the change steps, then sets the value.

That means that if the steps trigger something that then changes the relevant attribute, per spec we should keep the "old" value, which seems wrong.

Example:

```html
<!doctype html>
<div popover="manual">wat</div>
<button>Hide</button>
<script>
let div = document.querySelector("div");
div.addEventListener("beforetoggle", function(e) {
  if (e.newState == "closed") {
    this.setAttribute("popover", "manual");
  }
})
document.querySelector("button").addEventListener("click", function(e) {
  div.removeAttribute("popover");
});
div.showPopover();
</script>
```

Per spec, after clicking the value the `popover` attribute should not be there, which is wrong and doesn't match implementations.

My _guess_ is that modulo that case this is generally not very observable, because other attribute change steps are usually async.

It feels very weird tho that `removeAttribute` runs script synchronously for popover btw...

cc @mbrodesser-igalia, @mfreed7, @domenic, @annevk, @smaug----

**Comment by annevk** [comment]
Could you review #1176?

I think there are a couple attribute listeners that might run script and they're not as bad as mutation events, but if there are multiple there could well be ordering issues I suppose.

**Comment by mfreed7** [comment]
@josepharhar

**Comment by josepharhar** [comment]
@emilio does https://github.com/whatwg/dom/pull/1176 resolve this issue? At least with regards to DOM spec?

**Comment by annevk** [comment]
It solves the ordering problem. You still have synchronous notification of a node tree mutation. I think when I previously looked into such notifications I did not find them problematic for attributes. But maybe someone else should look into that again, especially with Chromium wanting to remove mutation events.

**Comment by mbrodesser-Igalia** [comment]
Given https://github.com/whatwg/dom/pull/1176 was merged, this can be closed?

**Comment by annevk** [comment]
I think so. @emilio please reopen or say something if you disagree.
