### ISSUE TITLE
Does the currentEvent variable make a sense in Inner Invoke?

### ISSUE THREAD

**Issue by dSalieri** [whatwg/dom#1191]
Now we have this:
> 7. Let currentEvent be undefined.
> 8. If global is a [Window](https://html.spec.whatwg.org/multipage/nav-history-apis.html#window) object, then:
>    1. Set currentEvent to global’s [current event](https://dom.spec.whatwg.org/#window-current-event).
>    2. If invocationTargetInShadowTree is false, then set global’s [current event](https://dom.spec.whatwg.org/#window-current-event) to event.

>12. If global is a [Window](https://html.spec.whatwg.org/multipage/nav-history-apis.html#window) object, then set global’s [current event](https://dom.spec.whatwg.org/#window-current-event) to currentEvent.

Can we short into this:
> 7. If global is a [Window](https://html.spec.whatwg.org/multipage/nav-history-apis.html#window) object, then:
>    1. If invocationTargetInShadowTree is false, then set global’s [current event](https://dom.spec.whatwg.org/#window-current-event) to event.

>11. If global is a [Window](https://html.spec.whatwg.org/multipage/nav-history-apis.html#window) object, then set global’s [current event](https://dom.spec.whatwg.org/#window-current-event) to undefined.

I wondered because `currentEvent` always has `undefined` value. Do we have a case when this reduction could break the logic?

**Comment by dSalieri** [comment]
@annevk nested events right? In that case it make sense, you're right.

**Comment by miketaylr** [comment]
> I think this makes sense when the listener dispatches another event. In that case there will be a current event.

Yep.
