### ISSUE TITLE
Explicitly update the child's parent

### ISSUE THREAD

**Issue by TomokiMiyauci** [whatwg/dom#1221]
In the current specification, updating a child's parent reference is implicit and does not seem to be described anywhere.

For example, in [appendChild](https://dom.spec.whatwg.org/#dom-node-appendchild), the parent's children are explicitly modified by [insert](https://dom.spec.whatwg.org/#concept-node-insert).

> 2. If child is null, then append node to parent's children.
> 3. Otherwise, insert node into parent's children before child's index.

Somewhere before or after this, the appended node's parent reference should also be updated, but this is implicit.

When is the appropriate time for this?

**Comment by pshaughn** [comment]
"Parent reference" isn't a concept in the spec. The parent-child relationship is _defined_ in https://dom.spec.whatwg.org/#trees ; if X is a child of Y, then Y _by definition_ is a parent of X. When your implementation is using a two-way pair of references as an implementation detail of tracking this relationship, it probably should set them both at the same time.

**Comment by TomokiMiyauci** [comment]
> An object that participates in a [tree](https://dom.spec.whatwg.org/#concept-tree) has a parent, which is either null or an object, and has children,

I thought this expression meant that each node has an internal slot of parent and children.
But, certainly the word "associated" was not used.

The question has been answered. Thanks!
