### ISSUE TITLE
"connected" should be defined for all kinds of nodes

### ISSUE THREAD

**Issue by zcorpan** [whatwg/dom#1259]
### What is the issue with the DOM Standard?

> An [element](https://dom.spec.whatwg.org/#concept-element) is connected if its [shadow-including root](https://dom.spec.whatwg.org/#concept-shadow-including-root) is a [document](https://dom.spec.whatwg.org/#concept-document).

Since `isConnected` is an attribute of `Node`, the "connected" concept should be defined for all kinds of nodes, not just elements.

HTML also expects text nodes to have "connected" defined, as otherwise text outside an open modal dialog is not inert: https://html.spec.whatwg.org/multipage/interaction.html#modal-dialogs-and-inert-subtrees

**Comment by annevk** [comment]
This should be as simple as replacing "element" with "node". This also seems to apply to the "in a document tree" and "in a document" definitions. We should fix those at the same time.
