### ISSUE TITLE
Some tweaks for Nodes

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#127]
==
ensure pre-insertion validity (https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity)
6. doctype
 "parent has a doctype child, an element is preceding child, or child is null and parent has an element child." << "preceding" operates on two object (nodes) but here `child` can be `null` so it's strange. Maybe write "...,child is not null and element is preceding child,..."    
And maybe clarify some things in this three condition:
"doctype is following child." << we don't see what exactly "doctype" is, so better use "doctype in/inside/from parent" or write full prose "parent has a doctype which is following child"
"element is preceding child" << like above, better use "element in//inside/from parent"

==
https://dom.spec.whatwg.org/#dom-node-normalize
One typo, in greenbox above we have ()().

**Comment by annevk** [comment]
Thank you!

> And maybe clarify some things in this three condition:

These already seem unambiguous given the other constraints.
