### ISSUE TITLE
I can't find where inserting DocumentType nodes into Element nodes is disallowed

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#1278]
### What is the issue with the DOM Standard?

https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity seems like it should disallow it but I can't find any step that does so. Am I missing something obvious?

Chrome and Firefox disallow such insertions. http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=12589

**Comment by annevk** [comment]
> If either node is a [Text](https://dom.spec.whatwg.org/#text) [node](https://dom.spec.whatwg.org/#concept-node) and parent is a [document](https://dom.spec.whatwg.org/#concept-document), or node is a [doctype](https://dom.spec.whatwg.org/#concept-doctype) and parent is not a [document](https://dom.spec.whatwg.org/#concept-document), then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a "[HierarchyRequestError](https://webidl.spec.whatwg.org/#hierarchyrequesterror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).
