### ISSUE TITLE
Some fix for replace algo and question

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#129]
https://dom.spec.whatwg.org/#concept-node-replace
12. If child’s parent is not null, set removedNodes to a list solely containing child and remove child from its parent with the suppress observers flag set. << first "parent" and "remove" should not be linked? Especially for "remove" because I don't know if you mean "remove algo" or direct term.

And have another question, why in step 13. we again remove `child` from its `parent`? We have it in step 12, or, if `child` is same as `node`, then removing from `parent` is done in step 10. via "adopt algo" (https://dom.spec.whatwg.org/#concept-node-adopt).

**Comment by nox** [comment]
@ArkadiuszMichalski @annevk Some very bad amending shenanigans happened when I did the initial patch, will fix that tonight.
