### ISSUE TITLE
Missing arguments for “locate a namespace prefix” in `lookupPrefix` steps

### ISSUE THREAD

**Issue by bhathos** [whatwg/dom#1302]
In the `lookupPrefix` [operation steps](https://dom.spec.whatwg.org/#dom-node-lookupprefix), there are three “invocations” of the [“locate a namespace prefix”](https://dom.spec.whatwg.org/#locate-a-namespace-prefix) algorithm which only pass its _element_ argument, not its _namespace_ argument:

- “the result of **locating a namespace prefix** for its _document element_”
- “the result of **locating a namespace prefix** for its _element_”
- “the result of **locating a namespace prefix** for its _parent element_”

Unless there’s a calling convention that I’m unaware of that makes it implicit that the local _namespace_ “variable” should be passed down, this seems like a mistake. Note that in the `Element` case, _namespace_ is already explicitly passed:

- “the result of **locating a namespace prefix** for _it_ using _namespace_”

**Comment by annevk** [comment]
Nice find. This has been broken forever: 43213eda4f80407950a897cc0b654ded5615809e.

I suspect that in all these cases we need to pass _namespace_ on. The test I added at the time suggests the same. I guess I should fix this.
