### ISSUE TITLE
Suggestion to Add Translated Link for dom (Simplified Chinese 简体中文)

### ISSUE THREAD

**Issue by JinDX** [whatwg/dom#1309]
### What is the issue with the DOM Standard?

I have completed the translation of the dom specification into Simplified Chinese (简体中文). Here is the link to the translated document:

- [Translated version of the specification in Simplified Chinese](https://htmlspecs.com/dom)

It would be helpful for international users if this link could be added to the official documentation or the README.

Thank you for considering this request!

**Comment by annevk** [comment]
Thank you! Should be live shortly on https://dom.spec.whatwg.org
