### ISSUE TITLE
Small correct for Mutation observers

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#132]
https://dom.spec.whatwg.org/#mutation-observer-compound-microtask-queued-flag
Missing initial state for this flag, just add "(initially unset)", whe have this for other flags (in this spec and in other spec):
https://dom.spec.whatwg.org/#stop-propagation-flag
https://dom.spec.whatwg.org/#concept-event-listener
https://encoding.spec.whatwg.org/#textdecoder
https://encoding.spec.whatwg.org/#gbk-flag
https://url.spec.whatwg.org/#non-relative-flag

---

https://dom.spec.whatwg.org/#registered-observer
Why we don't have definition for "observer", "options" and "source" with some id? Instead using `<b>` in other place for this terms it would be more convenient to use references. 

---

https://dom.spec.whatwg.org/#interface-mutationrecord
`readonly attribute Node target;` << this IDL should not be mark by `[SameObject]`? It's not change, similarly what we have for root in NodeIterator/TreeWalker (https://dom.spec.whatwg.org/#interface-nodeiterator, https://dom.spec.whatwg.org/#interface-treewalker)

**Comment by annevk** [comment]
They mostly don't have `<dfn>` because it is more work. If someone is interested in adding that I'm happy to review.
