### ISSUE TITLE
"inner invoke" of event listener with "once" doesn't mark listener as "removed"

### ISSUE THREAD

**Issue by awesomekling** [whatwg/dom#1323]
### What is the issue with the DOM Standard?

[inner invoke](https://dom.spec.whatwg.org/#concept-event-listener-inner-invoke) has this step for `once` listeners:

> 5. If listener’s [once](https://dom.spec.whatwg.org/#event-listener-once) is true, then [remove](https://infra.spec.whatwg.org/#list-remove) listener from event’s [currentTarget](https://dom.spec.whatwg.org/#dom-event-currenttarget) attribute value’s [event listener list](https://dom.spec.whatwg.org/#eventtarget-event-listener-list).

However, this doesn't prevent double invocation of the `once` listener, in particular when doing nested event dispatch such as in this WPT test: http://wpt.live/dom/events/remove-all-listeners.html

I believe the fix here is to have **inner invoke** set the [removed](https://dom.spec.whatwg.org/#event-listener-removed) flag on the listener, like programmatically removing the event listener would.

**Comment by annevk** [comment]
I'm not sure I entirely follow.

1. The first event is dispatched.
2. We clone the target's listener list and run each listener.
3. Before the listener that dispatches the second event is run, we remove it from the target's listener list.
4. We run the listener that dispatches the second event.
5. The second event is dispatched.
6. We clone the target's listener list and run each listener.

Why would the listener that dispatches the second event still be in target's listener list in step 6?

---

(The console warning step of https://dom.spec.whatwg.org/#remove-an-event-listener does make it somewhat attractive to invoke that instead.)

---

Aside: the source code for this step currently reads:
```
   <li><p>If <var>listener</var>'s <a for="event listener">once</a> is true, then
   <a for=list>remove an event listener</a> given <var>event</var>'s {{Event/currentTarget}} and
   <var>listener</var> from 
   attribute value's <a for=EventTarget>event listener list</a>.
   <!-- Do this before invocation to avoid reentrancy issues. No need to set removed to true since
        each listener in listeners is run once anyway. -->
```
I wonder if this is actually wrong what else might be wrong here.

**Comment by awesomekling** [comment]
Here's a simplified example:

```html
<script>
    var type = "foo";
    var target = document.createElement("div");

    function listener1() {
        console.log("Listener 1");

        console.log("Before inner dispatch");
        target.dispatchEvent(new Event(type));
        console.log("After inner dispatch");
    }

    function listener2() {
        console.log("Listener 2");
    }

    target.addEventListener(type, listener1, { once: true });
    target.addEventListener(type, listener2, { once: true });

    console.log("Before outer dispatch");
    target.dispatchEvent(new Event(type));
    console.log("After outer dispatch");
</script>
```

When we begin the outer dispatch, the listeners are cloned. `listener2` is in the cloned list.

When we begin the inner dispatch, the listeners are cloned. `listener2` is in this cloned list as well.

After the inner dispatch invokes `listener2`, it's removed from the target, but it's still in the outer dispatch's cloned list.

Does that make sense, or am I missing something here? :)

**Comment by annevk** [comment]
Thanks, yeah, that makes sense. Will fix.
