### ISSUE TITLE
"Element? closest(DOMString selectors);"

### ISSUE THREAD

**Issue by WesNetmo** [whatwg/dom#133]
https://dom.spec.whatwg.org/#dom-element-closest

Can we please have a better name for this? Not a good idea using JQuery's naming here. "closest" gives me no indication about the direction (which is only ancestors).

Should be "queryAncestor" or something.

**Comment by annevk** [comment]
We are not going to change this name. It is already shipping in browsers.

**Comment by cauburtin** [comment]
.parents would have been better imo

**Comment by ZachSaucier** [comment]
`closest` will confuse many people

**Comment by cauburtin** [comment]
+1
