### ISSUE TITLE
consider renaming "namespace" params into "namespaceURI"

### ISSUE THREAD

**Issue by WesNetmo** [whatwg/dom#136]
Change signature of methods like
```
Attr? getNamedItemNS(DOMString? namespace, DOMString localName);
```
into
```
Attr? getNamedItemNS(DOMString? namespaceURI, DOMString localName);
```

Not a really important change, but `namespace` is a keyword in some programming languages;
plus `namespaceURI` is the name used in the API itself (`Element.namespaceURI`, `Node.lookupNamespaceURI`, etc).

**Comment by WesNetmo** [comment]
also the "interface" params in Event functions

**Comment by domenic** [comment]
https://w3ctag.github.io/design-principles/#js-only

**Comment by annevk** [comment]
I don't want this, since they are not URIs, but strings. The old API is somewhat broken in that respect. And as @domenic points out, non-JavaScript is not a concern at all.
