### ISSUE TITLE
Allow usage of IDL attributes for Element::setAttribute?

### ISSUE THREAD

**Issue by frewsxcv** [whatwg/dom#140]
From #whatwg on Freenode yesterday:

> 1:34 PM \<@frewsxcv\> should element.setAttribute work with content attributes in addition to idl attributes
> 11:47 PM \<@annevk\> frewsxcv: it only works on content attributes…

But, given this example:

```html
<body></body>

<script>
// 'bgColor' is the IDL attribute, 'bgcolor' is the content attribute
document.body.setAttribute('bgColor', 'green');
</script>
```

This results in the page turning green for me on Chrome, Firefox, and Safari.

**Comment by ArkadiuszMichalski** [comment]
Html document?
https://dom.spec.whatwg.org/#dom-element-setattribute << step 2. (argument was converted to ASCII lowercase).

**Comment by frewsxcv** [comment]
Welp. Nevermind.
