### ISSUE TITLE
Having getElementsByTagName match on localName is not "web"-compatible for IE and Firefox

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/dom#143]
More precisely, not compatible with people using HP printers.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1236329#c4 for some details.  Note that we have received multiple independent reports of this problem and we haven't even gotten close to shipping this 

The good news is that the HP code in question will do sane feature detection for non-IE and non-Firefox browsers, so speccing and having WebKit/Blink implement the IE/Firefox behavior seems like it should work OK.  At least as far as these HP printers are concerned...

**Comment by bzbarsky** [comment]
Oh, when this is fixed the following web platform tests will need to be adjusted:

    dom/nodes/Document-getElementsByTagName-xhtml.xhtml
    dom/nodes/Document-getElementsByTagName.html
    dom/nodes/Element-getElementsByTagName.html
    dom/nodes/case.html

**Comment by annevk** [comment]
@foolip @hober any concerns from your side if we switch this back?

**Comment by foolip** [comment]
I'm not familiar with the history of this. Was this last changed in commit 90823182dace496f0afeef3796fe836319242a43 and what behavior do you all suspect is going to be web compatible? Any change to getElementsByTagNameNS?

**Comment by annevk** [comment]
I think that was the last time it was changed, yes. The behavior we expect to be compatible is that `getElementsByTagName` matches on qualified name. (`getElementsByTagNameNS` has forever matched on namespace and local name and will continue to do so.)

**Comment by foolip** [comment]
Would that be analogous to [get an attribute by name](https://dom.spec.whatwg.org/#concept-element-attributes-get-by-name)? Lowercase the input for HTML documents, and then match that case-sensitively to a computed qualified name for each element?

**Comment by annevk** [comment]
No, you would have both _input_ and _lowercaseInput_ and then for elements in the HTML namespace you would use _lowercaseInput_ and for other elements you would use _input_.

I might also introduce an element's qualified name concept to make this easier (analogous to attribute's qualified name concept) and also use that to define `tagName`.

**Comment by foolip** [comment]
OK, that's actually not far from what Blink currently does. The collection has both a `m_localName` and a `m_loweredLocalName`, where the latter is used for HTML elements in HTML documents. Changing that to use the qualified name instead sounds like it carries some risk, as presumably `getElementsByTagName('svg')` would no longer find an element with both localName and prefix 'svg'?

**Comment by annevk** [comment]
Correct.

**Comment by foolip** [comment]
An ad-hoc test for the prefix thing: http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3817

It looks like Blink and Edge currently do the same thing, the discrepancy is because `document.createElementNS(htmlNS, 'FOO')` actually lowercases to 'foo' in Edge, which is a separate issue.

In addition to the case in https://github.com/whatwg/dom/issues/143#issuecomment-170508463, there's also the issue that `getElementsByTagName('x:foo')` currently never matches any element in Blink/Edge, because localName cannot contain a colon.

Trying to guess about the interop risk won't do us any good, so if you make the spec change I can try to add a use counter for the cases where the difference would be observable.

**Comment by annevk** [comment]
I'm taking that comment as you not objecting to me changing the standard.

**Comment by foolip** [comment]
Correct, the behavior you want seems reasonable if it's actually web compatible.

CC @tkent-google and @coonsta for possible Blink-side objections.

**Comment by bzbarsky** [comment]
Note that Edge can probably get away with the Blink behavior here in terms of the original issue I ran into because it spoofs the WebKit/Blink UA enough to not get detected as "IE" by the HP printer stuff...

**Comment by foolip** [comment]
The changes LGTM. I took a look at adding use counters in Blink, but it looks a bit messy, and I'd need to spend some more time untangling the two `getElementsByTagName` modes (HTML and non-HTML) and `getElementsByTagNameNS`, as internal code paths are shared in ways that will break.

**Comment by karlcow** [comment]
Just a comment, we have an issue about it on Shiseido Japan website.  https://github.com/webcompat/web-bugs/issues/1143

**Comment by foolip** [comment]
It seems pretty hard to guess about the risks here. Ignoring case folding for a moment, I think there are three possibilities given what has been implemented in various browsers:
1. The input contains no `:` and the author expects to match on localName.
2. The input contains no `:` and the author expects to match on qualified name.
3. The input contains `:` and the author expects to match on qualified name.

This is crazy talk, but it's *possible* that 1+3 would be the most compatible.

**Comment by ayg** [comment]
https://github.com/w3c/web-platform-tests/pull/2808

We need a protocol of some sort to track which spec changes have had test updates.

**Comment by annevk** [comment]
@ayg at some point @overholt was working on a specification dashboard of sorts, not sure if that's still active. But yeah, test updates and filing bugs against browsers would be great if we could keep track of that in some organized manner.

**Comment by overholt** [comment]
I've been busy but would love to get back to https://github.com/overholt/spectracker (disclaimer: super super super idea-y and I'm not a Web programmer :) at some point.

**Comment by cdumez** [comment]
@foolip: any update on blink side?

I am considering updating WebKit but I worry about the compatibility when there is no ´:' . @foolip ´s proposal to match by localname when there is no ':' and by qualifiedname when there is a ´:' seems less risky given we've always matched by localname.

**Comment by cdumez** [comment]
@rniwa

**Comment by cdumez** [comment]
Another reason I would like to match by localName if input has no ':' in input / match by qualifiedName if there is a ':' in input is that I have performance concerns about matching my qualifiedName when there is no ':' in input (common case).

getElementsByTagName() is performance-sensitive. Right now, WebKit matches by localName only which is fast. However, if we adopt the spec has it is, we would have to check both the localName AND the prefix of every element in the subtree. Performance-wise, it would be a net loss.

@foolip 's proposal would only slow down the cases where someone calls getElementsByTagName() with a ':' in the tagName, which is a lot more acceptable.

**Comment by bzbarsky** [comment]
For what it's worth, I've profiled both versions in Gecko.  There is no measurable slowdown from checking whether there is a prefix and in the overwhelmingly common case when there isn't one matching against the qualified name...  So I don't buy the performance argument.  I can sort of buy the compat argument, though note that this has a performance cost too: having to check for ':' in the passed-in string, even when the list is already cached and there isn't much work to be done other than just getting it out of the cache.

**Comment by cdumez** [comment]
I'll experiment with this in WebKit (https://bugs.webkit.org/show_bug.cgi?id=160682) and let you know how it goes.

**Comment by cdumez** [comment]
I updated WebKit to match the latest version of the specification in <http://trac.webkit.org/changeset/204441>. It looks like this was perf neutral. We'll see if it breaks anything once this reaches Safari Technology Preview.

**Comment by RByers** [comment]
I've filed [this chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=645165) to track getting blink changed to match the spec.
