### ISSUE TITLE
Drop "keyevents" as an alias of "keyboardevent" for createEvent

### ISSUE THREAD

**Issue by foolip** [whatwg/dom#148]
There's a test for this in wpt and a proposed fix in Blink:
http://w3c-test.org/dom/nodes/Document-createEvent.html
https://codereview.chromium.org/1569813002/

As discussed in that review, it looks like this alias is only supported by Gecko, and so we think it would be better to drop it from the spec. If it turns out to be unsafe to remove in Gecko, then the only way out is for all other engines to add it.

**Comment by dtapuska** [comment]
TextEvent already behaves similar too. Gecko supports TextEvents; but nobody else does. Of course TextEvent isn't part of the current spec and is deprecated; but nonetheless there are other examples of things Gecko supports that Safari, Edge, and Blink based browsers don't support.

**Comment by annevk** [comment]
Paging @smaug---- for thoughts.

**Comment by foolip** [comment]
TextEvent isn't in http://w3c-test.org/dom/nodes/Document-createEvent.html, fortunately.

Blink/WebKit are also very naughty, by supporting *all* known event interface names for `createEvent`, not just the ones listed in the spec.

**Comment by smaug----** [comment]
Gecko used to have only keyevents, and keyboardevent was added in 
https://bugzilla.mozilla.org/show_bug.cgi?id=238773, so, long ago.
In mozilla-central there are several tests using "keyevents", so I guess would need to fix those and then add some telemetry and based on that say something here.

**Comment by foolip** [comment]
How about removing it from the spec and adding it back only if there's evidence that it's needed for web compat, e.g. if Gecko fails to remove it? Leaving it in risks that someone implements it, if a reviewer doesn't pay close attention.

**Comment by annevk** [comment]
That sounds reasonable to me. @smaug---- is there a bug against Gecko on removing this?

**Comment by ArkadiuszMichalski** [comment]
I open bug for Gecko:
https://bugzilla.mozilla.org/buglist.cgi?quicksearch=createEvent%28%29&list_id=12946726
