### ISSUE TITLE
Exclude style="" by default from mutation observers

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#153]
@esprehn mentioned that Chrome cheats with mutation observers and does not include `style=""`. There might also be some paths where `class=""` gets excluded? @smaug----, does Gecko do that as well?

**Comment by smaug----** [comment]
We try to be consistent. No inconsistency hacks please. They tend to bite us sooner or later.
What we could perhaps do is to add something to the API to exclude style etc changes explicitly.
some kind on negative filter? excludeAttributes = ["style", "class"].

But anyhow, I'm strongly against adding style attribute specific inconsistencies to the API.

**Comment by annevk** [comment]
We're not doing this for custom elements either per https://github.com/w3c/webcomponents/issues/521 so I'm closing this.
