### ISSUE TITLE
classList.toggle(clsName, boolValue)

### ISSUE THREAD

**Issue by cauburtin** [whatwg/dom#160]
I find it useful if we had something like `element.classList.toggle('active', someBoolean)` that would add the class if the boolean is true, and remove it otherwise. without the second argument it would behave like the current `.toggle(clsName)` function, where the boolean is `element.classList.contains(clsName)` actually

**Comment by domenic** [comment]
You may be interested in https://dom.spec.whatwg.org/#dom-domtokenlist-toggle

**Comment by cauburtin** [comment]
oh.. it exists, :), ok
