### ISSUE TITLE
Move "event dispatch pretends Window is Document's parent" magic from HTML into DOM

### ISSUE THREAD

**Issue by cvrebert** [whatwg/dom#164]
i.e. https://html.spec.whatwg.org/multipage/webappapis.html#events-and-the-window-object
Refs http://logs.glob.uno/?c=freenode%23whatwg#c984904

**Comment by domenic** [comment]
Hmm, it would be ideal if this were done without DOM knowing about Window(Proxy). E.g. define some kind of "event target above the document" hook that HTML defines as the Window.
