### ISSUE TITLE
Duplicated Invoking of an event target

### ISSUE THREAD

**Issue by triple-underscore** [whatwg/dom#169]
https://dom.spec.whatwg.org/#dispatching-events

> Let eventPath be a list containing target\.
>...
> For each object in eventPath, in reverse order, if event’s stop propagation flag is unset, invoke object with event\.
> Initialize event’s eventPhase attribute to AT\_TARGET\.
> If event’s stop propagation flag is unset, invoke target with event\.

Since eventPath contains target, this will invoke the target with event twice.

**Comment by annevk** [comment]
Thank you @triple-underscore!
