### ISSUE TITLE
Several references are now wrong after Bikeshed conversion

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#17]
@tabatkins 

[URL], [ENCODING], [WebIDL], [DOM-Parsing], and [UIEVENTS] have wrong statuses and dates.

There is both [SELECTORS-4] and [SELECTORS4].

There is both [CSSOM-VIEW] and [CSSOM-VIEW-1].

**Comment by annevk** [comment]
Informative references from the Goals and Historical sections also regressed. Don't quite want to remove links to the legacy stuff yet since I don't think everything in DOM has been implemented from scratch at this point.

**Comment by Joris-van-der-Wel** [comment]
I am guessing this is the same issue:

All of the links referring to interfaces in the IDL sections on https://dom.spec.whatwg.org/ are broken. For example they link to `#node` instead of `#interface-node`

**Comment by domenic** [comment]
I really think a revert might be a good idea until @TabAtkins gets things straightened out. Having an unusable DOM spec is really bad, and doubly so given that it's a Living Standard. In the future we'd want to locally test any conversion PR before accepting it

**Comment by annevk** [comment]
@tabatkins opinions? Any suggestions for how to create a clean revert?

**Comment by domenic** [comment]
This should do the trick:

```
$ git checkout -f b7563aaf0864c8d104d18c36a9eda036c5205131 -- .
$ git commit -a -m "Reverting Bikeshed and related changes"
$ git push
```

**Comment by tabatkins** [comment]
I'm fixing all this stuff right now, don't worry. ^_^

**Comment by annevk** [comment]
@tabatkins the normative references seem wrong still. Any suggestions for those? I think the rest of the specification is fine at this point.

**Comment by domenic** [comment]
Updated the OP to list the current set of problems.

**Comment by tabatkins** [comment]
Thanks for updating the OP, will burn through this list tomorrow.

**Comment by tabatkins** [comment]
URL had another entry in the CSSWG biblio.ref file; I've removed it, since SpecRef has the correct entry.

Encoding, WebIDL, and DOM Parsing all point to the ED now that I've defaulted WHATWG to that policy.

UI Events is messed up at the SpecRef source; both forms of the name show up in the DB, and neither is an alias of each other, but they should be.  I've filed [a bug](https://github.com/tobie/specref/issues/180) about it; once it's fixed, we can switch the refs to whichever name SpecRef settles on.

CSSOM View and Selectors are another SpecRef issue; they've got the un-numbered one, and I'm able to generate a "fake" numbered one.  I'll put in a PR for SpecRef to have the numbered one as an alias.

**Comment by tobie** [comment]
[Fixed](https://github.com/tobie/specref/commit/5814cf3) the Specref bug.

**Comment by annevk** [comment]
How do I reference historical documents? Currently I reference the old DOM specifications though maybe now that this DOM Standard is accepted by everyone I can cut those ties...

**Comment by tobie** [comment]
@annevk would "IDENTIFIER-YYYYMMDD" be what you're looking for? If not, can you find what you're looking for here: http://www.specref.org/?q=DOM ?

**Comment by domenic** [comment]
Updated the OP. The newest bug appears to be something that slurps in the wrong status and dates.

**Comment by annevk** [comment]
We still have selectors4 and selectors-4. @tabatkins any ideas how to get rid of that?

**Comment by annevk** [comment]
@tabatkins ping!

**Comment by tabatkins** [comment]
Ah, sorry, will look into this again.

**Comment by tabatkins** [comment]
Fixed - SpecRef didn't know about "selectors-4", only "selectors4", so Bikeshed couldn't dedupe it with its auto-generated "selectors-4" reference.

**Comment by annevk** [comment]
Newly noticed:

* AnimationEvent points to [CSS-ANIMATIONS-1]  but we also point to [CSS3-ANIMATIONS].
* TransitionEvent points to [CSS-TRANSITIONS-1]  but we also point to [CSS3-TRANSITIONS].

**Comment by tabatkins** [comment]
Yeah, this reminded me to go fix <https://github.com/tabatkins/bikeshed/issues/389>, and Animations and Transitions are in the PR I'm generating. This'll be fixed once I finish up the PR and get it merged.

**Comment by tabatkins** [comment]
All right, done! They both collapse down to the CSS3-FOO versions, which isn't ideal, but is an artifact of the way the SpecRef data isstructured, and can't easily be fixed. This'll fix itself properly when they get their shortnames fixed in the W3C database.

**Comment by annevk** [comment]
Thanks, https://dom.spec.whatwg.org/#normative looks all good now!
