### ISSUE TITLE
MutationObserver and createShadowRoot()

### ISSUE THREAD

**Issue by rodneyrehm** [whatwg/dom#170]
I'm looking for a way to keep track of ShadowRoots being created. Neither does the current implementation of ShadowDOM/MutationObserver in Firefox 44 and Chrome 48 register a mutation for `element.createShadowRoot()`, nor does either specification mention this situation specifically.

To the best of my knowledge it is currently not possible to get identified when a ShadowRoot is created for an element.

Has this ever been discussed and decided to be ignored, or has this just not come up before?

**Comment by annevk** [comment]
I don't recall it being discussed. Might be best to raise an issue here for now: https://github.com/w3c/webcomponents/issues/new. Also, it's `attachShadowRoot()` these days.

**Comment by rodneyrehm** [comment]
thanks! opened the issue over there :)
