### ISSUE TITLE
Add Attr#nodeName

### ISSUE THREAD

**Issue by zcorpan** [whatwg/dom#171]
https://dom.spec.whatwg.org/#attr

>   readonly attribute DOMString name;

Add `nodeName` as an alias. 10091 resources from 470k pages match `REGEXP_MATCH(content, r'\.attributes\[[a-zA-Z0-9\. -]+\]\.nodeName')` (dataset httparchive:har.chrome_jan_15_2016_requests). Also Live DOM Viewer. :-)

See http://logs.glob.uno/?c=freenode%23whatwg&s=22+Feb+2016&e=22+Feb+2016#c985861

**Comment by annevk** [comment]
Feel free to land your fix. Still think we're doomed and have to add Attr as Node back though.
