### ISSUE TITLE
Syntax-highlight code blocks

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#18]
Now that we have Bikeshed it should be easy to syntax-highlight the code blocks.

```js
<pre><code class="lang-html">
...
</code></pre>
```

Maybe I'll PR it tomorrow.

**Comment by domenic** [comment]
Nevermind, this appears to be working already. Maybe I had the wrong tab open?

**Comment by tabatkins** [comment]
Also, note that it's `lang-markup`, as it applies to all XML-ish languages.
