### ISSUE TITLE
className setter is not defined?

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#183]
https://dom.spec.whatwg.org/#interface-element

> The className
> attribute’s getter must reflect the "class" content attribute\.

Same for id

**Comment by annevk** [comment]
Yes. And https://dom.spec.whatwg.org/#concept-reflect defines what that means. What is the problem?

**Comment by ArkadiuszMichalski** [comment]
`The id attribute’s getter must reflect...`
`The className attribute’s getter must reflect...`
So why not just `The id attribute must reflect...` and `reflect` cover setter and getter?

**Comment by annevk** [comment]
Oh yeah, that is weird. I think that must have regressed somehow. Probably my fault.

**Comment by ArkadiuszMichalski** [comment]
Would be clear if reflect algo use indent for both (setter and getter), now setting is defined "visually outside" thad definition and it can be easy omit.
```
This means that depending on action these steps must be run:
  Setting
    1....
  Getting
    1....
```
or something like that.

**Comment by annevk** [comment]
Good suggestion, done. And thanks @domenic for raising this.
