### ISSUE TITLE
Export the term "target override"

### ISSUE THREAD

**Issue by cvrebert** [whatwg/dom#187]
This term is currently relied upon by HTML: https://html.spec.whatwg.org/#concept-event-target-override

**Comment by annevk** [comment]
I think it would be better for HTML to invoke the dispatch algorithm correctly. I'm not sure we should be introducing named arguments (other than flags).

**Comment by cvrebert** [comment]
That sounds fine too.

**Comment by annevk** [comment]
One problem DOM needs to fix here is that "fire an event" doesn't take a target and target override argument currently and HTML seems to use those anyway.

**Comment by cvrebert** [comment]
Ah, the joys of untypechecked prose algorithms...

**Comment by annevk** [comment]
The other thing we need to fix is that "fire an event" needs to return whatever dispatch returns so HTML can use that instead of "default action" talk.

**Comment by annevk** [comment]
Thanks for reporting this, HTML side is being worked on still, but should be good somewhere next week hopefully.
