### ISSUE TITLE
Some Conformance section stuff is duplicated

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#19]
It looks like some of it is boilerplate from Bikeshed and some of it is from the original.

https://github.com/whatwg/dom/commit/b105abe2fed72000764523b69b97bed57f47815d shows it being added; I'd guess something different between how @tabatkins and @annevk ran Bikeshed

**Comment by annevk** [comment]
Fixed in https://github.com/whatwg/dom/commit/1de425f573b3af07d30cfeef5ac7374298b1bf4f

I had not updated Bikeshed.
