### ISSUE TITLE
Back to previous definition for Element.getAttributeNS()

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#197]
https://dom.spec.whatwg.org/#dom-element-getattributens
This new definition doesn't match the behavior of the browsers, using `get an attribute value` here is wrong, when attr not exist then `null` is returned, not empty string.

**Comment by annevk** [comment]
This regressed in https://github.com/whatwg/dom/commit/e3d82914676ad1e1bf590e1042636e60feddb6ae.

**Comment by annevk** [comment]
Thank you @ArkadiuszMichalski!
