### ISSUE TITLE
"origin alias" doesn't seem to exist in HTML anymore

### ISSUE THREAD

**Issue by tabatkins** [whatwg/dom#200]
Section 4.5 says that the default "effective script origin" of a Document is an alias of its origin, linking "alias" to <https://html.spec.whatwg.org/multipage/browsers.html#concept-origin-alias>. That link doesn't appear to work; it just redirects to <https://html.spec.whatwg.org/multipage/browsers.html#browsers>, and the term "alias" is nowhere on the page.

**Comment by annevk** [comment]
Thanks, but this is #195. I'll try to update this tomorrow. I also need to fix URL for the same reason.
