### ISSUE TITLE
Unify behavior for error handling in supports() and contains() methods

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#202]
Both this  methods don't modificate tokens so probably should have similar behavior when `token` argument has empty string and ASCII whitespace. Currently `contains()` throw (like all other DOMTokenList methods) and `supports()` doesn't throw. So there is two solution:
- change `supports()` to throwing, this method is new so compatibility should not be a problem.
- change `contains()` to not throwing because in this scenerio it's unnecessary (we don't change tokens) so we get little simplification.

BTW:
Step 2. and 3. in "validation steps" (https://dom.spec.whatwg.org/#concept-domtokenlist-validation) probably can be replace by one step. I don't see that you copy passing argument to new variable for any other methods that operate on argument converted to ASCII lowercase:
https://dom.spec.whatwg.org/#dom-document-createelement
https://dom.spec.whatwg.org/#dom-document-createattribute
https://dom.spec.whatwg.org/#concept-element-attributes-get-by-name
https://dom.spec.whatwg.org/#dom-element-setattribute
https://dom.spec.whatwg.org/#dom-element-hasattribute 
but not sure which style is more correct.

**Comment by annevk** [comment]
@cdumez, opinions? I was considering making `contains()` not throwing.

**Comment by cdumez** [comment]
@annevk: Yes, I would be in favor of updating contains() to not throw. The input validation does not bring much here since we are not going to use this token to modify the list. Also, no longer throwing should be fine from a backward-compatibility standpoint.

**Comment by annevk** [comment]
Thanks everyone.

**Comment by cdumez** [comment]
Will align WebKit via:
https://bugs.webkit.org/show_bug.cgi?id=156453

**Comment by bentian** [comment]
Will align Gecko via:
https://bugzilla.mozilla.org/show_bug.cgi?id=1263116
