### ISSUE TITLE
"HTMLCollection is an historical artifact we can..."

### ISSUE THREAD

**Issue by senolv** [whatwg/dom#203]
https://dom.spec.whatwg.org/#interface-htmlcollection

> HTMLCollection is an historical artifact we cannot rid the web of\. Please do not use it in new APIs\.

Please tell us what does this mean in fact.

Does it mean we should not use .getElementsByTagName(), .getElementsByClassName(), .children,
because they all give HTMLCollection back, if yes please show us a way of how to, or what to use instead.

**Comment by annevk** [comment]
My apologies, it's meant as a note for other specification editors. I'll try to clarify the language.

**Comment by annevk** [comment]
Thank you!
