### ISSUE TITLE
Made more formal for object global

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#206]
https://dom.spec.whatwg.org/#dom-document-document
"The Document() constructor, when invoked, must return a new document whose origin is the origin of the global object’s associated document."
What is global object here? In DOM we don't have such definition so you mean this from HTML https://html.spec.whatwg.org/multipage/webappapis.html#global-object? If yes maybe use refference?

This term exist in some other places:
https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener
https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener
https://dom.spec.whatwg.org/#dom-documentfragment-documentfragment
https://dom.spec.whatwg.org/#dom-text-text
https://dom.spec.whatwg.org/#dom-comment-comment
https://dom.spec.whatwg.org/#dom-range-range

**Comment by annevk** [comment]
Thanks again for reporting this!
