### ISSUE TITLE
Inconsistency when using "Rethrow any exceptions"

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#209]
What is convenction when we have nested algorithms and some of them throws exception, this exception should be always rethrows in the calling algorithm (and marking it in prose)? Now it's  unclear, especially for node mutations.
Some analysis:

https://dom.spec.whatwg.org/#dom-element-insertadjacentelement
`insertAdjacentElement(where, element)` (rethrow for "insert-adjacent") > "insert-adjacent" (rethrow for "pre-insert") > "pre-insert" (not rethrow for "ensure pre-insertion validity") > "ensure pre-insertion validity" (throw)
"
https://dom.spec.whatwg.org/#dom-node-appendchild
`appendChild(node)` (not rethrow for "append") > "append" (not rethrow for "pre-insert") > "pre-insert" (not rethrow for "ensure pre-insertion validity") > "ensure pre-insertion validity" (throw)

https://dom.spec.whatwg.org/#dom-node-replacechild
`replaceChild(node, child)` (not rethrow for "replace") > "replace" (throw)

Only three examples, but there are more, not olny for nodes, at once hard to locate all of them.

**Comment by annevk** [comment]
The preference is to call it out since it's not always obvious what should be done to implementers. And sometimes we don't rethrow the exception, but report it instead (event dispatch for instance).

Hopefully longer term we have some ECMAScript-inspired formalism in IDL we can use, but until that time this is what we got.

**Comment by annevk** [comment]
I posted a PR to fix at least these. Review welcome. If you find more I'm happy to take PRs from you or new issues.
