### ISSUE TITLE
Header is all wrong

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#21]
Current:

> This version:
>    https://dom.spec.whatwg.org 
> Version History:
>    https://twitter.com/thedomstandard 

Desired:

> Participate:
>    File an issue (open issues) 
>    IRC: #whatwg on Freenode 
> Version History:
>    https://github.com/whatwg/dom/commits 
>    @thedomstandard

**Comment by annevk** [comment]
Mostly there now. Still shows "This version" field... @tabatkins?

**Comment by domenic** [comment]
You also will want to add appropriate `<a>`s instead of just URLs; they don't get auto-linkified/Twitter-username-ified
