### ISSUE TITLE
"The previousElementSibling and nextElementSibli..."

### ISSUE THREAD

**Issue by senolv** [whatwg/dom#210]
https://dom.spec.whatwg.org/#interface-nondocumenttypechildnode

> The previousElementSibling and nextElementSibling attributes have been removed from DocumentType nodes for compatibility reasons\. If these additions are deemed compatible enough in the future, they could be reinstated\.

If there wasn´t a compability problem, in which interface would they both be listed? Node or Element?

**Comment by domenic** [comment]
ChildNode

**Comment by senolv** [comment]
Thanks

**Comment by ArkadiuszMichalski** [comment]
And bug for this:https://www.w3.org/Bugs/Public/show_bug.cgi?id=23691
On the occasion, is there any approximate time when this incompatybile problem will be checking again or we stuck with this interface forever?

**Comment by annevk** [comment]
We should probably just suck it up and just note they can't be put on `DocumentType`.

**Comment by senolv** [comment]
that would be more appropiate, when they belong to ChildNode.

The more Objects you create, the more you confuse.

The same matter with NonElementParentNode, no sry, it´s not the same, it´s harder to comprehend.

Instead of just mentioning that there are compability conflicts with jquery´s old versions, you create a new object and say, this interface will be removed and its method will be an attribute of ParentNode when jquery... 

What I try to say is, when anyone is interested in dom standarts jquery is not important enough to be the reason to make me wait for the time when a core-tech dominates a framework.


I´m sry for my bad language, it´s late in the night, hope you could catch my thughts

**Comment by annevk** [comment]
It's harder to comprehend to have multiple mixins, sure, but we cannot actually change any of this. We can just clarify that it will remain this way since it's unlikely to become that much less of a problem.

**Comment by ArkadiuszMichalski** [comment]
> We should probably just suck it up and just note they can't be put on `DocumentType`.
My guess is that the same will happen to `NonElementParentNode`? Comparing to other 
potential changes (Attr, CDATASection, Documnet) this comment looks so pessimistic, but to be sure I ask again for another 3 years:)

**Comment by annevk** [comment]
Yeah, we should update both and indeed add back some of the ancient features. It's pretty clear that browsers are not going to remove them. It's just not worth the amount of churn it turns out.

**Comment by annevk** [comment]
Thanks for reporting this @senolv!
