### ISSUE TITLE
Default value for node document or always set it explicitly

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#212]
https://dom.spec.whatwg.org/#concept-node-document
"Each node has an associated node document, set upon creation, that is a document."
So every time when we create new node we must set node document for this node. But in some case you don't do this:

https://dom.spec.whatwg.org/#dom-element-insertadjacenttext
1. Let text be a new Text object whose data is data. < btw, you can change this to "new Text node" (and linked /Text/ and /node/) like in any other case.
Of course finally this new Text node will have correct node document because in step 2. we run "insert adjacent" which use "adopt" but it does not fit to definition node document.

Other similar cases:
https://dom.spec.whatwg.org/#dom-node-textcontent << element's setter
https://dom.spec.whatwg.org/#dom-domimplementation-createhtmldocument << this is more interesting because you also use new element (html/head/title/body) but it's to general, how you create them (using "create an element" algorithm)? After changing definition around Element (due to custom elements) I don't see that default value for namespace and namespace prefix is null. This was removed: "When an element is created, its local name is always given. Unless explicitly given when an element is created, its namespace and namespace prefix are null."
 
Maybe define default value for node document to global object’s associated document for other node than document and for document use himself (or something else more uniwersal) and change it explicitly in other algorithms only when necessary? If no then node document should always be set explicitly when node is created in some cases, even if for the moment will be automatically changed by other step in algorithm because that is the definition of node document, but it's a little uncomfortable.

**Comment by annevk** [comment]
Hmm yeah, we should probably use https://dom.spec.whatwg.org/#concept-create-element to define `createHTMLDocument()`. @domenic?

**Comment by annevk** [comment]
(I don't think a default node document works well as it's typically just the node document of the caller, we'll just need to remember to properly define it everywhere.)

**Comment by ArkadiuszMichalski** [comment]
So DOM requires light adjustments, but HTML... every time when node (in most case element) is create its node document should be set. Sometimes I see uniwersal rules, like this for XML parsing:
https://html.spec.whatwg.org/multipage/xhtml.html#templateTagXML
but in some places there are gaps (or maybe I not yet located the universal description):

https://html.spec.whatwg.org/multipage/dom.html#dom-tree-accessors:svg-title-4
https://html.spec.whatwg.org/multipage/dom.html#dom-tree-accessors:the-title-element-3
Table methods:
https://html.spec.whatwg.org/multipage/tables.html#dom-table-createcaption
https://html.spec.whatwg.org/multipage/tables.html#dom-table-createthead
https://html.spec.whatwg.org/multipage/tables.html#dom-table-createtfoot
https://html.spec.whatwg.org/multipage/tables.html#dom-table-createtbody
https://html.spec.whatwg.org/multipage/tables.html#dom-table-insertrow
https://html.spec.whatwg.org/multipage/tables.html#dom-tbody-insertrow
https://html.spec.whatwg.org/multipage/tables.html#dom-tr-insertcell

Probably more exist like this text node (https://html.spec.whatwg.org/multipage/forms.html#the-option-element:text-2).

**Comment by annevk** [comment]
We should probably patch all of those. Would you be willing to file a sibling issue against whatwg/html?

**Comment by ArkadiuszMichalski** [comment]
I will open but definitions for element should be more universal, this node has some internal state and now only shadow root has initial null value. Writing in other specs just "create a new `xxx` element" is too general, directly using [create an element](https://dom.spec.whatwg.org/#concept-create-element) requires passing 5 or 6 values what is uncomfortable.

**Comment by annevk** [comment]
Yeah, @domenic was positing that there would not be many callers and therefore uncomfortable was fine, but I think he might have been mistaken to some extent, but we can refactor once we find out for sure.

**Comment by ArkadiuszMichalski** [comment]
P&S also creates new elements, only one time missing node document for [parseFromString step 4.](https://www.w3.org/TR/DOM-Parsing/#dfn-dom-domparser-parsefromstring). @annevk any plans in the near future to bring back P&S under the WHATWG?
And don't forget about [innerText](http://rocallahan.github.io/innerText-spec/index.html) (also creates text and element nodes).

**Comment by annevk** [comment]
No concrete plans, though with it not being maintained it's somewhat rising in importance.

**Comment by annevk** [comment]
Closing this since it's addressed in DOM and HTML.
