### ISSUE TITLE
Consider making dispatchEvent() unset stop (immediate) propagation flags

### ISSUE THREAD

**Issue by ayg** [whatwg/dom#219]
If you call stop(Immediate)Propagation() on an event, then try to dispatch the event again, Chrome will not do so.  IE 11 and Gecko both will re-dispatch it, because they unset the flags in dispatchEvent().  The spec currently matches Chrome.  What's the rationale for this?  smaug said <https://bugzilla.mozilla.org/show_bug.cgi?id=698929#c6> he prefers the Gecko/IE behavior.  I don't know why you'd fire the same event twice, so I can't say for sure which makes more sense.  But at first glance I'd think it makes more sense that stopPropagation() cancels the current dispatch, rather than making the event undispatchable in the future.

Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1263937

**Comment by ayg** [comment]
If we do this, it might make sense to have the start of dispatch unset the stop propagation flag, so .stopPropagation() has no detectable effect if called outside dispatch.

**Comment by ArkadiuszMichalski** [comment]
I see that behaviour for `Event.initEvent()` it's also inconsistent, this method should unset stop propagation flag, stop immediate propagation flag, and canceled flag. Even if `dispatchEvent()` not unset them by default then we should do this manually via `Event.initEvent()`.
https://dom.spec.whatwg.org/#dom-event-initevent
```js
<!DOCTYPE html>
<script>
	var ev = document.createEvent("Event");
	ev.stopPropagation();
	ev.initEvent("type", false, false);
	document.addEventListener("type", function() {alert("hello");}, false);
	document.dispatchEvent(ev);
</script>
```
Only Chrome alerts.

```js
<!DOCTYPE html>
<script>
	var ev = document.createEvent("Event");
	ev.initEvent("type", false, false);
	ev.stopPropagation();
	document.addEventListener("type", function() {alert("hello");}, false);
	document.dispatchEvent(ev);
	ev.initEvent("type", false, false);
	document.dispatchEvent(ev);
</script>
```
Only Firefox alerts.

**Comment by annevk** [comment]
I found https://github.com/whatwg/dom/commit/ab8631eb178e2834b8629eee81bde52f5c50ea0e and https://github.com/whatwg/dom/commit/b5791f67ce57860f07414e120fb67e2b39793786 neither of which gives much context.

However, https://lists.w3.org/Archives/Public/www-dom/2011JanMar/thread.html#msg54 was emailed around that time. It seems to suggest that Opera (Presto) and WebKit had the same behavior.

**Comment by ayg** [comment]
Could we ask Blink/WebKit if they're interested in switching to the IE/Firefox behavior?

**Comment by annevk** [comment]
Sure, @travisleithead, @foolip, @RByers?

**Comment by RByers** [comment]
Doesn't seem likely to matter much either way to me.  Has anyone found any example of a website or developer noticing this difference or caring either way?  I assume Edge matches blink and WebKit?  We could measure to see if this ever happens in practice (stopProgation bits already set on entry to dispatchEvent).  If so, without some more motivation, I wouldn't consider this worth non-trivial compat risk to change blink and the spec.  @tkent-google WDYT?

**Comment by tkent-google** [comment]
I agree with @RByers.  This is a trivial issue, and changing Blink behavior looks low risk.

**Comment by annevk** [comment]
Oh, I had not considered Edge, if it agrees with Blink/WebKit I'm not sure it's worth the churn... @travisleithead?

**Comment by foolip** [comment]
I put https://github.com/whatwg/dom/issues/219#issuecomment-209605497 into https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4071 and https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4072

Edge does not alert for either of these, so it looks like neither `initEvent` nor `dispatchEvent` resets the flags in Edge? That's not what @ayg said so maybe I'm testing it wrong.

**Comment by cvrebert** [comment]
> https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4071 and https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4072
>
> Edge does not alert for either of these

Neither does IE11.

**Comment by ayg** [comment]
The test I was thinking about was something like this:

https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4075

Firefox and IE11 fire the event, Chrome does not.  I don't have access to Edge or WebKit.  If they match one or the other, obviously the spec should follow the majority.

I'm now pretty confused about what each browser does here.  They all seem to unset the stop propagation flag under somewhat different circumstances.

**Comment by cvrebert** [comment]
> https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4075

WebKit doesn't fire the event.
Edge 13.10586 fires the event.

**Comment by foolip** [comment]
> I'm now pretty confused about what each browser does here. They all seem to unset the stop propagation flag under somewhat different circumstances.

From reading the code, Blink and WebKit only reset the flags in `Event::initEvent`. I'm not so confident in my grep skills for Gecko, but it looks like `EventTargetChainItem::HandleEventTargetChain` is the only place they are reset? What would that correspond to in spec terms?

**Comment by foolip** [comment]
FWIW, if the flags are reset at all, I think that only doing it at the end of dispatch would make the most sense. Doing it at the beginning of dispatch might amount to the same thing in black box testing, though.

**Comment by ayg** [comment]
I think Gecko resets effectively at the end of dispatch.  Beginning vs. end is distinguishable if you call .stopPropagation() outside of a dispatch.  Resetting at the beginning of dispatch would mean that .stopPropagation is restricted to the current event dispatch and does nothing if the event is not currently being dispatched.  Resetting at the end would mean it's restricted to the current event dispatch, or next one if the event is not currently being dispatched.

Resetting at the beginning of dispatch seems simplest.  It means you can use an event object multiple times without having to call initEvent() again (which new event types don't have, right?).  I don't see why the event shouldn't be reusable just because you didn't reinitialize it -- it doesn't seem intuitive to me.  If we do this, we could then remove the reset in initEvent, because it's no longer black-box detectable.

I don't know why authors are dispatching their own events at all, by the way, let alone why the same event twice.  But given that we do allow dispatching the same event twice, I don't see how it makes any sense for a previous .stopPropagation() call to ever stop future dispatches.

**Comment by foolip** [comment]
> Resetting at the end would mean it's restricted to the current event dispatch, or next one if the event is not currently being dispatched.

Thanks @ayg, I didn't think hard enough about that. I agree that doing it at the beginning of dispatch seems simplest, and then there's no point in doing it in `initEvent()` as well.

**Comment by ayg** [comment]
However, the default prevented flag is only reset on initEvent in Gecko.  Testing indicates that Chrome does not reset on dispatch -- does it reset anywhere else?  I couldn't get .defaultPrevented to work on IE 11 (always seems to return false).  So once default prevented is already interoperably reset only in initEvent, it makes the most sense if the propagation flags follow suit.  Unless IE does reset the default prevented flag on dispatch instead?  Then maybe we should converge on IE.

**Comment by foolip** [comment]
Chrome sets the default prevented flag (`m_defaultPrevented`) to false in `initEvent()`, and if one sets `event.returnValue = true`. I guess it would make sense to reset that flag at the beginning of dispatch for the same reasons.

**Comment by ayg** [comment]
We might still want to reset in initEvent, though, because authors might be using that as a way to reset the defaultPrevented flag within a dispatch.

**Comment by ayg** [comment]
Come to think of it, that makes it black-box detectable whether initEvent resets the propagation flags too.

**Comment by foolip** [comment]
https://dom.spec.whatwg.org/#dom-event-initevent is a no-op during dispatch, so that shouldn't be an issue. (There's a Blink bug there one might come across in testing, namely that rather than check an "is dispatching" flag, it checks `dispatched()`, which returns true if `event.target` is non-null.)

**Comment by cdumez** [comment]
FYI, I have recently updated WebKit to match more closely the specification:
1. We no longer prevent calling initEvent() again on a previously dispatched event. We now only prevent calling initEvent() while the event is being dispatched.
2. Calling initEvent() now resets the target

However, I have not updated our behavior to reset the (immediate) propagation flags at the end of dispatchEvent(). The reason I have not done it is because the DOM specification does not say we should (even though there is a web-platform-test that expects this behavior). I personally would not be opposed to updating WebKit's behavior to match Firefox as long as we update the DOM specification accordingly. It seems less risky for WebKit / Blink to align with Gecko than the other way around.

But really, I do not mind either way as long as we align browsers somehow and our web-platform-tests match the DOM specification.

**Comment by annevk** [comment]
@smaug---- any opinions on the suggestion from @ayg to reset propagation flags at the beginning of event dispatch? https://github.com/whatwg/dom/issues/219#issuecomment-211366587

I'd be okay with specifying the reset-at-the-end-of-dispatch behavior too by the way. The difference doesn't seem too important.

**Comment by smaug----** [comment]
I've seen code where stopPropagation is called before dispatch to prevent event listeners to be called, but let default handling still happen. And that is a valid use case.

**Comment by smaug----** [comment]
(that applies mostly to click handling )

**Comment by annevk** [comment]
Yeah, no new events should have "default handling", but fair enough. I guess I'll align with reset at-end-of-dispatch then.

**Comment by cdumez** [comment]
Thanks, I will align WebKit via https://bugs.webkit.org/show_bug.cgi?id=160853

**Comment by cdumez** [comment]
It looks like there are a couple of web platform tests that need updating:
- dom/events/Event-initEvent.html

> Calling initEvent must unset the stop propagation flag.	assert_unreached: Reached unreachable code
> 
> @http://w3c-test.org/dom/events/Event-initEvent.html:88:5
> Test.prototype.step@http://w3c-test.org/resources/testharness.js:1403:20
> Test.prototype.step_func/<@http://w3c-test.org/resources/testharness.js:1427:20
> @http://w3c-test.org/dom/events/Event-initEvent.html:91:17
> Test.prototype.step@http://w3c-test.org/resources/testharness.js:1403:20
> async_test@http://w3c-test.org/resources/testharness.js:518:13
> @http://w3c-test.org/dom/events/Event-initEvent.html:81:1

- dom/events/Event-propagation.html

> Fail	After stopPropagation()	assert_equals: Propagation flag expected false but got true
> 
> testPropagationFlag/<@http://w3c-test.org/dom/events/Event-propagation.html:19:5
> Test.prototype.step@http://w3c-test.org/resources/testharness.js:1403:20
> test@http://w3c-test.org/resources/testharness.js:501:9
> testPropagationFlag@http://w3c-test.org/dom/events/Event-propagation.html:11:3
> @http://w3c-test.org/dom/events/Event-propagation.html:28:1

and

> Fail	After stopImmediatePropagation()	assert_equals: Propagation flag expected false but got true
> 
> testPropagationFlag/<@http://w3c-test.org/dom/events/Event-propagation.html:19:5
> Test.prototype.step@http://w3c-test.org/resources/testharness.js:1403:20
> test@http://w3c-test.org/resources/testharness.js:501:9
> testPropagationFlag@http://w3c-test.org/dom/events/Event-propagation.html:11:3
> @http://w3c-test.org/dom/events/Event-propagation.html:35:1

**Comment by cdumez** [comment]
Updating web platform tests via https://github.com/w3c/web-platform-tests/pull/3469
