### ISSUE TITLE
Event.returnValue legacy property

### ISSUE THREAD

**Issue by cvrebert** [whatwg/dom#222]
[`Event.returnValue`](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue) seems to work in all modern browsers (Chrome, Safari, Edge, IE11) except Firefox, but it's not spec'd anywhere.
Testcase: http://jsbin.com/xisujo/edit?html,js,output

Consider specing it?

**Comment by domenic** [comment]
Dupe of https://www.w3.org/Bugs/Public/show_bug.cgi?id=25002, which has seen some recent activity. (Yes, having two bug trackers sucks.)

**Comment by cvrebert** [comment]
Dangit.
