### ISSUE TITLE
"convert nodes into a node" needs to specify which document is used as the owner document for the nodes it creates

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/dom#224]
https://dom.spec.whatwg.org/#converting-nodes-into-a-node says things like:

> Replace each string in nodes with a Text node whose data is the string.

What should the owner document of that Text node (and hence its associated global) be?  Should it be the current Realm global's document, the owner document of the context object, or something else?

Gecko's implementation is going to use the owner document of the context object here.

**Comment by ArkadiuszMichalski** [comment]
This is very simillar to: https://github.com/whatwg/dom/issues/212, I forgot to mention these methods.

**Comment by annevk** [comment]
Thanks @bzbarsky!

**Comment by annevk** [comment]
And thanks @ArkadiuszMichalski, per usual, your attention to detail is much appreciated. Let me know when you want to start editing some text. 😊
