### ISSUE TITLE
"event . cancelable Returns true or false depend..."

### ISSUE THREAD

**Issue by senolv** [whatwg/dom#226]
https://dom.spec.whatwg.org/#interface-event

> event \. cancelable
> Returns true or false depending on how event was initialized\. Its return value does not always carry meaning, but true can indicate that part of the operation during which event was dispatched, can be canceled by invoking the preventDefault\(\) method\.

In which situation do they not carry any meaning?

**Comment by annevk** [comment]
Sometimes the event is reported as cancelable, but cancelling it has no effect. I don't know of any examples offhand though.

**Comment by ArkadiuszMichalski** [comment]
Per [UI Evensts](https://w3c.github.io/uievents/#event-types-list): `keyup`, `mousemove`, `mouseout`, `mouseover`.
