### ISSUE TITLE
"In a document" confusion

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#238]
So I guess this has been discussed to death elsewhere, but naively putting on my web developer hat, something that's in a shadow tree is still "in a document". Maybe in English: the element is in the shadow tree, the shadow tree is in the document, therefore the element is in the document.

Have we considered "in a document's light DOM" or similar?

It seems like regardless of what we do we're going to have to audit every use of "in a document" and figure out whether it should become "in a document's light DOM" or "in a shadow-including document".

**Comment by annevk** [comment]
I don't think we really discussed this much actually. @dglazkov, @smaug----, @hayatoito, @rniwa? Now would be a good time to decide on this, since I'm working on several patches to HTML that would be affected by this.

"In a light document" (to disambiguate) and "connected" (after the developer-facing API)?

**Comment by smaug----** [comment]
"light document" sounds a bit odd, given all the different meanings of "light". One could think data documents being "light", since they are less heavy than documents bound to a browsing context.
And there is no shadow document. 

To me in a document clearly means light dom only, since there is parentNode chain from node to document in that case. That is what tree structures usually mean in computer science.
But I guess I could live with "in a document's light DOM".

**Comment by rniwa** [comment]
I'd say "directly in a document" or "in a document without crossing shadow boundary" or "in a document tree".

**Comment by annevk** [comment]
The DOM Standard does already introduce "light tree" as an opposite to "shadow tree", but given this feedback I'm inclined to just stick with "in a document" and "in a shadow-including document" meaning what they mean today.

**Comment by domenic** [comment]
> To me in a document clearly means light dom only, since there is parentNode chain from node to document in that case. That is what tree structures usually mean in computer science.

Is that CS tree concept usually denoted using the word "in", or is there perhaps a more precise phrase?

I do think "in a document tree" (and "in a shadow-including document tree" or similar) helps a bit over the simple "in a document". It makes me aware that there's a concept known as "document tree" and that I should be thinking in terms of tree structures.

I like "in a light document"/"in a document's light DOM" and "connected" the most but I guess others don't.

**Comment by smaug----** [comment]
"in a light document" doesn't quite make sense, but the the others are fine.

(Though, very subjective view, I prefer Gecko's naming: In composed document, in uncomposed document, but I think others have said they don't like those.)

**Comment by hayatoito** [comment]
> I'm inclined to just stick with "in a document" and "in a shadow-including document" meaning what they mean today.

+1

We should not use "light". "light" does not have a absolute meaning. It is just a parent tree of a shadow tree. Whether "light tree" is a document tree or a shadow tree depends on its context.

**Comment by dglazkov** [comment]
I defer to y'all. No strong opinions, except that it should be great and amazing.

**Comment by domenic** [comment]
Since we should probably make a decision on this before spreading the terminology to too many specs. I see two potential issues being discussed here:

- "in a document" confuses some people (see my OP)
- "in a shadow-including document" could simply be "connected" or "connected to a document" for consistency with the callback naming

I'm OK keeping things as-is. But I think changing "in a document" to either "in a document tree" or "directly in a document" would be a nice improvement. And similarly I think using "connected" consistently would be kind of nice.

I don't think anyone feels very strongly here though (besides some people not liking certain proposed alternative terms) so maybe we should just keep things as they are?

**Comment by rniwa** [comment]
Indeed, changing "in a document" to "in a document tree" would be a good improvement.

**Comment by annevk** [comment]
We started using "connected" in HTML for being inserted into a shadow-including document. That matches the callbacks more closely. In a shadow-including document is state, which we don't really expose through callbacks.

"In a document tree" seems fine, though will result in a bit of churn. Probably manageable.

**Comment by hayatoito** [comment]
Yeah, I did not have a strong opinion, but I am feeling that we could get benefits if we could have a shorter, intuitive, terminologies.

Basically, I like using *connected* as a replacement of *shadow-including*. Thus, the proposal from me:

To represet a status:
- *is connected to a document*   (As a replacement of *in a shadow-including document*)
- A and B *are connected to the same document*  (As a replacement of "in the same shadow-including document" in https://github.com/whatwg/dom/pull/273)

To represent a change of state:
- *get connected to a document* (As a replacement of  *is connected*)
- *get disconnected from a document* (As a replacement of *is disconnected*)

I also like using 'in a document tree' to avoid confusion of 'in a document'.
- *in a document tree* (as a replacement of a *in a document*)
- *in a shadow tree*

**Comment by annevk** [comment]
@domenic @rniwa, thoughts? I would be okay with "is connected", "got connected", and "got disconnected" (I don't think we need to add "document" as the APIs don't have it either).

**Comment by domenic** [comment]
"becomes" instead of "got" IMO, but that sounds nice otherwise.

Do you have a proposal for a replacement for "in the same shadow-including document," which pointer lock wants? (IMO in that case it's fine to just talk about having the same shadow-including root.)

Are you on board with "in a document tree" as well? As was pointed out previously, this gives us a nice division: "in a document" means "not yet updated for shadow DOM" whereas "in a document tree" or "connected" imply we've spent the time and figured out what should happen.

**Comment by annevk** [comment]
I'm okay with renaming "in a document", yes. "Becomes" also seems okay.

And yeah, for "same" we should figure out if that can't just talk about the shadow-including root instead. Seems like a better abstraction.

**Comment by rniwa** [comment]
Yeah, I was gonna suggest "becomes connected" and "becomes disconnected" as well.

**Comment by hayatoito** [comment]
Thanks. Then, the conclusion is:

We will use:
- "is connected"
- "becomes connected"
- "becomes disconnected"
- "in a document tree"

Maybe we might want to have the following too:
- "A and B are connected to the same document"

**Comment by annevk** [comment]
How often do we need "A and B are connected to the same document"? That's basically "A and B are connected and their node document is identical".

**Comment by hayatoito** [comment]
I can not tell how often we need it.

Until we start to feel we need it, let's use "A and B are connected and their node document (shadow-including root?) is identical".

**Comment by annevk** [comment]
I guess both node document and shadow-including root work there due to the way connected is defined.

**Comment by hayatoito** [comment]
Ah, I did not realize that [node document](https://dom.spec.whatwg.org/#concept-node-document) is clearly defined. Thanks!

**Comment by annevk** [comment]
I created #275 and https://github.com/whatwg/html/pull/1483 to fix this, however I'm not sure I'm entirely happy with the result. There's a couple cases in HTML where "in a document" is used and then there's also reference made to that document's browsing context. It's not clear if that works well with "in a document tree".

And "is connected" often gets awkward since a lot of checks are for the opposite scenario. So just using "connected" is a term there might be better.

"Becomes connected" and "becomes disconnected" seem to work fine, although how build on top of insertion and removal is a little wonky, but we're not changing that here.

**Comment by domenic** [comment]
I think "connected" instead of "is connected" makes sense.

I think we should leave "in a document", giving it a definition like:

**In a document** means one of either connected or in a document tree. It is a legacy term indicating that the author of the spec that uses it has not yet thought through the interaction of their spec with shadow DOM and made a decision between those two.

**Comment by smaug----** [comment]
The meaning of in a document should not change. If a spec hasn't been updated to deal with shadow DOM, features relying on in-a-document should not work. Otherwise the behavior can be somewhat random or reveal parts of the shadow dom accidentally to light DOM etc.

**Comment by domenic** [comment]
Hmm, OK. Maybe then

**In a document** means in a document tree. It is a legacy term indicating that the author of the spec that uses it has not yet thought through the interaction of their spec with shadow DOM and made a decision between the two. All uses of it should over time be replaced by in a document tree, or possibly by connected, if thinking through the interactions reveals that to be more appropriate.

Or maybe this idea of using "in a document" to track not-yet-updatedness is not good?

**Comment by annevk** [comment]
It sounds fine to have something like that. It's a signal folks can use, but it's not one you can rely on. (Even without "in a document" usage some specification might not have considered shadow trees.)

**Comment by annevk** [comment]
I updated both PRs.
