### ISSUE TITLE
Event.prototype.deepPath as an attribute breaks TinyMCE 4.3.10

### ISSUE THREAD

**Issue by rniwa** [whatwg/dom#242]
This is probably an evangelism but wordpress.com breaks due to its use of deepPath as an attribute.  Specifically, they have a code that retrieves `event.deepPath[0]`.

**Comment by rniwa** [comment]
@hayatoito @annevk @Ms2ger @zcorpan @bzbarsky

**Comment by annevk** [comment]
What would a good alternative name be? `connectedPath()`, `composedPath()`, `unclosedPath()`, `openPath()`?

**Comment by rniwa** [comment]
I like `composedPath()`.  I'm really hoping that wordpress.com fixes this especially since [WordPress itself doesn't seem to have it](https://github.com/WordPress/WordPress/search?utf8=✓&q=deepPath).

**Comment by domenic** [comment]
Are there other parts of the API that should make the deep -> composed substitution for consistency?

**Comment by annevk** [comment]
As far as I know this is the only API that uses "deep" thus far. There's several open issues about adding more, but nothing remotely conclusive.

The other APIs that can go "downward" are `slotable.assignedSlot` and `shadowHost.shadowRoot`. And of course, all three are restricted to returning nodes in open shadow trees.

**Comment by rniwa** [comment]
Perhaps `flattenedPath` would be more consistent with `assignedNodes({flatten: true})`?

**Comment by annevk** [comment]
That does not seem entirely unreasonable (though I'd spell it `flatPath()`). One difference is that in the non-fallback case, children of slots are not part of the flat tree, but they can be part of the event path. I'm not sure if those subtle difference end up mattering more over time or not. If they do at some point, I think it would be better they had distinct terms.

**Comment by rniwa** [comment]
How about `bubblingPath`? `propagationPath` appears to be no so popular but has a [usage that  definitely breaks](https://github.com/impressiver/evr.js/blob/a1e135f0b8607421ff8a3d2b82e7b2af6d22238b/js/jquery.evr.js#L52).

**Comment by annevk** [comment]
I think those are more confusing than `composed` or `flat`. I figured we could maybe use `eventPath` getting back to the original `path` property that I suppose we can also no longer use, but that also seems like an extremely popular term.

**Comment by annevk** [comment]
https://github.com/whatwg/html/issues/1160 suggests either `piercingPath` or `composedPath`. We want to couple it with renaming `scoped`.

**Comment by rniwa** [comment]
Apparently, this problem was caused by TinyMCE 4.3.10, which is included in WordPress 4.5 on the contrary to my earlier statement.  So we probably need to do this rename since there will be a lot of websites that have this version of WordPress and/or TinyMCE and never update to a new version :(

**Comment by annevk** [comment]
So @smaug---- does not like `piercing` because going from shadow to light is not really piercing anything (you're supposed to have that access) and @rniwa does not like `composed` because nothing is really composed. Giant sigh.

Different direction: `broad`. We cannot really use `complete` or `full` since it isn't always, but it's broader than usual and a `broad` event logically reaches more `EventTarget` objects. `findRootNode({ broad:true })` also works in that sense.

**Comment by rniwa** [comment]
how about `shadowPath` or `shadowCrossingPath`?  Or `dispatchPath`?

**Comment by annevk** [comment]
@rniwa I think ideally we have something that can also be used for `findRootNode()` and as replacement for `Event.prototype.scoped` (with opposite meaning).

**Comment by rniwa** [comment]
How about `escaping` then?  `findRootNode({escaping: true})`, `Event.prototype.escaping`, and `escapingPath`.

**Comment by annevk** [comment]
I suspect @smaug---- would not like those for the same reason he did not like piercing. Is `broad` that bad?

**Comment by rniwa** [comment]
I don't like it because `board` doesn't convey the semantics of exiting from a shadow root to a shadow host.  @othermaciej @hober

**Comment by rniwa** [comment]
I talked with @smaug---- on #whatwg and he seems to like `dispatchPath`, and I like that name too.

WDYT?

**Comment by smaug----** [comment]
"like". I can live with dispatchPath is perhaps closer ;)
propagationPath would be way nicer, but can't be used.

**Comment by smaug----** [comment]
composedPath and findRootNode({composedTree: true}) ?

**Comment by rniwa** [comment]
I don't think `composedPath` makes sense because it contains nodes that are not in the composed tree.  Also, we don't use the term `composed` anywhere else so that might be rather confusing.

**Comment by smaug----** [comment]
hmm, sounds like we have different meaning for composed tree. You think it as a synonym to flattened tree, I think. For me composed tree is the tree of node trees, including shadow roots and everything.

And if we don't use composed for anything else, it is a good thing. less likely to cause confusion.

**Comment by rniwa** [comment]
That's a good point.  Okay, with that, we can do `Event.prototype.composed` and `findRootNode({composed:true})`

**Comment by annevk** [comment]
And `composedPath`? \o/ Now we just need to wait for @hayatoito to weigh in.

**Comment by hayatoito** [comment]
*composed* is no longer a *reserved word* in the Shadow DOM spec. I stopped using this term in normative sections about a month ago. Now, we can use it freely in any meaning, if we want to re-use it.

I am fine with `composedPath`. I can not think of any better name.

**Comment by rniwa** [comment]
Let's go with `composedPath` then!
