### ISSUE TITLE
Better way to maintain this reference on event listener functions

### ISSUE THREAD

**Issue by mkay581** [whatwg/dom#245]
Sorry if I've missed any previous requests for this feature, but is there any goal to allow callbacks passed to event listeners to keep their `this` context without having to store a reference to the this-binded event listener first?

I frequently find myself doing this in my class methods:

```javascript
this.el = document.createElement('div');
this.listener = this.onClick.bind(this); // store a reference just to bind the `this`
this.el.addEventListener('click', this.listener)
```

only to ensure the correct listener mapping gets removed later on in a `destroy`-like function with this code:

```javascript
this.el.removeEventListener('click', this.listener);
```

A few years ago I would've never thought of a good reason to add such sugar, but now that JS is moving forward with class declarations, it seems more warranted now.

**Comment by annevk** [comment]
This is more a topic of discussion for TC39 (and has been discussed on es-discuss I believe) since it affects all callbacks.

For event listeners though if you name your event callback `handleEvent` you can just pass the object with that method to `addEventListener()`.

**Comment by mkay581** [comment]
oh wasnt aware of the `handleEvent` functionality. How does that work with multiple event listeners in a class?

**Comment by annevk** [comment]
I recommend searching through https://esdiscuss.org/ for earlier discussions and maybe re-raise it there. This isn't something we should be solving at the API-layer I think. As you indicate, `handleEvent()` is rather terrible and new callback-based APIs don't use that pattern.

**Comment by mkay581** [comment]
Hey @annevk, I opened [a discussion](https://esdiscuss.org/topic/better-way-to-maintain-this-reference-on-event-listener-functions) on es-discuss about this and seems as though they feel that this is an issue that should be addressed by this team. What are your thoughts?

**Comment by domenic** [comment]
Well, Andrea feels that way, but he is emphatically *not* a representative of TC39. The only TC39 member you got a reply from was me...

**Comment by mkay581** [comment]
lol okay, sorry. :)
