### ISSUE TITLE
I don't think Element.insertAdjacentText can cause CEReactions

### ISSUE THREAD

**Issue by dominiccooney** [whatwg/dom#255]
The steps for [insertAdjacentText](https://dom.spec.whatwg.org/#dom-element-insertadjacenttext) insert a text node into an element. I don't think this can cause CEReactions because it will not cause attributes to change, elements to be created or adopted, or elements to be attached to or removed from the document.

It is functionally equivalent to to over-specify the CEReactions attribute, but since there was a decision not to apply CEReactions universally it probably makes sense to remove it from insertAdjacentText.

**Comment by annevk** [comment]
Thanks!
