### ISSUE TITLE
Repeatedly inserting a custom element may upgrade it twice

### ISSUE THREAD

**Issue by dominiccooney** [whatwg/dom#261]
Say I have two custom elements&mdash;call them A and B&mdash;of the same type, in a document, and then I define this kind of element. This enqueues upgrade reactions for A and B.

If, during A's constructor, it removes and reinserts B, [node insert](https://dom.spec.whatwg.org/#concept-node-insert) step 6.5.2.2 enqueues a second upgrade reaction for B. This is implementable, but it seems error prone for authors if B's constructor runs twice.

One possibility is to have [upgrade an element](https://html.spec.whatwg.org/multipage/scripting.html#concept-upgrade-an-element) bail out if the element's custom element state is already "custom."

The edge cases are tricky so this may need some careful thinking through. For example, I think you need to do this check when running the upgrade step and not when enqueuing it to make the adoption case work.

**Comment by domenic** [comment]
About to head to sleep, but it seems immediately obvious to me that there should be some bail-out based on the custom element state. Maybe I thought it could never be reached...

I'll try to think tomorrow about the edge cases but your intuition seems right on first glance.

Thanks again for the great bugs!
