### ISSUE TITLE
What happens if a 'once' eventListener dispatches a similar event?

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#265]
What happens if a 'once' eventListener dispatches a similar event?

Code example:
```
var listenerCallCount = 0;
function listenerFunction()
{
    ++listenerCallCount;

    if (listenerCallCount == 1)
        document.body.dispatchEvent(new Event('test'));
}

document.body.addEventListener('test', listenerFunction, { 'once': true });
document.body.dispatchEvent(new Event('test'));
```

Relevant spec section:
https://dom.spec.whatwg.org/#concept-event-listener-inner-invoke

Based on the specification, it seems to me that the event handler would get executed twice despite being marked as 'once'? This is because we set the listener's removed flag to true *after* calling its handlerEvent().

Maybe the 'removed' flag should be set before calling handleEvent() in this case? Or is there something else in the spec that I missed and would prevent the listener to be executed twice in this case?

**Comment by cdumez** [comment]
@annevk @RByers I ran into this problem when implementing it in WebKit.

**Comment by dtapuska** [comment]
I agree half of step 8  (setting the remove) should likely be done before the Step 6.

**Comment by RByers** [comment]
@annevk?  FWIW it would be great to have a web-platform-test covering edge cases like this (nobody else has implemented `once` yet AFAIK).

**Comment by annevk** [comment]
We could move all of step 8 to be between 4 and 5 (to keep the passive listener guard as one step before and after actually calling). We still got a handle on the listener so we can invoke it just fine.

Does that sound right?

I'm sad that I had not anticipated this edge case.

**Comment by cdumez** [comment]
@annevk If we move step 8 between 4 and 5 (which sounds OK to me), can we drop the "removed" flag on the listeners as well?

**Comment by annevk** [comment]
No, note that we operate on a copy of the object's listeners there. We have that copy to prevent new listeners from being added, but we use removed to still allow removal of them (either through this once feature or the `removeEventListener()` method).

**Comment by cdumez** [comment]
@annevk I see now that the 'removed' flag is indeed useful when calling removeEventListener(). 
However, I do not understand yet why setting the 'removed' flag to true is still useful for 'once' event listeners if we move step 8 between 4 and 5. It seems to me that if we move step 8 between 4 and 5, we could drop the "then set listener’s removed to true" part of step 8.

**Comment by annevk** [comment]
Yeah, I had to walk outside for a bit to pick up the kid and such and realized the same thing. So yeah, we can drop the removed flag from this step. Thanks.
