### ISSUE TITLE
selectionchange possible improvements

### ISSUE THREAD

**Issue by caub** [whatwg/dom#271]
I've been in a situation where I need to know a 'target' for the selection change, or other times I needed an event type that triggered that change in selection.

Since selection change is always triggered by another event (I think), wouldn't it be better to include more information in this event?

I've done things like http://jsfiddle.net/rk6f74tw/34/ (check console and select content either in the blue menu or elsewhere) as also a polyfill, but it's of course more heavy

`document.activeElement` is body when selecting 'test ok' in the menu (for Chrome and Edge), so it doesn't help to know if we are clicking in the menu or not http://jsfiddle.net/rk6f74tw/36/. Only Firefox prevents the selectionchange events for non-form elements in a user-select:none element.

Edit: So it can more or less work with other polyfills: http://jsfiddle.net/rk6f74tw/39/ but it's a bit heavy

So I also think selectionchange should be fixed (on Chrome and Edge) with the user-select:none css property (will post issues respectively)

**Comment by annevk** [comment]
Hey @caub, thanks for the report. I'm going to ask you to file it against https://w3c.github.io/selection-api/ instead since this is out-of-scope for the DOM Standard. Hope you understand.

**Comment by caub** [comment]
Yes, thanks and sorry, I knew this other repo but forgot
