### ISSUE TITLE
Add relatedTarget to event dispatch

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#277]
There's some `relatedTarget` logic in https://w3c.github.io/webcomponents/spec/shadow/ that needs to become part of the core event dispatch algorithm. Basically for all events that have a relatedTarget "internal slot".

@hayatoito is this something you might be interested in working on?

**Comment by annevk** [comment]
Figuring out #276 is probably part of this.

**Comment by hayatoito** [comment]
Yeah, let me work on this.
