### ISSUE TITLE
Consider DOMTokenList#replace

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#28]
@wycats suggests people get freaked out by the reordering of tokens so they cannot use it in Ember.

**Comment by domenic** [comment]
Would be good to get a better description of the actual use case ... i.e. is the freak-out rational in any way? What does the ordering affect?

**Comment by annevk** [comment]
Sorry, `[class=...]` is affected primarily. Presumably non-refactored code (potentially from other libraries) might also have `className` checks and such.

**Comment by annevk** [comment]
Also debugging of templates and such. E.g. template has `class="{{level}} fancy"`. If the serialization has a different order that might be confusing.

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1224186 against Gecko.
