### ISSUE TITLE
Remove SVGZoomEvent?

### ISSUE THREAD

**Issue by Ms2ger** [whatwg/dom#283]
Per w3c/svgwg@3844475

**Comment by annevk** [comment]
Are Safari, Firefox, and Edge removing it too?

**Comment by Ms2ger** [comment]
Dunno. @erikdahlstrom?

**Comment by erikdahlstrom** [comment]
I'm not involved with either of these products, so can't speak for their respective intents.

The wg discussion describe the issues around SVGZoomEvent fairly well. All ways of zooming in current browsers lead to no dispatching of this event AFAIK, possibly with exception of javascript setting SVGSVGElement.currentScale.

**Comment by ayg** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1314388
