### ISSUE TITLE
"unclosed node of node" reads confusingly

### ISSUE THREAD

**Issue by tabatkins** [whatwg/dom#285]
Usually in a construction like "ADJ node of node", we expect the adjective to be a relational one, relating the first node to the second in some way, like "ancestor" or "sibling". But "unclosed" is a *personal* adjective describing the state of the first node, with no relational semantics at all, so when this phrase is is used it looks like a typo.  You can't rearrange it into similar phrases, either: "A is an ancestor node of node B" can reverse to "B's ancestor nodes", but "B's unclosed nodes" doesn't read well to me.

I've got a few suggestions for alternative wording, but I'm not married to any of them:

* A is an unclosed relative of B
* A is potentially reachable from B

The first one is a minimal change, just adding a relationship word to make it read better.  I like the second one a lot better, tho - it expresses the intent of the relationship a lot better.

**Comment by hayatoito** [comment]
I do not have a strong opinion, however, +1 for "A is potentially reachable from B".

 I remember that I thought the similar wording.
One concern is:

e.g.
```
let a = document.createElement("div");
let b = document.createElement("div");
```

In this case, `a` is *unclosed node* of `b`, and vice-versa. Thus, *reachable* might not reflect the situation correctly... :( 

Maybe it's okay. *Reachable* might be better than mysterious *unclosed*, I think.

**Comment by tabatkins** [comment]
I'm really trying to reach for a positive attribute here, because - in addition to the already confusing wording - saying "not unclosed" is confusing by itself. Double-negation is an anti-pattern both in APIs and in English (and here we have an API written *in* English!).  "Reachable" passes this test, as you have "reachable" and "not reachable".

However, your example is compelling.  What we're really trying to talk about is whether or not A is hidden from B by a closed shadow boundary.  Maybe "shadow-hidden"?  That's still a positive attribute, and it explicitly invokes the shadow boundary - it's clearer that your two script-created elements are "not shadow-hidden", because there's no shadows between them!

**Comment by annevk** [comment]
I like shadow-hidden.

**Comment by hayatoito** [comment]
I prefer "closed-shadow-hidden" to "shadow-hidden" because open shadow root is not *hidden*.

**Comment by annevk** [comment]
So _A_ is a closed-shadow-hidden node of _B_, if ...? That seems okay too.

**Comment by hayatoito** [comment]
Hmm. It looks long. (bikeshading...)
How about using "*A* is *open* to *B*"? Is this too short?

**Comment by annevk** [comment]
I think long is fine here, since it's not an API. If we added an API for it, we should have something reasonably short, but being descriptive here is okay. (I realize I used to prefer short for descriptions too, but I changed my mind on that, mostly.)

**Comment by annevk** [comment]
@hayatoito shall I take this or do you want to make this change?

**Comment by hayatoito** [comment]
@annevk Let me send a PR. Since the meaning of *closed-shadow-hidden* is negation of *unclosed node of node*, we have to update the consumers of it too.

I think we are going to use the followings:

- *A* is *closed-shadow-hidden* node of *B*.
- *A* is not *closed-shadow-hidden* node of *B*.

Do these sound good?

**Comment by annevk** [comment]
With s/is/is a/ for the first and s/is not/is not a/ for the second, yes.
