### ISSUE TITLE
new Element(tagName)?

### ISSUE THREAD

**Issue by caub** [whatwg/dom#287]
I've seen the syntax evolves from `document.createSomething()` to `new Something()`

for Range, Text, DocumentFragment, but for Element? is or will there be a way?

**Comment by domenic** [comment]
The problem is that then `new Element("p")` would not return an `Element`. So this is unlikely to ever work. We may in the future allow `new HTMLParagraphElement()`, but probably not ever `new Element("tagname")`.

**Comment by caub** [comment]
Ok, good to know, thanks
