### ISSUE TITLE
The adopted callback should be passed the old and new document

### ISSUE THREAD

**Issue by dominiccooney** [whatwg/dom#292]
https://dom.spec.whatwg.org/#example-5ffcda00

> For each inclusiveDescendant in node’s shadow\-including inclusive descendants that is a custom element, enqueue a custom element callback reaction with inclusiveDescendant, callback name "adoptedCallback", and an empty argument list\.

This doesn't help you track which document(s) you've been in; consider the case where an adopted callback causes more follow-on adoption. The same could be said of the connected and disconnected callbacks.

Maybe it is OK to consult the document or parentNode properties, but then the same could be said of the attributeChangedCallback, which is provided the old and new attribute values.

**Comment by annevk** [comment]
connected/disconnected does not change the node document. Why would they need arguments?

Agreed we should pass them for adopted though.

**Comment by dominiccooney** [comment]
Good point--connected/disconnected are fine as is.
