### ISSUE TITLE
cloneNode underspecified for attribute copying

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#30]
The spec says:

> Copy the following from node to copy, depending on the type of node: 
> ...
> (If Element) Its namespace, namespace prefix, local name, and its attribute list.

Copying the attribute list is underspecified. It seems like it could mean any of the following:

1. Set _copy_@[[attributeList]] to _node_@[[attributeList]], i.e., maintain a pointer, so that manipulating either element will affect the other.
2. Loop through _node_@[[attributeList]] and append each attribute to _copy_@[[attributeList]]. In this case, adding or removing attributes from _copy_ will not affect _node_, but updating existing ones will.
3. Loop through _node_@[[attributeList]] and create new `Attr` objects to append to _copy_@[[attributeList]].

**Comment by annevk** [comment]
Actually, 2 would move them so would be kind of disastrous. What is needed is 3. This whole algorithm needs cleaning up to account for custom elements at some point.

**Comment by domenic** [comment]
I'm not sure it would---_node_@[[attributeList]] would still contain pointers to the `Attr`s, although they would have their `ownerElement` changed. But yeah I assumed 3 was the intent. Implemented as https://github.com/tmpvar/jsdom/commit/31f48412eb0d430c078f85b2fb0a04fcdf64528b#diff-862b36375afbeb26674b60568127dd8cR349, maybe I can PR the spec later.
