### ISSUE TITLE
CDATASection misses

### ISSUE THREAD

**Issue by foolip** [whatwg/dom#300]
We missed a few things in https://github.com/whatwg/dom/pull/295, at least:

1. `appendChild(cdata)` should not throw, but does in https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity
1. `nodeName` should be `#cdata-section`
1. `normalize()` shouldn't actually touch CDATASection nodes, per my ad-hoc testing in Chrome and Firefox

There are also some places in the spec that say "switching on" that aren't wrong as such, but it could be made clearer so that nobody thinks it's possible to actually implement using a `switch(node.nodeType)`.

**Comment by foolip** [comment]
I found these by searching for "switch" and "{{Text}}" in the spec and scratching my head.

**Comment by annevk** [comment]
We really need IDL to define platform object branding to make some of this clearer.

**Comment by foolip** [comment]
But it seems `wholeText` does merge adjacent `CDATASection` nodes in at least Blink, Edge and Gecko, so it's not actually implemented using a [contiguous Text nodes](https://dom.spec.whatwg.org/#contiguous-text-nodes) concept shared with `normalize()`.

**Comment by foolip** [comment]
I have a PR for some of this, one minute.

**Comment by foolip** [comment]
I looked for cases where Blink looks at the (internal) `nodeType` and not taking the same code path for `TEXT_NODE` and `CDATA_SECTION_NODE` and found two more things:

1. Range::surroundContents would throw if a CDATASection node is partially contained. That's unlikely to be intentional.
1. Two "FIXME: What about kCdataSectionNode?" in the editing code that check `nodeType` seemingly specifically to exclude CDATASection.

**Comment by annevk** [comment]
Should we just fix `normalize()` in implementations?

**Comment by foolip** [comment]
That's definitely worth consider, but I suspect the current behavior on `normalize()` may be intentional, if you take it as an invariant that calling `normalize()` shouldn't change what is serialized.

So assuming that it's already perfectly interoperable I think just spec'ing that would be best.

**Comment by annevk** [comment]
Yeah, we should probably just define what is implemented at this point.

**Comment by annevk** [comment]
I think this is good enough now until we get proper branding.

**Comment by foolip** [comment]
Yep, thanks for making the spec just as crazy as implementations :)
