### ISSUE TITLE
Callback functions/interfaces need to be invoked with WebIDL concepts

### ISSUE THREAD

**Issue by foolip** [whatwg/dom#303]
This is needed to explain how you end up at https://html.spec.whatwg.org/multipage/webappapis.html#clean-up-after-running-script during event dispatch, which @jakearchibald mentioned in https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

@domenic added IDs in https://github.com/heycam/webidl/pull/146

**Comment by annevk** [comment]
Once that lands that seems like a good thing to do, yes.

**Comment by foolip** [comment]
Landed:
https://heycam.github.io/webidl/#call-a-user-objects-operation
https://heycam.github.io/webidl/#invoke-a-callback-function

These too, but I don't know when they'd come into play:
https://heycam.github.io/webidl/#get-a-user-objects-attribute-value
https://heycam.github.io/webidl/#set-a-user-objects-attribute-value
