### ISSUE TITLE
DOMTokenList.value could be a stringifier attribute

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#314]
Looking at the latest DOM specification [1], it seems that the DOMTokenList stringifier basically does the same thing as the 'value' attribute getter. Therefore, shouldn't we be able to make 'value' a stringifier attribute?

i.e.
[CEReactions] stringifier attribute DOMString value;

[1] https://dom.spec.whatwg.org/#domtokenlist

**Comment by cdumez** [comment]
@annevk @heycam

**Comment by annevk** [comment]
Yeah, that seems correct.

**Comment by cdumez** [comment]
Thanks.
