### ISSUE TITLE
Validating a qualified name does not match browsers in a corner case

### ISSUE THREAD

**Issue by ayg** [whatwg/dom#319]
``` html
<!DOCTYPE html>
<script>
try { document.createElementNS("a", "a:0") }
catch(e) { document.documentElement.textContent = e.name }
</script>
```

Outputs InvalidCharacterError in Chrome, Firefox, and Edge.  Per [spec](https://dom.spec.whatwg.org/#validate), it should throw NamespaceError, because "a:0" matches the Name production.  I think browsers should probably change here instead of the spec, because browsers' behavior doesn't make sense to me, but I'm filing a spec bug anyway because we seem to have interop against the spec.

**Comment by ayg** [comment]
(Also if the character after the colon is a combining character, Chrome and Firefox throw InvalidCharacterError for the same reason.  Edge doesn't throw in this case, but that's because it doesn't throw in general for anything starting with a combining character, which is just a bug on their part.)

**Comment by annevk** [comment]
Happy to change the spec if browsers already align. Prolly simplifies a bit too.

**Comment by annevk** [comment]
We could remove the Name check, right?

**Comment by ayg** [comment]
Then how would we know whether to throw InvalidCharacterError or NamespaceError?

**Comment by annevk** [comment]
Oh, I thought you suggested that distinction is not made here.

**Comment by ayg** [comment]
No, it's just in this one specific case that UAs throw a different exception.  If we want to change the spec to match them, we'd have to research exactly what the behavior is here, e.g., "a:0:a" and "a:a:0" and things like that.

**Comment by ayg** [comment]
Correction: the following test with combining char

```html
<!DOCTYPE html>
<script>
try { document.createElementNS("a", "a:ெ") }
catch(e) { document.documentElement.textContent = e.name }
</script>
```

gives InvalidCharacterError per Chrome, NamespaceError per Firefox and spec, and no exception in Edge.  So if we change the spec, it may have to be only for ASCII characters, which seems even less reasonable.

**Comment by annevk** [comment]
Do we have tests for this already?

**Comment by ayg** [comment]
I have tests in dom/nodes/Document-createElementNS.js that I checked in to Gecko but got backed out for a syntax error elsewhere in the push.  I'll reland them shortly.

**Comment by ayg** [comment]
Tests are now in Gecko and should wind up upstream soon: https://hg.mozilla.org/mozilla-central/rev/31177ceb556c

**Comment by ayg** [comment]
@bzbarsky What do you think?  Browsers are somewhat interoperable, but it seems like it's just a bug and the spec is right.

**Comment by bzbarsky** [comment]
So... at least in terms of what Gecko is actually doing, it's validating the qualifiedname in "namespace aware" mode.  In that mode, we treat the char right after the ':' (if there is a ':') as a "name start" character, and '0' is not valid "name start" character.  In particular, we effectively treat the parts before and after the ':' symmetrically, in terms of treating a digit starting either one as an "invalid character" error.  This allows validation of the name in a single scan of it, just resetting some state if a ':' is found.

OK, so back to the spec...  The spec requires scanning the name twice, right?  This is somewhat easier to spec, but less efficient, of course.

We could try to rewrite our validation algorithm to produce the output the spec expects while staying to a single pass, but that code is a bit fiddly, so this would have nontrivial regression risk in practice.

As far as whether the spec is "right"... it's not obvious to me why you consider it "right".  It could be rewritten in terms of a slightly more complicated (in spec terms) but simpler to implement as a single pass validation algorithm, and such an algorithm may naturally treat a localName following a ':' but not matching the NCName production because it doesn't start with NameStartChar as being an invalid char err, not a namespace err, because it's not at all a namespace error, afaict.

**Comment by annevk** [comment]
I think ideally we just throw `InvalidCharacterError` here and forget about the distinction. We don't have DOM without namespaces after all.

**Comment by ayg** [comment]
> We could try to rewrite our validation algorithm to produce the output the spec expects while staying to a single pass, but that code is a bit fiddly, so this would have nontrivial regression risk in practice.

I think we have pretty good tests for this.

> As far as whether the spec is "right"... it's not obvious to me why you consider it "right". It could be rewritten in terms of a slightly more complicated (in spec terms) but simpler to implement as a single pass validation algorithm, and such an algorithm may naturally treat a localName following a ':' but not matching the NCName production because it doesn't start with NameStartChar as being an invalid char err, not a namespace err, because it's not at all a namespace error, afaict.

It's a namespace error insofar as it is valid in XML without namespaces but invalid in XML with namespaces, so the error is only in namespace-land.  I don't know what other meaning you would give to InvalidCharacterError vs. NamespaceError here.

>I think ideally we just throw InvalidCharacterError here and forget about the distinction. We don't have DOM without namespaces after all.

That's very logical, but completely doesn't match browsers.  Am I too optimistic in hoping that maybe changing the exception type is not going to cause compat issues?  If it won't, maybe we can just get everyone to change their exception types.  (Did we succeed in getting rid of DOMError?)

**Comment by annevk** [comment]
We have successfully changed exception types a number of times. It's a risk and some churn each time of course. I believe we did rid ourselves of the `DOMError` interface successfully.

**Comment by bzbarsky** [comment]
> I don't know what other meaning you would give to InvalidCharacterError vs. NamespaceError here

I think in practice the distinction is completely irrelevant here.

**Comment by ayg** [comment]
I completely agree, so should we just go with InvalidCharacterError consistently?

**Comment by annevk** [comment]
Just to be clear, that is my preference.

**Comment by annevk** [comment]
@domenic are you still planning on trying to make name validation match the HTML parser? If so, we should maybe hold off on trying to clean this up until that either succeeds or another year has passed.

**Comment by domenic** [comment]
@dominiccooney and I are planning on doing so, but I still think converging on InvalidCharacterError and fixing the tests would be a good intermediate step. Otherwise Blink at least is likely to end up first changing to NamespaceError then later changing to no error. Just this morning @tkent-google filed https://bugs.chromium.org/p/chromium/issues/detail?id=702077 .

**Comment by annevk** [comment]
Posted a web-platform-tests PR and a standard PR.

**Comment by tkent-google** [comment]
Chrome's implementation validates input string in a single scan, and it seems an error of the first character validation for LocalPart is handled as InvalidCharacterError incorrectly.  It's easy to fix.

I'm fine with either of simplifying the specification or keeping the current one.

**Comment by annevk** [comment]
@cdumez opinions?

**Comment by ayg** [comment]
@annevk I think people seem to be okay with InvalidCharacterError here.  Do you think it's time to change the spec?

**Comment by annevk** [comment]
I wish we had heard from @cdumez. Did you review the patches to the specification and tests @ayg? If @tkent-google is still on board I guess I'm okay with simplifying this given that @ayg changes Firefox.

**Comment by cdumez** [comment]
Sorry, missed this. Same opinion as @tkent-google here.

**Comment by ayg** [comment]
LGTM.  I'm happy to write the patch for Firefox to use only InvalidCharacterError if that's what we want.

**Comment by annevk** [comment]
Alright, let's run with it.

**Comment by ayg** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1358104

Someone want to make sure there are bugs filed on other UAs?

**Comment by annevk** [comment]
Thanks for the reminder.

https://bugs.webkit.org/show_bug.cgi?id=171052
https://bugs.chromium.org/p/chromium/issues/detail?id=713681
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11730496/

**Comment by cdumez** [comment]
FYI, making this change seems to cause 2 acid3 test failures :/

**Comment by annevk** [comment]
Sigh. Maybe we should just give up on Acid3?

**Comment by ayg** [comment]
Can't we update Acid3?

**Comment by bzbarsky** [comment]
@ayg "we" == "hixie".  If you want to try to convince him, go ahead.  So far we haven't managed for the CSS spec change that likewise caused an Acid3 test failure.

**Comment by ayg** [comment]
Because he isn't around, or because he personally disagrees with the change, or what?  If the test isn't actively maintained or otherwise doesn't match what the specs say, is there any reason to not start ignoring it?  I'd think people aren't judging browsers based on Acid3 conformance anymore.

**Comment by bzbarsky** [comment]
> Because he isn't around, or because he personally disagrees with the change,

Some of both, as far as I can tell.

> I'd think people aren't judging browsers based on Acid3 conformance anymore

"people" is a broad generalization.  We certainly got bug reports on the CSS thing...

**Comment by bzbarsky** [comment]
Or put another way, a coordinated statement from all browsers that we plan to ignore Acid3, and why, would be a good idea if we plan to do that.
