### ISSUE TITLE
Rewrite replaceWith/before/after algorithms

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#32]
Take suggestions from https://lists.w3.org/Archives/Public/public-webapps/2015JanMar/thread.html#msg263 into account.

**Comment by annevk** [comment]
See also: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27887

**Comment by foolip** [comment]
These are being implemented in Blink, are there any big changes expected?

**Comment by annevk** [comment]
I guess the main change would be the one from https://lists.w3.org/Archives/Public/public-webapps/2015JanMar/0321.html for most of these methods.

**Comment by annevk** [comment]
Note that the reason these methods have not shipped yet in Gecko is because we think we need to exclude them from `with` statements and event handlers using `Symbol.unscopeables`.

**Comment by annevk** [comment]
I think for `replaceWith()` the new set of steps would be:

1. Let parent be context object's parent.
1. If parent is null, terminate these steps.
1. Let viableNextSibling be the first following sibling not in nodes, and null otherwise.
1. Let node be the result of converting nodes into a node.
1. Pre-insert node into parent before viableNextSibling.

And something similar for `before()`/`after()`. Can someone sanity check that?

**Comment by Joris-van-der-Wel** [comment]
I've gone over it a few times and the algorithm looks good. However should step 2 not throw an exception?, this would be consistent with `outerHTML` and others.

**Comment by annevk** [comment]
I think @arv and I decided we would not throw more than necessary for these algorithms. Note that improper usage can already result in a somewhat awkward state, with various nodes being removed from the document before you get an exception. (Due to appending them to the `DocumentFragment`.)

**Comment by Joris-van-der-Wel** [comment]
I would prefer an exception in step 2 because it aids in debugging. An awkward state before I get an exception is okay because I can still figure out where I messed up. Silently doing nothing if the parent is missing would be frustrating to debug.

**Comment by foolip** [comment]
All the other new APIs in this group silently do nothing if there's no parent element, though.

**Comment by Joris-van-der-Wel** [comment]
In that case I would say do what is more consistent.

I also just noticed that `outerHTML` throwing for a missing parent node is inconsistent between browsers, so that is not a good example after all.

**Comment by annevk** [comment]
I like @inexorabletash's `this.parent === parent` check to preserve the replace mutation records where possible and will copy that into the specification.
