### ISSUE TITLE
Clarify that DOMTokenList's .replace() must preserve the original order

### ISSUE THREAD

**Issue by ayg** [whatwg/dom#324]
Per #28, it seems the whole purpose of .replace() is to put the new token in the same place as the old one.  The implementation in Gecko doesn't actually do that.  The current spec says just "Replace token in tokens with newToken", which is not absolutely explicit that order should be preserved.  I think this could use clarification, since the term "replace" is not formally defined anywhere.

**Comment by ArkadiuszMichalski** [comment]
But it's not clear now? The same story was for `setAttributeNode` https://github.com/whatwg/dom/issues/116 and any additional prose was not added. Replace is replace, maybe adding would be more unclear, but replace?
@ayg Btw, after fixing https://bugzilla.mozilla.org/show_bug.cgi?id=1293563 looks like Gecko (actual Nightly) retains the correct order or am I wrong?
`
<script>
	function showTokens(set){
		return Array.prototype.slice.call(set).join(" ");
	}
	var html = document.createElement("html");
	html.className = " a b c d ";
	console.log(showTokens(html.classList)); // "a b c d"
	console.log(html.className); // " a b c d "
	html.classList.replace("b", "e"); 
	console.log(showTokens(html.classList)); // "a e c d"
	console.log(html.className); // "a e c d"
	
	html.className = "a b a c";
	html.classList.replace("a", "d");
	console.log(showTokens(html.classList)); // "d b c"
	console.log(html.className); // "d b c"
</script>
`

**Comment by ayg** [comment]
Oops, you're correct.  My build was too old.  If the editors think it's clear, then I'm fine with this being closed.  I just wanted to point it out because an implementer did evidently make that error when implementing it -- although it seems it was a first contribution, not a veteran Gecko hacker.

**Comment by annevk** [comment]
I think this is clear enough as-is. Maybe at some point this can all be described in terms of collections and then we could clarify what "replace" means in a single place. That'd be the way to go.
