### ISSUE TITLE
Define how script-created click events are special during dispatch

### ISSUE THREAD

**Issue by foolip** [whatwg/dom#325]
https://w3c.github.io/uievents/#trusted-events
https://w3c.github.io/uievents/#default-action

If one starts reading at https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent there is no way to discover that click events are special. Probably it should be handled in the dispatch algorithm itself, or perhaps there should be an explicit extension point that UI Events could use.

Related to https://github.com/w3c/uievents/issues/104 and https://github.com/w3c/uievents/issues/106

@travisleithead @garykac @dtapuska @RByers

**Comment by annevk** [comment]
As part of this we should resolve https://www.w3.org/Bugs/Public/show_bug.cgi?id=12230. Legacy wins once again.

**Comment by domenic** [comment]
I wonder if we should work on PRs to UI events to fix those two bugs you mention, @foolip? They are long-standing and pervasive problems with UI events that have caused a lot of confusion throughout the ecosystem. (Also https://github.com/w3c/uievents/issues/95 and https://github.com/w3c/uievents/issues/90 maybe...)

Curious what the editors of UI events think.

**Comment by foolip** [comment]
I'd also like to hear input from UI Events editors. I'm also reminded of https://groups.google.com/a/chromium.org/d/msg/blink-dev/WEMnlVIbe70/hP7fhHP0AAAJ (from @phistuck) about what kind of event it has to be. It seems likely that allowing any kind of event will work with more content and also makes the layering simpler.

**Comment by annevk** [comment]
I talked about this a while back with @smaug----. https://dom.spec.whatwg.org/#concept-event-dispatch uses "get the parent" to determine where to invoke listeners. Something similar is used at the end of dispatch. https://www.w3.org/Bugs/Public/show_bug.cgi?id=12230#c29 also explains this. That is what we should use here and we should only do it if the canceled flag is not set.

Then we can let specifications define "legacy post-dispatch steps" for objects that need them (only `<a>`?). (I don't want to call it "default action", not even prefixed with "legacy". I think that would continue to cause much confusion.)

Does anyone see problems with that?

**Comment by annevk** [comment]
(It's an awful lot of machinery for such an edge case, but I don't really see a better way.)

**Comment by garykac** [comment]
Sorry for not seeing this thread earlier. We definitely want to fix this in
UI Events, but there are some subtleties in the terminology that I want to
make sure I get right when making this change.

Also, since people will still search for "default action" (it's used
throughout the web), I think we'll still need a glossary entry indicating
that the term is inappropriate and should not be used (and also have
pointers to the "legacy post-dispatch steps").

Is it worth setting aside some time at TPAC for this?

On Thu, Sep 15, 2016 at 7:09 AM, Anne van Kesteren <notifications@github.com

**Comment by RByers** [comment]
Note that after much effort, @dtapuska has succeeded in pushing the [breaking change out to chromium stable] (http://crbug.com/520519).  It's now truly only `click` where this is special in blink.

**Comment by smaug----** [comment]
That sounds super great!

**Comment by annevk** [comment]
This basically means refactoring HTML too, for its "run post-click activation steps". I noticed HTML has "run pre-click activation steps" too, which are defined for `<input type=checkbox>` and `<input type=radio>`.

And per http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4567 it seems these are run for all synthetic `click` events (as long as they implement the `MouseEvent` interface).

So maybe I should just integrate what HTML already defines, pre-click activation steps and activation behavior, and then update HTML to remove some of the redundancy. That seems like the easy way out here.

**Comment by annevk** [comment]
One thing we need to decide upon is when the post-click-dispatch steps are run. E.g., in Gecko the click event that causes those to be run will still have `eventPhase` set to 2, whereas in Chrome it is 0. http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4568

Both browsers do agree that `currentTarget` is null and only Chrome exposes `composedPath()` at the moment which returns an empty array.

Chrome also allows recursion to happen (stops after 42 times or so) whereas in Firefox the "dispatch flag" is not yet unset and therefore `dispatchEvent()` throws.

I'm inclined to align with Chrome here though that would require taking a copy of event's path as we'd have to set it to null to not reveal anything through `composedPath()`.

**Comment by annevk** [comment]
I created #342 to address this. What I'd like feedback on:

* `label` elements seem to require looking at the event's target to determine their "activation behavior" (as HTML currently calls it). I guess that means we should at least pass the target along to the algorithm?
* The pre-click-dispatch steps are quite exceptional and only used by two elements, but post-click-dispatch ("activiation behavior" in HTML today) is quite universal. Perhaps we shouldn't call the latter legacy? It seems any new element with activation behavior should probably be triggered the same way. Or not?

I also noticed that irrespective of whether the event's canceled flag is set, we need to run some steps. So we should probably have both post-click-dispatch steps and post-canceled-click-dispatch steps. Good times.

Anything else I missed?

**Comment by annevk** [comment]
There's another major difference between implementations here. It seems Chrome/Safari follow HTML when it comes to only running the pre/post steps for a single element, whereas Firefox does it for the entire event path. Simple demonstration: http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4570. (What Chrome/Safari matches HTML's current language around "activation behavior" and seems better.)

(Note that you cannot mutate the event path so you'll always get the same element.)

**Comment by annevk** [comment]
Another thing I missed and discovered while discussing with @smaug---- is that bubbling matters. We agreed that looking at bubbling even for the pre-click steps was okay (as that would mean any corresponding post-canceled-click steps would always end up running too). That does not match Firefox at the moment, but it's an extreme edge case, requiring nodes to be nested in an `input` element. Doing it that way however requires finding the "activation target" only once and we no longer need multiple traversals of the event's path.

I also decided to stick with the name "activation behavior" as I doubt we're going to come up with another pattern for that kind of thing. Might as well enshrine it.

**Comment by annevk** [comment]
So some testing shows `<label>` does indeed look at the target of the event (and elements between the target and itself). `<input type=image>` also needs the coordinates of the event. So passing the event itself to "activation behavior" seems like the way to go.

**Comment by dtapuska** [comment]
While @RByers is correct about click and the default event handler in Blink. I believe we do have a couple of pre-dispatch handlers in Blink that act on pre-dispatch events.

TextInput can submit a form (probably not good)...
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/HTMLInputElement.cpp?sq=package:chromium&rcl=1476256712&l=1147

touchstart and mouse down open controls...
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/shadow/MediaControlElements.cpp?sq=package:chromium&rcl=1476256712&l=250

Seems like a work around for a bug to me:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/forms/TextFieldInputType.cpp?sq=package:chromium&rcl=1476256712&l=73

Can probably be tested with isTrusted...
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/HTMLMediaElement.cpp?sq=package:chromium&rcl=1476256712&l=3641

We only have one postDispatch event handler and that is for click.

**Comment by annevk** [comment]
@dtapuska if you are saying that they respond to synthetic events that would be problematic as that means they need to be part of dispatch (otherwise they could be part of the OS input action). I wonder how interoperable those are.

**Comment by dtapuska** [comment]
The non-click based ones are basically a filter to stop propagation of the event. And I'm not sure how interoperable those are because it means that we aren't actually calling the event handlers on the target. It seems to me that the filter probably should be done in the default handler itself.

The MediaControlsElements end up showing a cast overlay when an event occurs. 
The HTMLMediaElement is using DOM events to detect fullscreen change. Kind of odd.

The problem is the pre-dispatch virtual has been conflated and probably can be cleaned up if we target only to be click event oriented.

**Comment by annevk** [comment]
I'm afraid I don't really follow. Are you saying that most likely these can be restricted to isTrusted = true or can be refactored in some other way such that they would not necessitate patching the event dispatch algorithm beyond `MouseEvent("click")`?

**Comment by annevk** [comment]
Looking at the Blink code and what nodes these special cases apply to I don't think there's a real problem here and these can probably either be guarded with isTrusted or fixed down the line.
