### ISSUE TITLE
event.composedPath() should not return every items in path if event.currentTarget is window

### ISSUE THREAD

**Issue by hayatoito** [whatwg/dom#326]
According to the current composedPath() definition, window.composedPath() would
return every items, even if the item's root is a closed shadow root, because
window is not a node.

**Comment by annevk** [comment]
Why would window have a `composedPath()` method?

**Comment by hayatoito** [comment]
Ah. That's my mistake.
I meant that event.comopsedPath() is called from an event listener registered on window.

Let me update the PR and this issue.

**Comment by hayatoito** [comment]
I have updated the PR. Could you have a chance to take a look?
