### ISSUE TITLE
Consider adding Promise-based API for listerning event

### ISSUE THREAD

**Issue by upsuper** [whatwg/dom#333]
We now have `once` option in `AddEventListenerOptions`, but wouldn't it be more convenient if there is a Promise-based API for that?

Probably something like

``` text
partial interface EventTarget {
  Promise<Event> on(DOMString type, optional EventListenerOptions options);
}
```

and let it behave like `AddEventListenerOptions.once`?

**Comment by annevk** [comment]
@domenic mentioned https://github.com/tc39/proposal-observable will likely become part of JavaScript at some point in the future. We should probably wait until that happens to see what kind of abstractions we can build on top.

**Comment by dtapuska** [comment]
I don't care for for the key event example @domenic  provided there. At least for keyboard events we want to take advantage of threaded scrolling. But having javascript filter every key event prevents that so a filter on the registered event listener is best for the UA for some apps that only care about certain keys; like 'Enter'. Then PageUp/PageDown can be accelerated and not dispatch javascript at all. But +1 for Observables.

**Comment by benjamingr** [comment]
There are also async-iterators. currently stage 2 https://docs.google.com/presentation/d/1r2V1sLG8JSSk8txiLh4wfTkom-BoOsk52FgPBy8o3RM/edit#slide=id.g1236b1e2d6_0_320 and you can build on those.

That said, for event emitters observables are likely a better fit.

**Comment by blesh** [comment]
> There are also async-iterators. currently stage 2  https://docs.google.com/presentation/d/1r2V1sLG8JSSk8txiLh4wfTkom-BoOsk52FgPBy8o3RM/edit#slide=id.g1236b1e2d6_0_320 and you can build on those.

> That said, for event emitters observables are likely a better fit.

Definitely a better fit. I don't think allocating a Promise for every mouse movement event would be very efficient.

**Comment by benjamingr** [comment]
You don't actually need to allocate a promise for every mouse click - and note that allocating a promise is cheaper than an empty array at this point so unless you have hundreds of thousands of mouse clicks and handling of concurrently it's not a huge issue. 

However, I think observables are a nicer fit conceptually since they're push streams and model clicks much more naturally. Even if you'd use async iterators you'd bastardize them to act like observables in this case though a function that consumes from the iterators as elements enter the iteration. With observables it's just subscribe.

**Comment by blesh** [comment]
> note that allocating a promise is cheaper than an empty array at this point 

Not all runtimes are created equal. Netflix has to deal with exotic runtimes and older browsers where this isn't true. And hardware isn't always great, or is sometimes busy.

**Comment by domenic** [comment]
Sure, but those runtimes won't have a DOM implementation that conforms to any update of this standard, so they're not relevant to designing future features.

**Comment by blesh** [comment]
You can't make that assumption, though, can you? JavaScript runtime performance and DOM standards conformity aren't inherently linked. And it still only addresses half of what I'm saying. Weak hardware isn't going to like additional allocations regardless of standards conformity.

**Comment by annevk** [comment]
@benjamingr the problem with async-iterators is that promise-based timing is not compatible with event dispatch. E.g., if you want to use `preventDefault()` (or `respondWith()` in service workers) you need to be able to do that "synchronously" and not in a microtask later on.

**Comment by benjamingr** [comment]
Why exactly can't preventDefault or respondWith be called after a microtask? It's not as if we're letting timers run ahead of them?

A smart implementation would need to allocate very few promises anyway.

That said:

> However, I think observables are a nicer fit conceptually since they're push streams and model clicks much more naturally. Even if you'd use async iterators you'd bastardize them to act like observables in this case though a function that consumes from the iterators as elements enter the iteration. With observables it's just subscribe.

**Comment by annevk** [comment]
> Why exactly can't preventDefault or respondWith be called after a microtask? It's not as if we're letting timers run ahead of them?

If we could make that work at all (it's not clear to me how, given that you could have both `.on()` and normal listeners), how that would for for synthetic events?

**Comment by benjamingr** [comment]
> If we could make that work at all (it's not clear to me how, given that you could have both .on() and normal listeners),

We're talking about `preventDefault` here and not `stopPropagation` so I don't see what the issue with making it work is in the first place - let alone for synthetic events.

**Comment by annevk** [comment]
@benjamingr because the code looks like:
```js
var doSomething = obj.dispatchEvent(new Event("test", {cancelable:true})
if(doSomething)
  // ...
```
So if the `preventDefault()` is not invoked during dispatch, `if(doSomething)` will go down the wrong branch.

**Comment by isiahmeadows** [comment]
[Here's why I find this proposal not as great as it might seem](https://github.com/tc39/proposal-observable/issues/129). It may seem nice at first, but the allocations would make it a performance nightmare, especially on highly spammy events like `"mousemove"`.

**Comment by isiahmeadows** [comment]
Although it only bears tangential relevance, Rust's [`futures` library](https://docs.rs/futures) is 1. 100% pull-based, and 2. requires you to use `stream.for_each` and connect the resulting future to an event loop to be able to react to changes. JS has a native event loop and is much more idiomatically push-based, which makes that kind of model much more awkward.

**Comment by upsuper** [comment]
I don't think this is a problem for this proposal. This Promise-based API would behave like a listener added with `once` specified. So it is a one-off thing. If you need to continuously monitor an event like `mousemove`, it makes no sense to use it. It is mostly for replacing the structure of
```js
elem.addEventListener(type, function handler() {
  elem.removeEventListener(type, handler);
  doSomething();
});
```
or the new syntax
```js
elem.addEventListener(type, function() {
  doSomething();
}, {once: true});
```
with
```js
await elem.on(type);
doSomething();
```

**Comment by isiahmeadows** [comment]
What makes that any different than what you can do already? It's fairly easy to pull into a utility function.

```js
function on(elem, type) {
    return new Promise(resolve => {
        elem.addEventListener(type, function listener(ev) {
            this.removeEventListener(type, listener, false)
            resolve(ev)
        }, false)
    })
}
```

And given the new `once` option, I seriously doubt such a thing is worth it.

**Comment by annevk** [comment]
I think the main problem with this and why I'm going to close it is timing. The promise "callback" is called too late to be able to use `preventDefault()`, which makes it not a great pattern for event listeners.
