### ISSUE TITLE
Improvements for adjacent text nodes manipulation

### ISSUE THREAD

**Issue by Netmosfera** [whatwg/dom#335]
Dropping here a couple of things I would like to have in DOM.

While I like that contiguous text nodes can be used as separated entities, e.g. for setting their contents without touching their surrounding text siblings, I think something more could be done for when creating adjacent text nodes is not intentional.

First of all, the problem with `normalize()`: it's impossible to normalize a sequence of text nodes only without touching others in the same parent element:

```
running div.normalize(); will merge both sequences
<div>
      first text node       <- I only want
      second text node      <- these two merged
      <span></span>
      first text node       <- While these must stay
      second text node      <- two distinct text nodes
</div>
```
### `Text.prototype.getFirstNearbyText = function(skipComments){};`

Selects the first Text node in a sequence of contiguous Text nodes.
`this` is any of the Text nodes in the sequence.
`skipComments = true` would make the algorithm ignore `<!-- comments -->` between text nodes. 
### `Text.prototype.getLastNearbyText = function(skipComments){};`

Like previous, but selects the last Text node in the contiguous Text nodes sequence.
### `Text.prototype.getNearbyTextString = function(skipComments){};`

Same purpose of `textNode.wholeText` except that it allows to jump around comment nodes if arg0 is true. `textNode.wholeText === textNode.getNearbyTextString(false)`. Returns a `DOMString`.
### `Text.prototype.mergeNearbyText = function(eatComments){};`

Replaces this Text node's nearby Text siblings with a new single Text node containing said siblings' concatenation of DOMStrings and returns it.

Thoughts?

**Comment by annevk** [comment]
Can you justify why you want these things? Is there JavaScript library precedent for these kind of operations?

**Comment by annevk** [comment]
https://wiki.whatwg.org/wiki/FAQ#Is_there_a_process_for_adding_new_features_to_a_specification.3F is a good resource to read through.

**Comment by Netmosfera** [comment]
Hi annevk. I don't _want_ anything :P i think I'm just suggesting something that could be discussed. Working with adjacent text nodes, normalization, is tedious... to say at least. I do realize people, me included, don't do that very often, but I think that's because API is not collaborative enough, i.e. "I would rather wrap this in an element rather than venture myself into adjacent text nodes manipulation". There's a whole bunch of functions that could be added and that I think would be used if they existed. Would them be overkill?

**Comment by annevk** [comment]
It depends, if libraries have added these kind of functions and lots of developers use them, then sure, it makes sense to standardize them. I haven't really seen anything to that effect though.

**Comment by Netmosfera** [comment]
I just noticed DOM3 has one of them:
```
Text replaceWholeText(in DOMString content) raises(DOMException);
```
It's implemented by MSIE9+, doesn't exist in FF, Chrome.

**Comment by annevk** [comment]
Yeah, DOM3 doesn't count. We need something that is in use by lots of sites.

**Comment by annevk** [comment]
I'm going to close this due to lack of follow-up and interest. We can always revive this if that changes.
