### ISSUE TITLE
insert/remove hooks need to be invoked for ancestor changes too

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#34]
See https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0600.html and https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0572.html in particular.

**Comment by annevk** [comment]
https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0617.html seems key. The processing model we end up with is that whenever "insertion steps" and "removing steps" run now, we instead run them for all inclusive descendants, in tree order, with a "noscript flag" set. Then we run them again, without that flag set.

In addition we need to pass in context about which node we run the steps for and which node was actually removed/inserted. 

Seems fairly trivial.

Are there any tricky cases with compound insertions/removals? If you insert a `DocumentFragment` or remove all children, what kind of tree does each notification see? I suspect it's per individual insertion/removal, but it would be good to have that confirmed.

**Comment by smaug----** [comment]
Do we need the "without that flag set" part? Could we rely on nanotask queue to process whatever
insertion/removing steps need to do at safe time?


In Gecko inserting DocumentFragment does cause inserting its children one by one, and
depending on whether one is inserting or appending, ContentInserted or ContentAppended
is called. ContentAppended is effectively just an optimization where you need to just tell the first
node which was appended. Probably not something we need to expose to the web. Though, MutationObserver gets just one record when DocumentFragment is inserted.

**Comment by annevk** [comment]
Yeah, perhaps I should wait with the script stuff until it is clear what needs it (other than `<script>` as we established) and add a note for now that it needs to be tackled somehow.

(`DocumentFragment` causing a single mutation record is covered already. That's mostly what triggered the question. I agree that we shouldn't put any optimizations in the specification though.)

**Comment by annevk** [comment]
http://krijnhoetmer.nl/irc-logs/whatwg/20150729#l-370 seems to be suggesting

* node::bind(newParent)
* node::ancestorBind()
* node:unbind(oldParent, oldPreviousSibling)
* node::ancestorUnbind()

perhaps with an additional argument for "in-document" or just passing the ancestor in.

It's also still unclear whether this is enough to explain all existing features or whether they also need some form of mutation observers that is synchronous.

**Comment by annevk** [comment]
Blink seems to notify a few things before removal (the range stuff the DOM Standard handles directly within the remove algorithm):

* https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/dom/Document.cpp&l=3728
* https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/dom/ContainerNode.cpp&l=664

They then have a pretty clean interface for elements and such:

* https://gist.github.com/dglazkov/4e5d449a1931b7b5bba7

**Comment by annevk** [comment]
Based on discussion with @coonsta we should make these changes:

* Where https://dom.spec.whatwg.org/#concept-node-remove makes range adjustments we also need to make `NodeIterator` adjustments and add an issue for focus adjustments.
* Where we run the removing steps we don't need to pass _oldPreviousSibling_ and per previous comments we need to invoke them for descendants too.
* We probably need a way for algorithms that hook into the removing steps to queue a follow up algorithm where they can run script. That queue is drained after all the removing steps have been called. This allows for implementing `<script>`. Not sure if there's anything else. We should make sure this doesn't negatively impact any range algorithms. (Or adjust them if it does.)
* Fullscreen and Pointer Lock should be able to make use of the generic hooks.

**Comment by annevk** [comment]
@smaug---- should have separate steps for ancestor insert/remove vs node insert/remove or share them and name the argument newAncestor/oldAncestor. Separate steps might be clearer?
