### ISSUE TITLE
setAttributeNS needs special-casing for the xlink namespace

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#343]
Found in https://github.com/tmpvar/jsdom/issues/1624; credit to @PatrickKing.

Test case: http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4571

I think https://dom.spec.whatwg.org/#validate-and-extract needs to some special handling here. However, browsers seem rather non-interoperable if you vary that test case (e.g. change the namespace URL, or add a prefix to the qualified name).

**Comment by domenic** [comment]
Oh, this might be invalid, or rather not a DOM issue, but instead a serialization issue with outerHTML. http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=4572 shows that the .prefix property seems to be null still.

**Comment by annevk** [comment]
Yeah, serialization of namespaces is a mess. I think @travisleithead did write some algorithms for it over in https://w3c.github.io/DOM-Parsing/ but I'm not sure they have buy-in from everyone.

**Comment by annevk** [comment]
Closing this since the DOM doesn't define serialization.
