### ISSUE TITLE
Proposal: ParentNode#append() to return self

### ISSUE THREAD

**Issue by maciejhirsz** [whatwg/dom#348]
A minor quality of life change that would allow changing this:

``` js
function createFoo(bar) {
    let foo = document.createElement('div');
    foo.append('Inside foo', bar);
    return foo;
}
```

Into:

``` js
function createFoo(bar) {
    return document.createElement('div').append('Inside foo', bar);
}
```

This would also make it easier for transpiler authors to target the bare-bones DOM API with syntax like JSX or similar.

**Comment by annevk** [comment]
That seems a little weird, since e.g., `appendChild()` returns the child it appended.

**Comment by domenic** [comment]
In general we don't want to support this chaining style in web APIs, I'd say. We should respect [command-query separation](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation) as much as possible.

**Comment by maciejhirsz** [comment]
Fair enough :).

Thanks for considering.
