### ISSUE TITLE
Can no longer access https://dom.spec.whatwg.org

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#351]
I am no longer able to access https://dom.spec.whatwg.org in Firefox / Chrome or Safari.

I get a SEC_ERROR_UNKNOWN_ISSUER error code.

**Comment by cdumez** [comment]
@annevk Can you reproduce?

**Comment by inexorabletash** [comment]
Some discussion on [#whatwg](http://logs.glob.uno/?c=freenode%23whatwg#c1009536)

Looks like a certificate name mismatch:

https://www.ssllabs.com/ssltest/analyze.html?d=dom.spec.whatwg.org

**Comment by domenic** [comment]
I was able to fix this locally by flushing my computer's DNS cache. On Windows it's `ipconfig /flushdns` from an elevated command prompt.

This sucks; not sure how it could have gone better.

**Comment by annevk** [comment]
Apologies for the downtime. I think it was mainly related to slow DNS propagation. This WHATWG subdomain was hosted at a somewhat unusual spot and I wanted to resolve that before working on #350.
