### ISSUE TITLE
Is EventTarget really an interface, or is it a mixin?

### ISSUE THREAD

**Issue by tuespetre** [whatwg/dom#355]
I ask because I noticed that currently, DocumentFragment and ShadowRoot should implement addEventListener et al by implementing Node which implements EventTarget. Is there really any user agent that does that? It doesn't seem right, am I missing some detail?

**Comment by annevk** [comment]
Have you found a user agent that does not?

**Comment by tuespetre** [comment]
Wow, I must really be tripping. I could have sworn that it wasn't there these past couple of days. I'm sorry for wasting your time! 😹

**Comment by annevk** [comment]
No worries, happy to help.
