### ISSUE TITLE
Nit: URI fragment for NonElementParentNode says 'interface' and not mixin

### ISSUE THREAD

**Issue by tuespetre** [whatwg/dom#357]
https://dom.spec.whatwg.org/#interface-nonelementparentnode

Don't know if you didn't want to break linking or something like that, but thought I would point it out.

**Comment by tuespetre** [comment]
Also:

https://dom.spec.whatwg.org/#interface-parentnode
https://dom.spec.whatwg.org/#interface-nondocumenttypechildnode
https://dom.spec.whatwg.org/#interface-childnode

**Comment by annevk** [comment]
Yeah, it's basically because I don't want to break existing links. We might also slightly redo the way we do mixins in IDL so it may change a little further. Closing, but let me know if you need this reopened.

**Comment by tuespetre** [comment]
Is the WebIDL spec the one that I should check out for more information on those kinds of things?

**Comment by annevk** [comment]
https://heycam.github.io/webidl/ describes how the IDL fragments coupled with the algorithms in the standard end up reflecting in JavaScript.

**Comment by tuespetre** [comment]
Thank you!
