### ISSUE TITLE
Give "create an event" a target argument

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#358]
In https://github.com/whatwg/dom/pull/354#issuecomment-256938608 @bzbarsky suggests that rather than a Realm argument we pass an event target to "create an event".

This would be a change from what @domenic came up with in #349 a couple days ago.

**Comment by bzbarsky** [comment]
One issue is that "create an event" is called from event constructors too.  Given that, passing a realm makes sense, and callers will just have to get one off their target.

Or we could have a "create an event for dispatch to target" algorithm for convenience?

**Comment by annevk** [comment]
Given that in the majority of cases callers will use "fire an event" I suspect we might be fine. If we start noticing misuse of "create an event" (rather new) we can revisit.
