### ISSUE TITLE
Why doesn't testing for node equality include an initial check for node sameness?

### ISSUE THREAD

**Issue by tuespetre** [whatwg/dom#360]
https://dom.spec.whatwg.org/#concept-node-equals

At first thought it seems like you could check for sameness as a first step and return `true` early if possible. Are there any potential issues with such an approach? If so, could the reasoning be noted in the specification?

- [WebKit does not check for sameness](https://github.com/WebKit/webkit/blob/9a8e6b0ca9a0cc5a0cfb0f7177526b217ea6ee75/Source/WebCore/dom/Node.cpp#L1256)
- [Gecko does not check for sameness](https://github.com/mozilla/gecko-dev/blob/802e7b16f9ea42599aa6e03189babecfb49d6f9b/dom/base/nsINode.cpp#L991)

**Comment by annevk** [comment]
I don't think there are any issues necessarily. Probably nobody thought it was worth creating a fast-path for that case. (Sorry for the slow reply, I somehow missed this.)
