### ISSUE TITLE
Meta: commit snapshot cleanup

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#363]
Tips from @domenic:

> I had some script where you could press the key "y" to get a snapshot, like on GitHub. It's only working on streams though hmm
> Ah I missed this line https://github.com/whatwg/streams/blob/master/index.bs#L63
> So that + https://github.com/whatwg/html/blob/master/.travis.yml#L4-L7 in a follow-up commit
> Maybe also a readme update like https://github.com/whatwg/streams#streams-standard

**Comment by domenic** [comment]
We should also remove the line

```
TESTS_DIR="tests"
```

from deploy.sh; it's leftover copied and pasted from streams.

**Comment by annevk** [comment]
I ended up not changing the README since I kinda like the current style and didn't want to completely redo it.
