### ISSUE TITLE
Allow an EventTarget to provide the default value of the AddEventListenerOptions

### ISSUE THREAD

**Issue by dtapuska** [whatwg/dom#365]
In order to support interventions such as [Default passive true for touch blocking listeners on root level targets](https://github.com/WICG/interventions/issues/35) we need a hook in the DOM specification to be able to override the default value of the passive field.

**Comment by dtapuska** [comment]
@foolip @RByers @smaug----  @annevk 

WDYT?  And then I'll have to put a hook in the touch event spec that defines a default passive algorithm on window, document and html element.

**Comment by annevk** [comment]
In your patch you say an argument is passed, but you don't actually pass a parameter. Assuming that is fixed, would we only change the default for certain event types?

**Comment by dtapuska** [comment]
Yes only touchstart and touchmove are covered under our intervention. Our long term goal is to have these both default to passive: true. However in the meantime we'd like to default them to passive: true if the ContextObject is either window, document, or document.body (as defined in HTML spec).  I was planning on putting this wording into the Touch Event Spec; ie to define the default passive algorithm on Window, Document and HTMLElement.

**Comment by annevk** [comment]
I think it's a little weird for Touch Events to define that as HTML/DOM define these objects. Guess I'll wait to see what everyone else who was pinged thinks.

**Comment by foolip** [comment]
Given the goal of making some `addEventListener('touchfoo', callback)` calls result in passive behavior without code changes, I don't see any way other than treating a missing `passive` member as a third state that resolves to either true or false. So I have no suggested changes for the behavior itself.

Making EventTarget the extension point works for me, but I can see two other ways that'd be indistinguishable but result in different layering:
* Instead of making the event target the extension point and passing the event type, make the event type the extension point and pass the event target.
* Resolve undefined to true or false later when determining which elements have event handlers that can `preventDefault()` and block scrolling.

In both cases Touch Events would use the extension point. If either of those or another mechanism seems preferable to anyone they ought to work, but implementation-wise I think there's little reason to layer things like that.

**Comment by dtapuska** [comment]
I've created a pull request on the touch event spec; see w3c/touch-events#75

**Comment by foolip** [comment]
@smaug----, do you have time to go over the options here?

**Comment by RByers** [comment]
This seems reasonable to me.

> Instead of making the event target the extension point and passing the event type, make the event type the extension point and pass the event target.

I can see how this might be simpler.

> Resolve undefined to true or false later when determining which elements have event handlers that can preventDefault() and block scrolling.

This would have slightly different semantics from the current definition, eg. in the case that a 2nd HTMLBodyElement is added after the `addEventListener` call.  We could probably work around that, but in general deferring the decision point to after `addEventListener` seems more complex and harder to reason about to me.  I don't have a strong opinion though.

**Comment by smaug----** [comment]
(in my todo list, but can't do the context switch just right now.)

**Comment by annevk** [comment]
Talking with @foolip "offline" I noticed that since event handler attributes are not explicitly linked to `addEventListener()` at this point in time. So `ontouchfoo` would not be affected while it probably should be.

https://github.com/w3c/ServiceWorker/issues/1004 is basically that issue.

**Comment by foolip** [comment]
The current situation is that in the [blink-dev intent thread](https://groups.google.com/a/chromium.org/d/msg/Blink-dev/BW3qrkisqIs/v5Au-HVTAwAJ), we're trying to get some sense of whether anyone else will be interested in shipping this.

My take is that tweaking `addEventListener` isn't super satisfying layering-wise, but I see no good alternative, and the end user benefits are substantial. Therefore, lacking objections, I think we should go ahead and try shipping this in Blink, and to be prepared to make changes based on feedback (and data) and get the spec changes merged once it's clear that the change was in fact web compatible. Before then, the PRs should hopefully be enough to unambiguously document what will ship.

**Comment by annevk** [comment]
Well, it isn't really. E.g., does it affect event handler attributes or not?

**Comment by RByers** [comment]
> Talking with @foolip "offline" I noticed that since event handler attributes are not explicitly linked to addEventListener() at this point in time. So ontouchfoo would not be affected while it probably should be.

That's a really good point, thanks!  Yes `ontouchfoo` should be affected too.  @dtapuska can you look into updating the PRs to make that clear somehow?

**Comment by foolip** [comment]
I've checked Blink, and it uses a shared code path so that it'll behave as if `addEventListener('touchfoo', callback, false)` were called.

**Comment by annevk** [comment]
The way we need to make that work is by updating DOM and HTML. DOM needs to have an abstract algorithm that `addEventListener()` invokes (and I guess the same for `removeEventListener()`). And HTML needs to start using that algorithm for event handler attributes rather than directly manipulating event listeners.

**Comment by foolip** [comment]
Makes sense. Since this PR won't be merged for a few months still I think there's plenty of time to work through that.

**Comment by domfarolino** [comment]
@annevk You're saying the abstract DOM algorithm would also be invoked somewhere in [this](https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-attributes:event-handler-content-attributes-3) list correct?

@RByers @dtapuska Seems like this has been shipped in Chrome for a little while, is there any more data that has been collected that suggests this should make it in the specs? Just curious :)

**Comment by annevk** [comment]
@domfarolino the bit that says "the user agent must append an event listener" will need to be modified in HTML.

**Comment by annevk** [comment]
Created https://github.com/whatwg/dom/pull/596 for https://github.com/whatwg/dom/issues/365#issuecomment-259720891.

Would be good to get an answer to @domfarolino's question too.

**Comment by annevk** [comment]
I did not mean to close this. Apologies.

**Comment by domfarolino** [comment]
I noticed that https://github.com/w3c/touch-events/pull/75 was closed (to me, unexpectedly), so I'm not really sure what the status of https://github.com/whatwg/dom/pull/366 or if we're still planning on following through with the aforementioned intervention in the spec, but more info would be greatly appreciated!

**Comment by domenic** [comment]
There appear to be tests for this behavior or something related to it, with no spec backing them:

- https://github.com/web-platform-tests/wpt/blob/master/dom/events/document-level-wheel-event-listener-passive-by-default.html
- https://github.com/web-platform-tests/wpt/blob/master/dom/events/document-level-touchmove-event-listener-passive-by-default.html

**Comment by rniwa** [comment]
> * https://github.com/web-platform-tests/wpt/blob/master/dom/events/document-level-touchmove-event-listener-passive-by-default.html

It seems like they should be at best considered as "tentative" tests.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/29039 to rename those two tests.

**Comment by domenic** [comment]
Quick status update: it appears what remains to be specced (and is implemented in at least 2 browsers, maybe 3?) is:

- wheel, mousewheel, touchstart, and touchmove events...
- are passive: true by default, when used on window, document, or document.body

We have .tentative test coverage for wheel and touchmove on document. So the work to do is:

- Expand the test suite to the full matrix above
- Make sure there's actually interop
- Update the spec. (There was an attempt in #336 and in https://github.com/w3c/touch-events/pull/75 but it seems to have been abandoned.)

**Comment by zcorpan** [comment]
This test https://github.com/web-platform-tests/wpt/blob/master/dom/events/document-level-wheel-event-listener-passive-by-default.tentative.html says it's a manual test (but doesn't use `-manual` filename suffix), but still includes `testdriver.js` et al. Loading the page from `wpt serve` it fails immediately with `promise_test: Unhandled rejection with value: object "Error: unimplemented"`

Running it with `wpt run` it passes in Chrome, so, it seems it's not actually a manual test. It does this
```js
    await new test_driver.Actions()
       .scroll(pos_x, pos_y, delta_x, delta_y).send();
```

I'll assume that the manual test statement is wrong. Please let me know if I'm missing something though :)

**Comment by zcorpan** [comment]
I suppose it's possible that certain events are not cancelable, independently from default passive event listeners. Is that the case?

**Comment by smfr** [comment]
> The behavior of both Chrome and Safari for [the third demo](http://software.hixie.ch/utilities/js/live-dom-viewer/saved/10398) can't be explained by the existing intervention design docs, as far as I can tell. The behavior seems to be something like: first fire a cancelable event, and if that event is not `preventDefault()`ed, subsequent events for the same gesture are _not_ cancelable.

That is an accurate description of Chrome and Safari's behavior, yes.

**Comment by zcorpan** [comment]
@smfr thanks! But it's unrelated to default passive event listener, which happens during `addEventListener`, right?

The chromium code for that is here:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/events/event_target.cc;l=288;bpv=0;bpt=1

which I think still matches https://github.com/WICG/interventions/issues/35#issuecomment-256356041 (+ `wheel` and `mousewheel`)

**Comment by smfr** [comment]
> @smfr thanks! But it's unrelated to default passive event listener, which happens during `addEventListener`, right?
 
Right. It's a separate kind of intervention intended to maintain good scrolling performance.

**Comment by zcorpan** [comment]
Great! Makes sense. I'll file a separate issue about that intervention.

**Comment by zcorpan** [comment]
Oh, I see now that it's already in the UI Events spec: https://w3c.github.io/uievents/#cancelability-of-wheel-events

**Comment by zcorpan** [comment]
So, Chromium and WebKit also implement this hack for smoothscroll.js:
https://bugs.chromium.org/p/chromium/issues/detail?id=501568
https://github.com/WebKit/WebKit/blob/dd956d5e74249681ddf904e0bbe401f308b65e0f/Source/WebCore/page/Quirks.cpp#L929-L946

As far as I can tell, Gecko does not. https://searchfox.org/mozilla-central/source/dom/events/EventListenerManager.cpp#1593 (and [no search results for "ssc_wheel"](https://searchfox.org/mozilla-central/search?q=ssc_wheel&path=))

Should we put this in the spec?

The use counter is currently at ~0.01% of page views. But scrolling the page doesn't work at all without the hack.
https://chromestatus.com/metrics/feature/timeline/popularity/2020

**Comment by domenic** [comment]
IMO we should put that hack in the spec, although it could perhaps be done separably since it's such a ... unique ... hack.
