### ISSUE TITLE
Upstream `delegatesFocus` property of ShadowRootInit from W3C spec.

### ISSUE THREAD

**Issue by bicknellr** [whatwg/dom#367]
The W3C Shadow DOM spec defined a property of ShadowRootInit dictionaries called [`delegatesFocus`](http://w3c.github.io/webcomponents/spec/shadow/#focus). This property still needs to be brought into the WHATWG DOM spec.

**Comment by annevk** [comment]
I was wondering if HTML could perhaps define that extension since DOM doesn't really say much about focus. But I suppose that's impossible due to the way dictionaries work.

**Comment by TakayoshiKochi** [comment]
I'll handle this with https://github.com/whatwg/html/issues/2013

**Comment by TakayoshiKochi** [comment]
Let's track the issue in whatwg/html#2013 and close this.

**Comment by TakayoshiKochi** [comment]
Ah, maybe it's worth keeping this issue - we have to tweak ShadowRootInit et al. in dom spec.

**Comment by caridy** [comment]
Just a side note: `delegatesFocus` is a very bad property name for such init value IMHO. Do we have time to revisit it? I have found that this is particularly affecting folks with english as a second language. The most common mistake is forgetting the `s` from `delegates`, yes, it is a silly mistake, but nevertheless a mistake. Conjugation, declension and other grammatical rules are not very common in DOM APIs as far as I can remember, I wonder if this can be revisit, e.g. : (`activeFocus`, `focusDelegation` or `focusTransfer`)

This reminds me of some very interesting discussions that we had at TC39 a while ago about language APIs, and how they are perceived by a larger community of developers.

**Comment by annevk** [comment]
@TakayoshiKochi I think we should probably augment it in HTML via `partial` if possible.

**Comment by annevk** [comment]
@caridy I think only Chrome shipped it, but I believe there was also rough agreement on this API shape already I believe, so it would be kinda bad to ask them to rename at this point.
