### ISSUE TITLE
"The adoptNode(node) method, when invoked, must ..."

### ISSUE THREAD

**Issue by tuespetre** [whatwg/dom#368]
https://dom.spec.whatwg.org/#dom-document-adoptnode

> The adoptNode\(node\) method, when invoked, must run these steps:​
> 
> 1. If node is a document, then throw a NotSupportedError\.
> 2. If node is a shadow root, then throw a HierarchyRequestError\.
> 3. Adopt node into **the context object\.**
> 4. Return node\.

Should the bolded part instead be "the context object's node document"?

**Comment by annevk** [comment]
Why? `adoptNode()` only exists on documents.

**Comment by tuespetre** [comment]
Oh man. Just ignore me outright from now on. 😱
