### ISSUE TITLE
"The assignedSlot attribute’s getter must return..."

### ISSUE THREAD

**Issue by tuespetre** [whatwg/dom#369]
Alright, I (will try to) promise this one won't be really stupid. 👷 

https://dom.spec.whatwg.org/#mixin-slotable

> The assignedSlot attribute’s getter must return the result of find a slot given context object and with the open flag set\.

Why should this getter run the 'find a slot' algorithm rather than simply returning the slotable's assigned slot?

**Comment by tuespetre** [comment]
I think I may have figured out why.

At https://dom.spec.whatwg.org/#assign-slotables, step 4, the slotable's assigned slot is set to slot.

> For each slotable in slotables, set slotable’s assigned slot to slot.

But at https://dom.spec.whatwg.org/#concept-node-remove, step 10, there is no provision for setting the node's assigned slot to null.

**Comment by annevk** [comment]
It could maybe be simplified somewhat, but we don't want to expose a shadow root whose mode is "closed". @hayatoito what do you think?

**Comment by hayatoito** [comment]
I think the current definition is good enough, letting UA to optimize that if they want to.

**Comment by annevk** [comment]
Yeah, it's not immediately obvious to me how to make this better either.

**Comment by tuespetre** [comment]
@annevk 

> but we don't want to expose a shadow root whose mode is "closed"

Ah, there's the kicker. I knew I was missing something, thanks!

@hayatoito 

> I think the current definition is good enough, letting UA optimize that somehow if they want to do.

@annevk 

> Yeah, it's not immediately obvious to me how to make this better either.

I was thinking of something like:

1. Let *assigned slot* be the context object's assigned slot
2. If *assigned slot* is null, return null
3. If *assigned slot*'s root is a closed shadow root, return null
4. Return *assigned slot*

With the 'find a slot' algorithm, the return due to a closed shadow root can happen earlier, but finding the assigned slot can happen later due to the tree order traversal. With the alternative, the assigned slot is immediately available, but the check for the closed shadow root is from one to **shadow tree depth** steps of traversal. 

But of course I'm not developing a UA so I couldn't even begin to declare one optimal over the other. 🐸 

I **do** think the node removal algorithm should include a provision for setting the node's assigned slot to null, though. Because here:

> 10. If node is assigned, then run assign slotables for node’s assigned slot.

If a node has an assigned slot, and is removed from a shadow host, and then later added to some other node that does not cause it to be assigned a different slot, and then later removed, this algorithm as-is would cause 'assign slotables' to be run for a slot when it didn't need to.

**Comment by tuespetre** [comment]
Update: turns out the correct way to describe the alternative is:

1. Let *assigned slot* be the context object's assigned slot.
2. If *assigned slot* is null, return null.
3. If *assigned slot* is closed-shadow-hidden from the context object, return null.
4. Return *assigned slot*.

**Comment by annevk** [comment]
I'm still leaning  towards wontfixing this. Implementations can optimize how they see fit, but we don't necessarily need to include all such optimizations in the standard.

**Comment by tuespetre** [comment]
That's understandable. What do you think about "the node removal algorithm should include a provision for setting the node's assigned slot to null"?

**Comment by annevk** [comment]
I don't quite understand what you think is defective there.

**Comment by annevk** [comment]
Closing this due to lack of follow-up.
