### ISSUE TITLE
Inform event handler about the default action of an event

### ISSUE THREAD

**Issue by upsuper** [whatwg/dom#382]
Sometimes authors may want to know the default action of an event if it is not prevented, for example, if it is a shortcut to save the page, the page may want to cancel it and do an internal save action, or if it is a ctrl/cmd-click which opens the link in a new tab, the page may want to do something different than a normal click.

Currently, authors need to detect the platform and even browser to correctly respond to events, for e.g. ctrl on PC vs. cmd on Mac. It might be worth a standard way to know the default action of an event.

**Comment by annevk** [comment]
We generally moved away from default actions being a thing since the API doesn't see them that way. That is, the event flow works like this:
```js
if(target.dispatchEvent(event))
  someAction()
```
So _event_ cannot really know about the action that might occur unless we pass that along as state somehow.

**Comment by cvrebert** [comment]
Seems like the author should listen for something like [IndieUI Events](https://dvcs.w3.org/hg/IndieUI/raw-file/default/src/indie-ui-events.html) instead of the "physical" click/keypress events in such scenarios.
