### ISSUE TITLE
initEvent should not require three parameters

### ISSUE THREAD

**Issue by achristensen07** [whatwg/dom#387]
I have found many instances of web content calling initEvent with only one parameter.  Matching the current spec makes these pages not work, showing up as unresponsive blank white pages.

I therefore propose changing this:
void initEvent(DOMString type, boolean bubbles, boolean cancelable); // historical
to this:
void initEvent(DOMString type, optional boolean bubbles = false, optional boolean cancelable = false); // historical

**Comment by achristensen07** [comment]
Maybe the type should be optional, too.

**Comment by annevk** [comment]
That means those pages break in browsers other than Safari?

**Comment by achristensen07** [comment]
One example was web content packaged inside an iOS app.  Only WebKit would ever read it.
One example was web content that opened successfully in Chrome and Safari but not Firefox because Chrome and Safari do not require 3 parameters and Firefox does.
I couldn't easily find the original source of the other example to try loading it in Chrome and Firefox.  WebKit's attempt at matching the current spec broke an iOS app that is very popular in Asia.

All the affected content had one parameter in the call site of initEvent.  I don't see a reason to require the other two, especially if Chrome and Safari don't require them.

**Comment by annevk** [comment]
@foolip do you know if there are other instances where Chrome does not require arguments?

Does seem good to fix this if both Chrome and Safari match.

Do you know what Edge does?

**Comment by achristensen07** [comment]
Edge requires three parameters.

**Comment by cdumez** [comment]
To clarify Alex's comment, we did not find any evidence of actual Web breakage. However, updating the specification in WebKit broke a lot of iOS apps using WebViews and at least one Safari extension.

**Comment by annevk** [comment]
That's generally not a good enough reason to change the standard, but if @foolip and @smaug---- et al would support adding it to Chrome and Firefox I don't see much reason to stop this. It's a rather trivial IDL change.

**Comment by smaug----** [comment]
Any actual web pages breaking in FF or Edge because of this? Links?
iOS apps or extensions don't count here.

How do all the other init*Event methods behave?

**Comment by cdumez** [comment]
As I said, we have no evidence of actual Web breakage. Sadly, there are a lot of WebKit-specific apps / extensions calling initEvent() with a single parameter. We usually deal with this by adding quirks until those apps get fixed. However, in this case, it seems to be a common pattern and it is breaking a lot of iOS apps.

I agree that this is not a very compelling argument to get the specification changed but Alex thought it was worth trying given the pain we're currently experiencing. Also note that those 2 boolean parameters are not required when you use the Event constructor (i.e. You can call the Event constructor with only a type) and those have default values (false) for the constructor. Therefore, having initEvent() behave similarly wouldn't look too surprising.

**Comment by cdumez** [comment]
Also note that Chrome 55 behaves does not have initEvent() parameters as mandatory. So Safari and Chrome are in agreement at least.

**Comment by smaug----** [comment]
As I asked, how do other init*Event methods behave?

**Comment by cdumez** [comment]
In WebKit, parameters to all init*Event() methods are optional (except for initCustomEvent). The same appears to be true for Chrome based on grep'ing of their code.

Note that the parameters to initCustomEvent() were optional in WebKit until recently (not even sure this shipped in Safari yet).

**Comment by cdumez** [comment]
Any thoughts on this? We had to roll this change out in WebKit because it broke way too many popular iOS apps (including Flipboard and WeChat).

**Comment by foolip** [comment]
Not long before this issue was filed, I [suggested](https://bugs.chromium.org/p/chromium/issues/detail?id=673698#c2) that @LoonyBean try fixing this in Blink, giving it good chances of working out because Firefox and Edge would already throw.

If there is a way for WebKit to make the change, then that'd be great. However, different behavior for a browser and WebView seems the only option, and not a good one.

So, I think we should make the two boolean arguments optional. I'd support doing the same for all `init*Event` methods, requiring arguments only up to the last argument corresponding to a required dictionary member. (Otherwise the `init*Event*` methods can make some attributes null. Another way would be to just make the attributes nullable and sigh.)

**Comment by annevk** [comment]
Is there even a legacy event that has `init*Event` and a required dictionary member? Seems unlikely.

**Comment by cdumez** [comment]
Any update on this? Would anyone oppose if I wrote to PR to update the DOM spec and the web-platform-tests?

**Comment by annevk** [comment]
That sounds good to me. So to recap, the proposal here is that we change *all* `initEvent()` methods, including `initCustomEvent()` et al, to have their arguments, except for the first, be optional and default to the same value as the corresponding event dictionary defaults them to.

This will require changes in DOM, HTML, [UI Events](https://w3c.github.io/uievents/), and maybe more?

**Comment by annevk** [comment]
I do think it would be good if we coordinated the changes to all these standards, to keep it all consistent and make implementation easier.

**Comment by foolip** [comment]
I would like to see the change across the board as well. In Blink, these are the `init*Event()` methods:
* initCompositionEvent
* initCustomEvent
* initDeviceMotionEvent
* initDeviceOrientationEvent
* initEvent
* initKeyboardEvent
* initMessageEvent
* initMouseEvent
* initMutationEvent
* initStorageEvent
* initTextEvent
* initUIEvent

https://software.hixie.ch/utilities/js/live-dom-viewer/saved/4873 is a quick test that confirms what our IDL files suggest, namely that `initCustomEvent` is the only one that requires any argument, namely all 4. Its 4th argument is of type `any`, so making that default to null wouldn't be an issue.

I checked all of the rest, and much to my surprise and delight didn't find any cases where an event interface member would have to be made nullable to accommodate this change. (I found many things like this when looking at event init dicts with no required members.)

**Comment by foolip** [comment]
To clarify, I don't think the change to DOM needs to block on every other PR being ready. In particular, https://w3c.github.io/uievents/ doesn't even have the arguments, and if there's any trouble in fixing that I think we should still fix everything in HTML and DOM.

**Comment by cdumez** [comment]
I am going to try and find time this week end to write the DOM / HTML spec changes, as well as updating the web-platform-tests accordingly.

**Comment by cdumez** [comment]
Uploaded PRs for DOM, HTML and WPT.

**Comment by cdumez** [comment]
Will fully align WebKit via https://bugs.webkit.org/show_bug.cgi?id=169176.

**Comment by annevk** [comment]
@cdumez can you file bugs against Edge and Firefox too? And does Chrome need a bug? I'll land this tomorrow. I'm satisfied with the PR and tests PR.

**Comment by annevk** [comment]
(And thanks for making those!)

**Comment by annevk** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1345044 and https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11187286/.

@foolip can you file the Chrome issue? I wasn't entirely sure it was needed since it seems that Chrome doesn't match either the standard or this revision so likely that's already tracked?

**Comment by foolip** [comment]
Yes, this is tracked by https://bugs.chromium.org/p/chromium/issues/detail?id=673698 in Chromium, and the needed change is to make the first argument required.

**Comment by cdumez** [comment]
Thank you for merging and filing the bugs. WebKit is now aligned with the spec:
https://trac.webkit.org/r213517
