### ISSUE TITLE
Provide an opt-out for inputs overriding form DOM API

### ISSUE THREAD

**Issue by dvoytenko** [whatwg/dom#388]
The problem involves how HTML FORM inputs are exposed on the parent `<form>` element. It was originally introduced in the MS Internet Explorer as far back as JavaScript 1.0 and eventually copied by most of browsers. W3C DOM Level 2 spec has addressed this by introducing HTMLFormElement.elements collection. Unfortunately, the old behavior was left intact for backward compatibility.

Consider the following markup:

```
<form action="...">
  <input name="submit">
</form>
```

Normally, you can submit the form via `form.submit()` API. However, b/c `input` with name "submit" is present on the form, it overrides `form.submit` to be a reference to this input. Thus, `form.submit()` will throw an error "form.submit is not a function".

The same as true for any of the form's properties or methods. As the bottom-line, any normal DOM API can be overridden this way on the form. This, at best, is a big source of inconvenience, and, at worst, an XSS vector.

This old feature is neither needed nor expected. The spec already has `form.elements` collection to provide this functionality w/o messing up the form's APIs. It'd be nice to opt-out a form or a whole page out of this behavior. For instance, `<form do-not-expose-inputs-on-form>` style, or any other in markup or JS API.

You can read more about this problem in this post: https://medium.com/@dvoytenko/solving-conflicts-between-form-inputs-and-dom-api-535c45333ae4#.116oto46q

**Comment by annevk** [comment]
1. This issue is not descriptive enough to be actionable. It would help if you could describe it without reference and only use references for background reading.
2. whatwg/html describes the API I think you have an issue with.

**Comment by dvoytenko** [comment]
@annevk Thanks for the feedback. I have updated the description with more detail. Let me know if this is actionable enough.

> whatwg/html describes the API I think you have an issue with.

Could you please clarify? The issue with with the DOM API, I believe.

**Comment by annevk** [comment]
That is a lot clearer, thanks! But I was right, the API you are concerned with is in another castle. DOM only defines the basics, not element-specific APIs. Those are defined by the HTML Standard.

**Comment by dvoytenko** [comment]
@annevk Thanks! I moved to https://github.com/whatwg/html/issues/2212. Closing this one.
