### ISSUE TITLE
What is the purpose of each part of the event dispatch algorithm?

### ISSUE THREAD

**Issue by tbodt** [whatwg/dom#391]
https://dom.spec.whatwg.org/commit-snapshots/e8a9f67886e554d81cf85277f61c6b1cd0ea6b44/#dispatching-events

There's a lot of stuff going on in this algorithm, but no explanations of why any of it is there or what it's really doing.

**Comment by annevk** [comment]
I'm happy to answer questions or clarify things that are particularly hard, but in general explaining algorithms in detail is not a goal. That'd be a whole additional job and would make the specification a lot harder to read.

**Comment by domenic** [comment]
One thing I did notice is that MDN doesn't seem to have any good explanations of capturing, bubbling, retargeting, get-the-parent, or the other complexities of the event dispatch algorithm. It would be a great contribution for someone to add something there.
