### ISSUE TITLE
"If target’s root is a shadow-including inclusiv..."

### ISSUE THREAD

**Issue by tbodt** [whatwg/dom#392]
https://dom.spec.whatwg.org/commit-snapshots/e8a9f67886e554d81cf85277f61c6b1cd0ea6b44/#dispatching-events

> If target’s root is a shadow\-including inclusive ancestor of parent, then:​

If parent is the window object, which it could be since document's get the parent algorithm normally returns the window object, then it doesn't make sense to talk about the shadow-including inclusive ancestor of parent. Window objects do not participate in a tree.

**Comment by annevk** [comment]
Good point, it seems the previous step also suffers from that. Should be easy enough to exclude Window object from those steps somehow.

**Comment by annevk** [comment]
Duplicating against a newer issue #580 that has more information. I'll make sure to add Theodore Dubois to the acknowledgments section however. Let me know if you don't want that.
