### ISSUE TITLE
Remove "Historical" section?

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#394]
We're updating it in #385 but at the same time I kinda feel like the need for this section has gone away and the accuracy has probably gone down over time too.

**Comment by annevk** [comment]
@domenic thoughts?

**Comment by domenic** [comment]
I think it still contains a lot of value, and helps give something concrete to point to when people end up on old specs and we need to correct them. Some of it could be trimmed; e.g. the more detailed changelogs ("toString is now defined using IDL" seems pretty useless). But the removals of APIs and capabilities, and the moves of APIs between interfaces, are still quite useful IMO.

**Comment by annevk** [comment]
I guess we can remove it once W3C clearly marked up all the older versions of their documents.
