### ISSUE TITLE
EventTarget.addEventListener lacks a proper definition on how to handle invalid callback

### ISSUE THREAD

**Issue by denschub** [whatwg/dom#405]
`EventTarget.addEventListener` specifies that browsers should terminate and ignore the call if the callback is null:

> If callback is null, terminate these steps.

However, it's unclear about what should happen if the callback is not a function/not a callable.

Take the following source, which is clearly a misuse:

```js
document.addEventListener("click", 42);
```

The callback is not `null`, so according to the spec, there is no reason to ignore the `addEventListener` call here. However, browsers behave different. In Chrome, the call simply gets ignored, acting as if the callback would be `null`. In Firefox, however, we throw an exception since a Number is not callable.

To avoid further issues and to make it easier for vendors to adjust their implementations, a note should be added to the spec, saying that the call should be terminated if the callback not callable.

**Comment by domenic** [comment]
That is governed by the Web IDL specification which is used to define the method.

**Comment by annevk** [comment]
Yeah, that would be a bug in Chrome. Could you please file one and leave a link here?

**Comment by denschub** [comment]
Fill file a Chrome bug. Also, Safari Technology Preview also throws, so this is the way to go. I'll throw a link here to the Chrome report, but I'll close this issue nonetheless, since it is actually covered in the WebIDL (sorry, did miss that).

**Comment by denschub** [comment]
Was already reported, see [Chromium bug 676845](https://bugs.chromium.org/p/chromium/issues/detail?id=676845).

**Comment by annevk** [comment]
Thanks @denschub!
