### ISSUE TITLE
"If options is a dictionary, then set capture to..."

### ISSUE THREAD

**Issue by snood1205** [whatwg/dom#408]
https://dom.spec.whatwg.org/commit-snapshots/9d8e4ed93896c50b1cacfceca6f93c56337686d8/#interface-eventtarget

> If options is a dictionary, then set capture to options’s capture\.

By most style guides (AP and Chicago included), `options`'s should be `options`' as it is a plural noun ending in s.

**Comment by domenic** [comment]
`options` in this case is not a plural noun. It's a proper noun that happens to end in `s`.

**Comment by annevk** [comment]
I'll defer to @domenic on this.
