### ISSUE TITLE
Attributes need case-insensitive matching on getting

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#41]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1165851#c23 for what is (likely, hopefully someone confirms my analysis) wrong with the current specification.

**Comment by annevk** [comment]
Note, the way this seems to be solved is simply lowercasing the argument to `createAttribute()`. That's certainly much more attractive.

**Comment by Ms2ger** [comment]
https://github.com/w3c/web-platform-tests/pull/2198
https://github.com/w3c/web-platform-tests/pull/2203
