### ISSUE TITLE
Event Listener Execution Order for Same Event Is Undefined

### ISSUE THREAD

**Issue by patrickdark** [whatwg/dom#415]
If I define `document.defaultView.addEventListener("load", someHandler)` and `document.defaultView.addEventListener("load", someOtherHandler)` in immediate succession, it's not clear from the spec whether the handlers are guaranteed to be executed in defined order. This is important because if the execution order matters, but there's no guaranteed order, then I need to call a third handler that then calls `someHandler` and `someOtherHandler` in the necessary order.

DOM 2 Events has a note at https://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-flow-basic: "Although all EventListeners on the EventTarget are guaranteed to be triggered by any event which is received by that EventTarget, no specification is made as to the order in which they will receive the event with regards to the other EventListeners on the EventTarget." However, in practice it seems that the event listeners are handled in the order in which they were declared.

I'd expect a note regarding this at https://dom.spec.whatwg.org/#introduction-to-dom-events or https://dom.spec.whatwg.org/#dom-eventtarget-addeventlistener.

**Comment by domenic** [comment]
This is pretty clear from the spec. The event dispatch algorithm loops over the list of event listeners in order as it calls them.

**Comment by patrickdark** [comment]
I just read over section 2.8 describing the dispatch algorithm at https://dom.spec.whatwg.org/#dispatching-events and all I see regarding an event listener queue is "For each event listener associated with object, append a pointer to the event listener to listeners."

However, that seems to only describe collecting the existing set of listeners for invocation and says nothing about the order in which they're appended to the invocation queue. Presumably, that order is the same as the listener creation order, but I don't see anything in the spec that says that.

**Comment by domenic** [comment]
When you call addEventListener, it adds to that list. Because there is no other step in the spec saying to shuffle the list into a random order, the order is maintained.

**Comment by domenic** [comment]
One what of making this clearer might be to ask you: how would you implement addEventListener and dispatchEvent in a way that follows the spec but also gives a different order than the order they were appended? I believe it is impossible, but I would welcome some pseudocode implementing those two functions that shows I am wrong.

**Comment by patrickdark** [comment]
@domenic
```
function inner_invoke(listeners) {
    while (listeners.length > 0) {
        let listener = listeners.pop(); // reversed order
    }
}
function invoke() {
    let listeners = object.get_listener_array(); // naturally, in definition order
    inner_invoke(listeners);
}
```

There's seemingly nothing in the spec that says `listeners.reverse()` has to be called in `inner_invoke`.

**Comment by domenic** [comment]
The spec uses "for each" which is in order. It also never removed from the list like your implementation does.

**Comment by patrickdark** [comment]
@domenic Right. But the step also appends a "pointer" to each listener to the invocation queue, not the original listener object, which implies that listeners can be shuffled if you're using a reference list of listeners. I'll take your word for it though since I now know what I needed to know when I filed this issue.

**Comment by domenic** [comment]
Hmm, I'm still curious where in the spec it implies you can shuffle lists of pointers into different orders :)

**Comment by patrickdark** [comment]
@domenic I think "pointer" is a C language term so perhaps I'm missing something? I'm not familiar with programming languages other than JavaScript, PHP, and XSLT.

I'm assuming a "pointer" is just a reference object like in JavaScript. And if you have an array of reference objects, then it's implied that you can reverse the array when processing its items which then reverses the processing order of references.

**Comment by domenic** [comment]
Hmm, I don't see how that's implicit. If I have

```js
const obj1 = { o: 1 };
const obj2 = { o: 2 };

const arrayOfReferenceObjects = [obj1, obj2];

arrayOfReferenceObjects.forEach(obj => {
  console.log(obj.o);
});
```

I don't see anything in the above code (meant to approximate the spec) that "implicitly" allows the VM to rearrange `arrayOfReferenceObjects` into a different order, so that it prints 21 instead of 12.

**Comment by annevk** [comment]
FWIW, if you have suggestions for how to make it clearer, I'm happy to consider making changes.
