### ISSUE TITLE
Question about references after Bikeshed conversion

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#42]
This is intentional that for every constructors/methods/algos you add all arguments to id in definition? 

setAttribute(name, value) 
https://dom.spec.whatwg.org/#dom-element-setattributename-value
but was 
http://dom.spec.whatwg.org/#dom-element-setattributenode

Omg now all references not work, the same is for URL spec but not for Fetch and Encoding :(

**Comment by domenic** [comment]
To fix this you can use Bikeshed's `oldids=""` feature. It is sad that they changed.

**Comment by tabatkins** [comment]
I can make this smarter, but changes will of course change *other* specs. But I doubt people really care, so I'm open to changing.

The problem is that if you have multiple overrides of a method, I need to have disambiguating IDs, so I took the conservative route and produced guaranteed-unambiguous IDs.  I can instead look for collisions and generate simple IDs when there aren't any.

**Comment by ArkadiuszMichalski** [comment]
Hmm this looks ugly, first argument is connected to name without any separator:
https://dom.spec.whatwg.org/#dom-element-getelementsbytagnamensnamespace-localname 

But problem is that any pages that use references for this spec now not work, not only other specs but of course any pages, like MDN, etc. It would be good if changing ids format does not happen often.

**Comment by domenic** [comment]
Yes, I think we should definitely restore the old IDs. The question is whether we do that by adding `oldids=""` for everything or get Bikeshed to do the work for us :)

**Comment by tabatkins** [comment]
Get Bikeshed to do the work for you.

**Comment by annevk** [comment]
If you have overloads you should still only have one method definition and one ID I think.

**Comment by tabatkins** [comment]
No?  You have two method definitions, like:

```
interface Foo {
  DOMString bar(DOMString stringBaz);
  long bar(long numericBaz);
};
```

**Comment by ArkadiuszMichalski** [comment]
Maybe add some less invasive method for colisions, like foo-bar,  foo-bar-2, foo-bar-3 or other format, but don't destroy all referrences what we have now. I don't remeber that see any colision in DOM, URL or Notification sepc so maybe for first def we can have old format but for next colision you can use this new style?

**Comment by tabatkins** [comment]
Yes, I've already agreed that I need to fix non-overload IDs in Bikeshed.

**Comment by annevk** [comment]
@tabatkins that's the IDL, but there should still be a single description for `bar()`. Since IDL ends up invoking a single specification-defined algorithm. (We need to make IDL a bit more imperative about how that handoff works and have it pass in some useful variables, such as the context object (to be named "this"), but that's what it comes down to.)

**Comment by ArkadiuszMichalski** [comment]
Exactly, I'm find some example that showing how it looks like now:

XMLHttpRequest.open()
https://xhr.spec.whatwg.org/#xmlhttprequest
https://xhr.spec.whatwg.org/#dom-xmlhttprequest-open

Document.open()
https://html.spec.whatwg.org/multipage/dom.html#the-document-object
https://html.spec.whatwg.org/multipage/webappapis.html#dom-document-open

Window.alert()
https://html.spec.whatwg.org/multipage/browsers.html#the-window-object
https://html.spec.whatwg.org/multipage/webappapis.html#dom-alert

All nawigate to the same single description with the same ID. Colision in IDL is taked in this way (if you want make id for all IDLs command too):
id="the-window-object:dom-alert"
id="the-window-object:dom-alert-2"

**Comment by tabatkins** [comment]
Okay, fixed.  As long as there's no local collisions, methods will generate with a simpler ID, just `dom-{interface}-{method}`.  When there is a clash, the old method is used to disambiguate all but the first.
