### ISSUE TITLE
prepend/append are inefficient compared to doing it yourself

### ISSUE THREAD

**Issue by esprehn** [whatwg/dom#433]
(1)
```js
let nodes = [...1000 nodes];
for (let i = 0; i < length; ++i)
  parent.appendChild(nodes[i]);
```

This is N, where N is the length of nodes.

vs

(2)
```js
let nodes = [...1000 nodes];
parent.append(...nodes);
```

The latter allocates a document fragment, inserts every node into the fragment, then appends that fragment which removes every node from the fragment and does the work that would have been done in (1).

This is 3N (append to fragment, remove from fragment, insert into page), and double the number of insertions, plus a bunch of removals which the former didn't do at all.

While in theory you could probably come up with a way to skip the fragment and hope no future spec every makes insertion observable, it's actually required in the exception case because the fragment is left as the parent node of the converted nodes.

```js
let e = document.createElement("div")
try {
  document.body.append(e, document);
} catch (e) { }
e.parentNode // => #document-fragment
```

**Comment by annevk** [comment]
Are you proposing that we change this to not use a fragment and just append/prepend directly? I'd have to go back to see why we did it this way to be sure, but I think that's probably reasonable.

**Comment by ArkadiuszMichalski** [comment]
Maybe because this new methods (prepend/append/before/after/replaceWith) operate on multiple arguments and using fragment is easiest to modify the tree in the next steps. All of them [using convert nodes into a node](https://dom.spec.whatwg.org/#converting-nodes-into-a-node) and for multiple nodes can leake this #document-fragment as parent (when conversion faild like above example).

But fragment as transient node also enters additional restrictions:
`document.append(dtd)` << work because we not use fragment (pass one argument)
 `document.append(comment, dtd)` << faild because we can't put dtd to fragment [ensure pre-insertion validity](https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity)

**Comment by snuggs** [comment]
@ArkadiuszMichalski @annevk For what it's worth `.after` seemed to be more performant than `.append`. Or perhaps using (yet another) `DocumentFragment` as an intermediary when collecting template iterations was far superior to using `DocumentFragment` in `template.contents`. Seemed fishy to me like although a fragment was still connected to `Document` somehow based on slowness.

Our operation is to have `.bind`able templates that when given a collection yield the template to the current object iteration and finally appending result of template mapping immediately `.after` template. 

```html
<ul>
  <template name=item>
    <li>Hello {name}!</li>
  </template>
</ul>

<script nomodule src=//unpkg.com/snuggsi></script>
<script nomodule>

// when context is a collection
const
  template = Template `item`
, context  = [ {name: 'DevPunk'}, {name: 'Snuggsi'} ]

template
   // internal template render for each item in context
  .bind (context)
/*
<ul>
    <template name=item>
    <li>Hello {name}!</li>
  </template>
  <li>Hello DevPunk!</li>
  <li>Hello Snuggsi!</li>
</ul>
*/

</script>
```

May not be relevant but definitely in the same ballpark. I know @annevk is adamant about seeing real world use cases. And I agree.

https://github.com/devpunks/snuggsi/blob/master/elements/html-template-element.es#L35-L44

**Comment by annevk** [comment]
@snuggs a new remove API should be its own issue. Would you mind raising one if you have ideas? (Also, what's most valuable I think is library implementations of such APIs and adoption of those library methods. That shows demand most clearly.)

**Comment by snuggs** [comment]
Of course @annevk! You are always preaching about having use cases and I agree 💯 . Difficult to use an eraser on stone. #FreeJewelry 💍 💎 

Will discuss with my colleagues and go through some thorough use cases before raising issue. You all have enough to deal with already. The fact you didn't say _"No"_ means `ParentElement.remove ([elements])` may be an idea worth investigating.

Thanks as always for feedback, and Have a great week!

/cc @brandondees @tmornini @RobertChristopher @btakita

**Comment by annevk** [comment]
Closing due to lack of reply to https://github.com/whatwg/dom/issues/433#issuecomment-289274006.

**Comment by domenic** [comment]
Elliott is no longer working on browsers, but I can answer for him: yes, that would be ideal.

**Comment by annevk** [comment]
I guess I'd be happy to make the change if it can be demonstrated to be compatible. If someone is up for doing that work I'd be happy to help out with the specification changes.

**Comment by annevk** [comment]
Note that you'd likely end up with a lot more mutation records though.
