### ISSUE TITLE
The mutation method macro has undefined behavior when nodes is empty

### ISSUE THREAD

**Issue by foolip** [whatwg/dom#44]
https://dom.spec.whatwg.org/#mutation-method-macro

This doesn't deal with the case where *nodes* contains no node at all. This needs to be defined for `ParentNode.prepend()`, `ParentNode.append()`, `ChildNode.before()`, `ChildNode.after()` and `ChildNode.replaceWith()` called with no arguments.

The only case where there could be any doubt is `replaceWith()`, should that do nothing or remove the context object?

**Comment by annevk** [comment]
Ah yeah, I believe when this came up initially I was hoping we could require at least one argument. I think we should just make this a no-op.

**Comment by annevk** [comment]
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27887 suggests handling them like empty `DocumentFragment` which would make `replaceWith()` act like `remove()`.

**Comment by annevk** [comment]
See also #32 btw.

**Comment by foolip** [comment]
Treating it like an empty `DocumentFragment` works for me.

**Comment by inexorabletash** [comment]
lgtm

**Comment by inexorabletash** [comment]
Well, to be totally nitpicky, the steps to convert nodes into a node don't explicitly "return node" at the end. I don't think that's going to confuse anyone, though.

**Comment by foolip** [comment]
I noticed exactly the same thing and was about to file an issue before I got distracted by something. Please fix :)
