### ISSUE TITLE
 DOMTokenList.add/remove normalize dupes/whitespace even if they're no-ops, but .toggle doesn't

### ISSUE THREAD

**Issue by ayg** [whatwg/dom#443]
Accidentally filed as w3c/dom#118.

> Per the current spec, this outputs "a b c c d d":
> 
> ```html
> data:text/html,<!doctype html>
> <script>
> var res = "";
> var span = document.createElement("span");
> span.setAttribute("class", "a a");
> span.classList.add("a");
> res += span.getAttribute("class");
> span.setAttribute("class", "b b");
> span.classList.remove("a");
> res += " " + span.getAttribute("class");
> span.setAttribute("class", "c c");
> span.classList.toggle("c", true);
> res += " " + span.getAttribute("class");
> span.setAttribute("class", "d d");
> span.classList.toggle("a", false);
> res += " " + span.getAttribute("class");
> document.documentElement.textContent = res;
> </script>
> ```
> 
> This is not consistent.  If we want add/remove to normalize even if they're no-ops, so should toggle.  This is especially true because force-toggle is otherwise precisely identical AFAICT, and the slight difference is confusing.
> 
> replace also doesn't normalize if the token doesn't exist, but that doesn't bother me as much since it doesn't otherwise behave identically to add/remove.

> I hit this because it complicates testing -- if force-toggle worked the same as add/remove, we could reuse add/remove tests for force-toggle for free.

I do have tests, which I'm [submitting upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1354066).

**Comment by ayg** [comment]
No-op .replace() also doesn't normalize.  If force-toggle is being changed, then it makes sense to change replace also, so that all of them are consistent.

I didn't test browser behavior for any of this, but I volunteer to update Firefox if the spec changes.

**Comment by ayg** [comment]
```html
data:text/html,<!doctype html>
<script>
var span = document.createElement("span");
span.setAttribute("class", "a a");
span.classList.replace("b", "a");
document.documentElement.textContent = span.className;
</script>
```

Firefox Developer Edition outputs "a", so it already normalizes in this case, contrary to the spec.  I'm still not able to test WebKit or Edge.

**Comment by ArkadiuszMichalski** [comment]
IE11 and Edge doesn't support `replace` method. Also Firefox Dev is not correct here:
```
data:text/html,<!doctype html>
<script>
var span = document.createElement("span");
span.setAttribute("class", "a a");
span.classList.replace("b", "c");
document.documentElement.textContent = span.className;
</script>
``` 
outputs "a a". It's nice to finally you make changes to the sets on Firefox.

**Comment by ayg** [comment]
WebKit outputs "a a" for both of those two test-cases.  I think "a" is best here, as #444 institutes.
