### ISSUE TITLE
What to do about events removed from createEvent that have no constructors?

### ISSUE THREAD

**Issue by ayg** [whatwg/dom#445]
Some events are not currently supported in createEvent, or we want to remove support, but they also have no constructors.  Generally we allow authors to create events that the browser fires (although I don't know why).  What should we do about these?  Leave them in createEvent?  Add constructors?

Examples: BeforeUnloadEvent, TimeEvent.

Related to #362.

@smaug---- @foolip @domenic

**Comment by foolip** [comment]
I have no strong opinion on this.

**Comment by annevk** [comment]
Where is TimeEvent defined?

**Comment by ayg** [comment]
It's supposed to be to do with SMIL.  I haven't tracked it down in the standard yet, so it might not really exist, in which case Gecko should probably drop support entirely.  BeforeUnloadEvent still holds, and perhaps others.  (I'll mention them here as I find them.)

**Comment by ayg** [comment]
TimeEvent is in the [SMIL spec](https://www.w3.org/TR/smil/smil-timing.html).

**Comment by ayg** [comment]
I think that any event types that are in actively-developed specs should have constructors defined to match other events in the platform.  If that's too much trouble, they can be left in createEvent.  E.g., I don't know if anyone wants to bother getting errata issued for SMIL 3.0 to get a constructor put in the spec there, so if no wants to, I think that should be added to createEvent officially, assuming we consider SMIL 3.0 to be part of the platform.

**Comment by ayg** [comment]
I filed whatwg/html#2574 for BeforeUnloadEvent, and tried sending a message to www-smil for TimeEvent (although I don't know if it got through).

**Comment by ayg** [comment]
https://lists.w3.org/Archives/Public/www-smil/2017AprJun/0000.html

**Comment by ayg** [comment]
Crickets on TimeEvent.  Does anyone know if it makes sense to update SMIL 3.0 here, or what should we do?  @jwatt, @longsonr?

**Comment by foolip** [comment]
Chromium doesn't have TimeEvent, FWIW.

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1445163 on TimeEvent as only Firefox supports it. We can keep https://github.com/whatwg/html/issues/2574 for BeforeUnloadEvent. I don't think we should extend `document.createEvent()` so closing this.
