### ISSUE TITLE
Web reality: DOMTokenList's toggle() cannot always update the corresponding attribute

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#451]
@smaug---- mentioned https://bugzilla.mozilla.org/show_bug.cgi?id=1360230 in #444. Which is a little sad, but also fine to fix.

So we basically want to go back to only invoking the "update steps" when we mutate the set first. Unclear if we should do the same for `replace()`. Given this is a special case it probably warrants a note as well.

**Comment by the8472** [comment]
Another option might be normalizing the value and only skipping the update if the normalized value matches the already present attribute. That avoids the particular issue with observer recursion since the recursion would terminate once the normalized value equals the attribute

**Comment by annevk** [comment]
I think I'd rather just restore the old behavior for this method. If you only use `DOMTokenList` for manipulation there won't be a difference with your solution.

**Comment by annevk** [comment]
@smaug---- I created a PR for this problem. Do you know what the current state of testing is? Since tests that land in Mozilla are not always synchronized directly with web-platform-tests, it's a little tricky to determine what I should update and when.

**Comment by smaug----** [comment]
Hmm, so I backed out Aryeh's patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1359780
https://reviewboard.mozilla.org/r/133932/diff/3#index_header should show the relevant tests, I think.

**Comment by ArkadiuszMichalski** [comment]
But the8472 solution would not be better? For  [update steps](https://dom.spec.whatwg.org/#concept-dtl-update) we can check if [ordered set parser](https://dom.spec.whatwg.org/#concept-ordered-set-parser) is the same ass attr.value, and if yes then return, if no then set attr.value. This will cover all other methods that which unnecessarily set the attribute again (and potentially invoke an observer).

**Comment by annevk** [comment]
It doesn't seem consistent with how attr.value = attr.value normally works. No-ops in the DOM still trigger listeners.

**Comment by annevk** [comment]
@smaug---- you didn't want to keep the new behavior for `replace()`?

**Comment by smaug----** [comment]
I didn't think that at all. I just saw breakage and since the patch author went offline backed out the whole patch asap.

**Comment by ayg** [comment]
Where does it say in the bug report that it's not web-compatible?  Am I missing something?

**Comment by ayg** [comment]
Never mind, I see now.  Oh well, not a big deal.

**Comment by ayg** [comment]
@annevk @smaug---- Do we have a definite decision on whether we want to change replace() back too?  I'd prefer not, but once we have inconsistency anyway it's not as big a deal.

**Comment by smaug----** [comment]
What is the behavior in browsers?

**Comment by ayg** [comment]
https://jsfiddle.net/4d8ja9yw/1/

Firefox outputs 1, like the old spec, not normalizing on a no-op.  Edge and Chrome don't appear to support replace() at all.  I wasn't able to test in WebKit right now (have to recompile it).

**Comment by smaug----** [comment]
If only Firefox supports it now, and has the behavior of the old spec, I think that is the model to have in the current spec too.

**Comment by annevk** [comment]
Safari TP also no-ops for that test.

**Comment by ayg** [comment]
But for this, Firefox outputs 1, which means that `replace("a", "a")` does run the update steps if "a" is in the token list, even though it's a no-op: https://jsfiddle.net/4d8ja9yw/2/  What does WebKit do?  (I'm still trying to compile WebKit myself, but I can't find non-ancient binaries for Linux, so until I succeed I can't test it.)

**Comment by annevk** [comment]
Sorry, I was unclear. Safari TP outputs 1 for both your fiddles.

**Comment by ayg** [comment]
Then we want to spec that if you replace a value that's not in the token set, it doesn't update, but if you replace a value in the token set with itself, it does update.

I'm a bit sad that if we change this back there will be no simple and foolproof way to update the attribute without changing its values.  You'd have to do something like

```javascript
if (list.length) {
  list.add(list[0]);
} else {
  list = "";
}
```
or
```javascript
list.remove("i-hope-this-value-isnt-ever-actually-in-the-list");
```
Or just update the values twice, like
```javascript
list.toggle("a");
list.toggle("a");
```
If `replace()` did update the value unconditionally, you could do simply `replace("a", "a")`.

But I guess it's not worth going against existing implementations.

**Comment by annevk** [comment]
Yeah, it's probably not worth it given the compatibility fallout seen thus far. I'll update the PR, but as I mentioned elsewhere it might take a while to land due to whatwg.org infrastructure issues.
