### ISSUE TITLE
To investigate: do error events bubble to window?

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#455]
@GeorgNeis found during some testing that error events on script elements (from fetch errors) do not bubble to the window.

This makes some sense, as window already has an error event with a different meaning.

DOM already blocks the bubbling of load events to window:

> A document’s get the parent algorithm, given an event, returns null if event’s type attribute value is "load" or document does not have a browsing context, and the document’s relevant global object otherwise. 

This issue is a reminder to myself to figure out what's going on here, and write a bunch of web platform tests. In particular it seems at least plausible that any of the following could be true:

- Something else was confusing the test results, and this is all a false alarm
- Bubbling is blocked based on the event's type being "error"
- Bubbling is blocked based on the event's type being "error" and its interface not being ErrorEvent
- Bubbling is blocked based on some of the above plus isTrusted being true
- "error" events on script elements don't bubble after all
- "error" events on a variety of elements don't bubble after all
- Bubbling gets blocked at some earlier stage, e.g. it never reaches body, or it never reaches document
- Capture also gets interfered with somehow

**Comment by annevk** [comment]
cc @smaug---- who might be able to just tell you.

**Comment by smaug----** [comment]
error event isn't special. It just isn't bubbling event. Using capturing listener in window should be able to catch them.

**Comment by domenic** [comment]
Oh, duh. I forgot that the defaults were non-bubbling for "fire an event". False alarm.
