### ISSUE TITLE
"The value attribute’s getter must return the va..."

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#456]
https://dom.spec.whatwg.org/commit-snapshots/b2f429273e23d22acbcbdcdad46cd440ec131098/#interface-attr

> The value attribute’s getter must return the value\.

I am not convinced this part of the spec is right. It makes it look like Attr.value always returns the attribute's value. However, all browsers will return the owner element's attribute value if the Attr Node has an owner element.

It is unclear to me that the specification matches browsers.

**Comment by annevk** [comment]
I don't follow what you're saying. An attribute can only belong to one element and has a name and a value. An element itself doesn't have an attribute value. What is wrong here? (Although I'd probably rephrase it as "return the context object's value" today.

**Comment by cdumez** [comment]
Ok. I think I got confused. I thought an Element could have an attribute value without necessarily having an Attr node associated. This is how things are implemented in WebKit (Attr nodes are created lazily).

**Comment by annevk** [comment]
Ah yeah, that makes sense. But I think that goes for most nodes. I don't think any browser creates the JavaScript object unless asked.
