### ISSUE TITLE
DOMTokenList.remove() can add an attribute

### ISSUE THREAD

**Issue by tkent-google** [whatwg/dom#462]
Specification: https://dom.spec.whatwg.org/#dom-domtokenlist-remove
WPT: http://w3c-test.org/dom/nodes/Element-classlist.html

Should ```remove()``` really add an empty attribute?

According to the current specification, the following code should show ```""``` (empty string).

```
var c = document.createElement('div');
c.classList.remove('a');
alert('"' + c.getAttribute('class') + '"');
```

Safari TP works so.  

The WPT test contains some sub-tests which don't conform to the specification. e.g.  "classList.remove("a") with attribute value null (HTML node)"
These sub-tests assume ```remove()``` never adds ```class``` attribute, and Firefox nightly, Chrome, and Edge don't add an empty attribute.

**Comment by annevk** [comment]
@cdumez thoughts?

It seems that would require changing the update steps to have extra conditionals or make `remove()` a no-op if there's no attribute...

**Comment by cdumez** [comment]
I agree the behavior spec'd is odd and do not object to align WebKit with other browser engines here.

**Comment by tkent-google** [comment]
Also, ```replace('non-existent-token', 'foo')``` and ```toggle('non-existent-token', false)``` should add an empty attribute according to the current specification. Neither of Safari nor Firefox adds it.

**Comment by annevk** [comment]
@tkent-google I think #452 fixes that for toggle. See also #451.

I don't think I'll be able to fix this and get all the tests updated before I leave. If you could write down exactly how you'd like the specification to change perhaps you can reach agreement in this issue and then I can update it when I get back or you can maybe work with @domenic to get tests and the specification updated.

**Comment by tkent-google** [comment]
Another related issue about ```replace()```.

```
var c = document.createElement('div');
c.className = 'a a a b';
c.classList.replace('c', 'd');
alert('"' + c.getAttribute('class') + '"');
```

Both of Safari TP and Firefox nightly shows "a a a b" and Element-classlist.html expects it though it should be "a b" according to the DOM standard.

**Comment by ayg** [comment]
I think no tests actually need changing, right?  Just a spec update to make remove() a no-op if the class isn't present?

@tkent-google That was changed in #444.  We have to decide if we want to change it back because of #451.  The tests were not updated to match the new spec because I submitted them upstream three-odd months ago and the patch got backed out because of #451 and so the tests never got downstreamed.

**Comment by ayg** [comment]
I think this is the right fix.

**Comment by ayg** [comment]
The test update tests force-toggle instead of just remove.

**Comment by tkent-google** [comment]
The current change of #488 resolves only ```remove()``` and ```toggle()``` cases, but doesn't resolve the case of https://github.com/whatwg/dom/issues/462#issuecomment-305378133. If we resolve all of them, I think we need to update 'Run the update steps.' in each of operations to 'Run the update steps if token set was updated in the prior steps'

> I think no tests actually need changing, right? 

Right. I think the test has the desired behavior.

**Comment by ayg** [comment]
That would change the behavior of `remove()` to also not update a _non_-empty attribute in the case where nothing was actually removed, whereas AFAIK we do want it updated.  So I think we have to make it two separate changes here.

**Comment by cdumez** [comment]
Aligning WebKit via https://bugs.webkit.org/show_bug.cgi?id=178280.
