### ISSUE TITLE
Need some kind of specifying target offset?

### ISSUE THREAD

**Issue by jimmywarting** [whatwg/dom#473]
Just encounter the fixed header anchor problem yet again, seems like a very common problem

https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header

Isn't it time we introduce some smarter way of telling the browser that we have a fixed header and it needs to compensate anchor link that it shouldn't scroll too much?

I have no idea of how to do it but i got some few ideas in mind

Globally, applies to all anchors
`<meta name="anchor-offset" content="100px">`
`window.anchorOffset = "100px"`

Individually, gives more fin control
`<h1 id="deeplink" offset="100">title</h1>`

css solution
`h1 {anchor-offset: 100px}`

---

sry if i posted this in the wrong repo, don't know where it belongs

**Comment by annevk** [comment]
I think https://github.com/w3c/csswg-drafts/issues/new would be the best place. In part HTML defines navigating to a fragment, but how that's displayed visually is really CSS' domain.

**Comment by annevk** [comment]
Closing this per my earlier comment and also because some time has passed without reply. Feel free to leave a further comment if this needs to be reopened for some reason. Thanks!
