### ISSUE TITLE
"If callback is null, then return."

### ISSUE THREAD

**Issue by guest271314** [whatwg/dom#480]
https://dom.spec.whatwg.org/commit-snapshots/fba2caf4be29c30e7e03010d5fce240a729e0bed/#interface-eventtarget

> 2. If callback is null, then return\.

[`window.addEventListener('load', undefined);`](https://stackoverflow.com/questions/45157031/cannot-determine-type-of-undefined)

Should `undefined` also be included at 2.?

> 2. If callback is null or undefined, then return\.

**Comment by annevk** [comment]
That's covered by IDL. See https://heycam.github.io/webidl/#es-nullable-type.
