### ISSUE TITLE
Make it easier to dispatch custom events

### ISSUE THREAD

**Issue by jonathantneal** [whatwg/dom#483]
It would be easier to read and write the dispatching of Custom Events if they could be created within `dispatchEvent`.

```
cancelled = !EventTarget.dispatchEvent((Event or DOMString), customEventInit);
```

### Example:

Clicking a button fires a custom `filter:results` event from a container:

```js
buttonEl.addEventListener('click', () => {
  /* maybe prepare stuff */

  containerEl.dispatchEvent('filter:results', {
    bubbles: true,
    detail: filterEl.value
  });
});
```

This small change makes a very readable difference for me. It would otherwise be:

```js
buttonEl.addEventListener('click', () => {
  /* maybe prepare stuff */

  containerEl.dispatchEvent(new CustomEvent('filter:results', {
    bubbles: true,
    detail: filterEl.value
  }));
});
```

I struggle to quantify this, but it gets difficult for my eyes to follow functions directly within other functions, namely due to the touching `))`. To resolve this right now, I’ll write `dispatchEvent` and `CustomEvent` on separate lines, gaining readability between the functions and constructors, but sacrificing the “paintstroke” readability of the actual “thing” I’m trying to accomplish.

I’ll completely understand if you find this request silly and my eyesight to be the real problem here. I earnestly felt like there really might be a advantage to many others if we ditched the constructor when dispatching custom events.

**Comment by annevk** [comment]
It doesn't work, since you need to know the class to know about the associated dictionary and you can't infer the class from the event name.

**Comment by jonathantneal** [comment]
@annevk, I thought I’ve specified the class every time, Custom Events. Is that not right? Could you teach me a little here if there’s something else?

**Comment by annevk** [comment]
Oh, it would always be a `CustomEvent`? I don't think that's really worth it then. A big use case for custom events is testing code paths and you need all kinds of event classes to do that.

**Comment by jonathantneal** [comment]
Oh! I must not be developing as folks expect. I use custom events all the time in components I write, whether it’s a carousel firing a `changeslide` event, or a global menu firing an `openmenu` event. I use `CustomEvent` for all of these things. I don’t use other classes because I am not pretending to be other kinds of event, like `MouseEvent`, `KeyboardEvent`, etc.

What you’re saying about testing code paths seems like a different use case. Is what I’m doing rare / wrong / not best practice?

**Comment by annevk** [comment]
It seems fine to me. I just wasn't expecting sole usage of `CustomEvent` objects. We can leave this open for a bit to see if there's more interest. My feeling at the moment is that the current syntax is convenient enough. You could always use a variable if you don't want all the nesting.

**Comment by domenic** [comment]
I also use lots of different event objects and subclasses. My default is Event, as I rarely need an extra detail property. ProgressEvent is also common.

**Comment by victornpb** [comment]
I feel like every JavaScript API is like that, not meant to be convenient to use, and conceived to be easy to implement and not convenient to use. I admit this has slowly moving on the past years.

So this being said, I'm ok with how it is now. Because any other API could be rewritten to similar cases like that. I've seen so many libraries that just wrap stuff, that I think that would be the case for this scenario.

**Comment by annevk** [comment]
FWIW, we do want easy-to-use APIs, but as I mentioned above you lose a lot with the proposed API. It would only be convenient if you're interested in just `CustomEvent`. So it's not easy-to-use-vs-easy-to-implement. Rather it's a tradeoff between flexibility and posing restrictions on consumers. And in that case we do tend to chose to not cut off functionality.

**Comment by victornpb** [comment]
IMO, I don't think the current implementation is bad and the proposal is merely esthetic, and not worth making the current implementation more complex. Also detect this feature would not be a trivial `(Feature in constructor)` I guess...

**Comment by jonathantneal** [comment]
Thanks for the feedback. I’m now convinced this is a bad solution to a real problem worth solving, event handling. I’m closing this, and I’m grateful to everyone who responded and anyone who entertained it.
