### ISSUE TITLE
"Unset the active flag. "

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#494]
https://dom.spec.whatwg.org/commit-snapshots/cd3bcaeea40b4b9355ae7be3a5799813faa492fc/#traversal

> Unset the active flag\. 

As written, this step will not be reached if the previous one throws an exception. However, as can be seen by e.g. http://w3c-test.org/html/syntax/parsing/template/creating-an-element-for-the-token/template-owner-document.html, browsers put it in a kind of "finally" block. The spec should too.

**Comment by annevk** [comment]
Did you mean to link to a different test?

Do you have anything better than adding "If an exception is thrown, then unset the active flag and rethrow the exception." to the end of step 6?

**Comment by annevk** [comment]
cc @ayg

**Comment by ayg** [comment]
That wording sounds good.  We should test this, too.

**Comment by annevk** [comment]
It sounds like it might already be tested, but @domenic just pasted the wrong link in.

**Comment by ayg** [comment]
I actually don't see any tests at all for the active flag, although I thought we had them.

**Comment by domenic** [comment]
Sorry, I meant https://github.com/w3c/web-platform-tests/blob/master/dom/traversal/NodeIterator.html#L55. @ayg added the tests a while ago in https://github.com/w3c/web-platform-tests/commit/b752fe789b9382fefecaaf5b45ab01c599323769.
