### ISSUE TITLE
NodeIterator pre-removing steps seem incorrect

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#496]
https://dom.spec.whatwg.org/commit-snapshots/cd3bcaeea40b4b9355ae7be3a5799813faa492fc/#interface-nodeiterator

Consider the scenario at https://jsbin.com/zugoyutice/edit?html,console,output , in particular the removeChild() call. (Derived from https://github.com/tmpvar/jsdom/blob/3743b423cb45657401eef3475a07fd99e015b2e2/test/to-port-to-wpts/node-iterator.js#L429 , for the record)

toBeRemovedNode = referenceNode = root = the span

1. toBeRemovedNode is an inclusive ancestor of referenceNode, so step 1 passes
2. pointerBeforeReferenceNode = true (since it starts that way)
   1. next = null; there is nothing that is not an inclusive descendant of toBeRemovedNode but is an inclusive descendant of root
   2. Do nothing
   3. **Set pointerBeforeReferenceNode to false**
3. **Set referenceNode to the body**

However the test shows that pointerBeforeReferenceNode and referenceNode do not change.

This appears to have regressed in https://github.com/whatwg/dom/commit/259775f14d55b21de16cbb0a3c625741fd54aa0b, as jsdom has an implementation based on the older removing-steps-based algorithm, and updating broke <del>a bunch</del><ins>one, after I fixed other bugs of ours :)</ins> of our (to-be-upstreamed) tests.

**Comment by domenic** [comment]
A fix that seems to pass my test suite is that step 1 becomes

> If toBeRemovedNode is not an inclusive ancestor of the referenceNode attribute value, or toBeRemovedNode is equal to nodeIterator's root, then return.

**Comment by annevk** [comment]
That also matches https://searchfox.org/mozilla-central/source/dom/base/NodeIterator.cpp#72.
