### ISSUE TITLE
Rename Elements to ElementList

### ISSUE THREAD

**Issue by esprehn** [whatwg/dom#50]
"Elements" is super hard to search for (ex. web search don't find this), and is not clear what it does. It should also be constructible and writing new Elements([...]) is weird, new ElementList([....]) makes sense.

https://dom.spec.whatwg.org/#element-collections

**Comment by domenic** [comment]
ElementArray if anything. But I prefer Elements.

**Comment by annevk** [comment]
What is the problem with it being hard to search for? Aren't lots of APIs hard to search for? E.g. `Text` or `fetch` or `window`?

**Comment by rwaldron** [comment]
> But I prefer Elements.

Agreed.

**Comment by annevk** [comment]
I guess the only thing to consider is whether we maybe want to name it Nodes, given https://www.w3.org/Bugs/Public/show_bug.cgi?id=27688, but I suppose we could also just add Nodes when the need for such a thing arises.

**Comment by annevk** [comment]
Actually, we'd just use a simple array in that case since there would be no need for these methods.
