### ISSUE TITLE
ChildNode.replaceWith specification clarification

### ISSUE THREAD

**Issue by caub** [whatwg/dom#502]
I'm trying to implement https://dom.spec.whatwg.org/#dom-childnode-replacewith in [jsdom](https://github.com/tmpvar/jsdom/pull/1947)

It starts with:
1. Let *parent* be context object’s parent.

and later:

5. If context object’s parent is *parent*, ...

Isn't there an issue here? it seems the 5. is always true, or I'm not understanding it well

**Comment by domenic** [comment]
The note is pretty clear right after this:

> Context object could have been inserted into node.

**Comment by caub** [comment]
Ah thanks I see
