### ISSUE TITLE
Move EventHandler to DOM spec

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/dom#509]
I wonder if we could migrate `EventHandler` from the HTML Spec to the DOM spec? The advantage is to do with testing. If you look at [this test](https://github.com/w3c/web-platform-tests/pull/7272/files#diff-1384d9a594eb14b65ee02bce64f8cc7dR18), you can see that it Imports `dom.idl`, but in order to also test `EventHandler` I would need to import all of HTML (which seems like way overkill - as it would add a ton of cognitive overhead to what we are actually interested in testing...).

You can also see a lot of instances in the WPT of people working around this if you:

```BASH
git grep "interface EventHandler"
``` 

In the web platform tests repo. 

The above is not great. Particularly because we see a few instances of it being added to `idlArray.add_untested_idls()`. 

Ideally, what we should be seeing in WPT, is everyone importing `dom.idl` and then layering their IDL on top.

**Comment by annevk** [comment]
Maybe just divide `html.idl` then? I don't really see how it makes sense for DOM to define event handler attributes.

**Comment by marcoscaceres** [comment]
Yeah, that might be cleaner... and it would probably break a ton of specs.

**Comment by annevk** [comment]
That's a good point, migrating it would be a ton of work.
