### ISSUE TITLE
Event.target should return null after dispatch is complete, when stopped at ShadowRoot

### ISSUE THREAD

**Issue by TakayoshiKochi** [whatwg/dom#511]
https://dom.spec.whatwg.org/#dispatching-events doesn't specify any operation on `event.target` after dispatching is done (step 14 and after). This leaves `event.taget` as what it was when the event was last set in step 13.1.

This, in turn, means that when the event is stopped at shadow root, and the reference to the event is stored somewhere in the event handler, the last `event.target` would sort of leak after dispatch is complete.

Would like to reset `event.target` to `null` when the event stopped at shadow root.

**Comment by annevk** [comment]
Good catch. That seems like the correct solution. Always doing it seems too risky.

cc @whatwg/components

**Comment by TakayoshiKochi** [comment]
We noticed that we missed `event.relatedTarget` and should be nullified when it's possible to leak shadow tree internals.  Let me update #513.
