### ISSUE TITLE
Expose Event, EventTarget to AudioWorklet

### ISSUE THREAD

**Issue by hoch** [whatwg/dom#515]
cc: @domenic @annevk 

[Related issue from Web Audio API](https://github.com/WebAudio/web-audio-api/issues/1266#issuecomment-311513537)

The proposed change is:
```webidl
[Constructor(DOMString type, optional EventInit eventInitDict),
 Exposed=(Window,Worker,AudioWorklet)]
interface Event { ... }

[Constructor,
 Exposed=(Window,Worker,AudioWorklet)]
interface EventTarget { ... }
```

If this looks okay, I'll submit a PR shortly.

**Comment by annevk** [comment]
Looks good, thanks!
