### ISSUE TITLE
Question about `attachShadow` to HTMLUnknownElement

### ISSUE THREAD

**Issue by baocang** [whatwg/dom#517]
I create a element with
```javascript
var toolbar = document.createElement('toolbar')
```
 then call

```javascript
toolbar.attachShadow({mode: 'open'})
```
It throws
```
VM4423:1 Uncaught DOMException: Failed to execute 'attachShadow' on 'Element': This element does not support attachShadow at <anonymous>:1:31
```
but this works:
```javascript
toolbar.createShadowRoot()
```
I don't want to use native custom element there, because it too restrictions, but i want use ShadowDOM there?
Why ShadowDOM V1 droped the support of `HTMLUnknownElement`?

**Comment by annevk** [comment]
To be able to add new elements to the language for which we need builtin shadow trees. If you name it `my-toolbar` or some such it'll work.

**Comment by baocang** [comment]
I hate it! That means I needs do polyfill with ShadowDOM V1. or I need work with some thing likes XSLT.
I miss some feature of ShadowDOM V0!
And I want WebComponents more flexible.
The fortunately, I can do polyfill.
