### ISSUE TITLE
MutationObserver: observing attribute changes fires even if the value didn't change.

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#520]
If I call `setAttribute(sameValueAsBefore)` on an element, passing the same value as the attribute already has, the MutationObserver instance still register a mutation. This is my observer:

```js
const attributeChangedObserver = new MutationObserver( records => {
    console.log( ' ---------- attribute change records', records )
} )

attributeChangedObserver.observe( element, {
    attributes: true,
    attributeOldValue: true,
    attributeFilter: observedAttributes
} )
```

This seems strange, because the attribute value didn't change. Why is it this way?

CustomElement attributeChangedCallbacks behave the same way (since I guess they use the same mechanism for implementation).

Related: https://github.com/w3c/webcomponents/issues/676

**Comment by trusktr** [comment]
Related: https://github.com/w3c/webcomponents/issues/676

**Comment by annevk** [comment]
You'd have to do some research and mailing list spelunking. I'm pretty sure this was discussed. We're not going to change at this point as it's interoperable.

**Comment by mkay581** [comment]
@trusktr can you post any discussions you find here for other folks that are looking, like myself? 😁

**Comment by trusktr** [comment]
I definitely don't feel like spending time spelunking for this.

There's always the possibility of `v2`... 

... Because it's still under consideration in Edge. :)

**Comment by trusktr** [comment]
Oops, I meant v2 of Custom Elements. Perhaps it won't change in MutationObserver because that's not versioned.

**Comment by annevk** [comment]
Custom elements isn't versioned either. v2 is just a reference to features we might introduce after shipping an initial version which everyone considers good enough (v1).

**Comment by smaug----** [comment]
MutationObserver was explicitly designed to work that way, but I can't now recall the reasoning.
I think it might have been something along the lines that for consistency every setAttribute call should create a record. Conceptually there is after all a mutation: there is an old value replaced with a new one, and whether or not they are the same doesn't really matter.
And Custom elements should work the same way as MutationObserver.

**Comment by mkay581** [comment]
Yeah I can imagine that it may be good to do this for debugging, logging purposes, etc. Thanks

**Comment by intervalia** [comment]
I always thought that the MutationObserver was supposed to get called when either setAttribute or removeAttribute was called no matter what values were set. This was to allow the code to act upon the calls and not just on a value change. There are some, rare, occasions when the dev might need to know that the same value was applied. Maybe to refetch data from the server, maybe to redraw with recent values, etc.
