### ISSUE TITLE
Attributes not ready on element construction?

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#522]
I've got a Custom Element that is used in HTML markup with an existing attribute, f.e.

```html
<some-element has="...">
</some-element>
```

and in the class definition I have this:

```js
    constructor() {
        super()

        console.log(' --- has attribute (sync)?', this.getAttribute('has')) // undefined

        Promise.resolve().then(() => {
            console.log(' --- has attribute (microtask)?', this.getAttribute('has')) // undefined
        })

        setTimeout(() => {
            console.log(' --- has attribute (macrotask)?', this.getAttribute('has')) // works!
        }, 0)
    }
```

As you can see, I am not able to see existing attribute during construction, which seems really strange because the element already has attributes in the HTML markup, so I expected it to have attributes after calling `super()`.

Furthermore, I find it super strange that I have to defer to a _macro_ task rather than a _micro_ task to detect initial attributes.

Is this as expected?

**Comment by intervalia** [comment]
https://w3c.github.io/webcomponents/spec/custom/#custom-element-conformance

When authoring custom element constructors, authors are bound by the following conformance requirements:

- A parameter-less call to super() must be the first statement in the constructor body, to establish the correct prototype chain and this value before any further code is run.
- A return statement must not appear anywhere inside the constructor body, unless it is a simple early-return (return or return this).
- The constructor must not use the document.write() or document.open() methods.
- The element's attributes and children must not be inspected, as in the non-upgrade case none will be present, and relying on upgrades makes the element less usable.
- The element must not gain any attributes or children, as this violates the expectations of consumers who use the createElement or createElementNS methods.
- In general, work should be deferred to connectedCallback as much as possible—especially work involving fetching resources or rendering. However, note that connectedCallback can be called more than once, so any initialization work that is truly one-time will need a guard to prevent it from running twice.
- In general, the constructor should be used to set up initial state and default values, and to set up event listeners and possibly a shadow root.

Several of these requirements are checked during element creation, either directly or indirectly, and failing to follow them will result in a custom element that cannot be instantiated by the parser or DOM APIs.

**Comment by trusktr** [comment]
> the constructor should be used to set up initial state and default values, and to set up event listeners and possibly a shadow root.

That one sort of conflicts with `The element's attributes and children must not be inspected`. I would consider default attribute values as default values. So for now, I am using a MutationObserver (the one in custom-attributes) to wait for attributes and, if the one that I want to have a default value doesn't exist, to create the attribute with default values so that default Custom Attribute effects can be triggered.

As long as I properly document this in my Custom Element documentation, I don't really see this sort of thing as a problem. F.e.,

> If you don't supply the `foo` attribute, it will have a default value of `"bar"`.

In my case, I've got Custom Element for rendering WebGL (similar to A-Frame, but more general purpose not specifically for AR/VR). We can write this:

```html
<i-scene experimental-webgl="true">
    <i-mesh has="sphere-geometry basic-material" receiveShadow="true" size="5" position="..." rotation="...">
    </i-mesh>
<i-scene>
```

but in order to make things simpler to get started with, without having to figure out all the things that are required to have something appear on the screen, the user can write

```html
<i-scene experimental-webgl="true">
    <i-mesh position="..." rotation="...">
    </i-mesh>
<i-scene>
```

in which case the `has=""` attribute will be created with a default value of `"box-geometry phong-material"` and will be lit by default lighting. Element inspector will show `has="box-geometry phong-material"`.

The `has` attribute can be changed later without any problem. 

Sidenote: Think of `has` as an "entity component system" but I'm caling it "Element Behaviors", as [detailed here with examples](https://github.com/w3c/webcomponents/issues/662#issuecomment-327945806). Each listed behavior is like a Custom Element, with similarly-named callbacks that receive the element instance. These behaviors react to attribute changes. It's much much nicer than the troubled `is=""` attribute, and allows for more than one class to be associated with an element (like jQuery allows too, but imperatively rather than declaratively).

**Comment by domenic** [comment]
We can make it clearer that these are not supposed to be attribute values.

Like native elements, custom elements should not sprout "default" attributes the moment they are created. The user wrote `<x-tag>`, not `<x-tag foo="bar">`. Going against the user's wishes is not a pattern we're interested in supporting, and we'll try to stop that, as you've seen.

They should instead interpret the absence of an attribute as triggering the default behavior.

**Comment by trusktr** [comment]
> They should instead interpret the absence of an attribute as triggering the default behavior.

That's true, I'll think about that, though currently I think it's cleaner to see (f.e. in the Inspector) the default values so it's easy to learn from. And it doesn't harm how anything like React/Vue/Angular works. Do you know any ways it might harm other code somewhere?

Seems like well-documented elements will probably not have a problem as long as they don't morph the HTML structure because React/Vue/Angular they track the DOM structure, but not attribute references (they only use setAttribute to update DOM).

Plus, builtin elements already do morph DOM, f.e. `<table>`.

**Comment by domenic** [comment]
No built-in elements morph the DOM. You may be thinking of the HTML parsing algorithm, but that's not related.

**Comment by trusktr** [comment]
Okay, maybe it's parsing.

```js
const d = document.createElement('div')
d.innerHTML = `
  <table>
    <tr><div>foo</div><td></td></tr>
  </table>
`
d.innerHTML
```

output:

```
"
  <div>foo</div><table>
    <tbody><tr><td></td></tr>
  </tbody></table>
"
```

That's much worse than what I'm doing here.

But you're right, I can achieve this without setting an attribute value, but what problems would it cause if I do?

**Comment by annevk** [comment]
If you rely on the attribute being there your element won't work well if I create it imperatively.

**Comment by trusktr** [comment]
That's what I was going to test next. But, I think it will work fine. If an attribute is already detected to exist, then it doesn't set the default value. If the Attribute is detected not to exist then it sets the default value. So I don't think it will break imperatively.

You will do one of the following

1. Construct the element and never set the attribute.
   - The default value will be set in a future macrotask.
1. Construct the element and synchronously set the attribute.
   - in a future macrotask this is detected and no default value is set.
1. Construct the element and asynchronously set the attribute in a following microtask.
   - in a future macrotask this is detected and no default value is set.
1. Construct the element and asynchronously set the attribute in a future macrotask.
   - if my future macrotask runs before yours no default attribute is detected so one is set, then your task sets the attribute later and my `attributeChangedCallback` handles this fine, destroying previous state and setting new state.
   - if my future macrotask runs after yours, then then your attribute is detected and no default is set.

I'm using a simple conditional check to see if the attribute exists, if not I set it. And the attributeChangedCallbak otherwise handles everything fine.

**Comment by annevk** [comment]
If that works fine then the current setup works fine too.

**Comment by annevk** [comment]
Closing due to lack of follow-up.
