### ISSUE TITLE
Should we really support modifying an already dispatched event via initEvent()?

### ISSUE THREAD

**Issue by cdumez** [whatwg/dom#523]
It is currently possible (as per the DOM specification) to modify the attributes on an event (e.g. its type) after it has already been dispatched using any of the init*Event() functions.

This has been supported by Gecko for a long time I believe. WebKit and Blink have fairly recently aligned with Firefox it seems (tested via http://jsbin.com/mekobayoxu/edit?html,output).

Some of the WebKit engineers have expressed concerns about this so I thought I would start a discussion upstream about possibly changing this.

The concerns are:
1. It used to be (in WebKit/Blink) that Events were somewhat immutable after being dispatched. As a result, the page could hold on to the events and read their attributes later, without having to worry about the event changing under them.
2. It used to be (in WebKit/Blink) that Events could not be re-dispatched after being dispatched. Support such re-dispatching does not seem very useful and is a potential source of trouble because engines tend to store browser-internal properties on events (e.g. underlying platform keyboard event) and we need to be extremely careful that those are properly reset before re-dispatching.

Any thoughts?

**Comment by cdumez** [comment]
cc @weinig

**Comment by cdumez** [comment]
Also note that WebKit/Blink are fairly inconsistent in their behavior (because not all code paths have been updated to match the specification.

See http://jsbin.com/zaxugimupo/edit?html,output

WebKit / Blink: load event cannot be modified using initEvent() after it has been dispatched
Gecko: load event can be modified using initEvent() after it has been dispatched

**Comment by cdumez** [comment]
cc @tkent-google

**Comment by danyao** [comment]
@domenic

**Comment by domenic** [comment]
@tkent-google is out for this quarter; probably @hayatoito is in the best position to help here.

I don't know much about this, but aesthetically I find my intuitions agreeing with @cdumez that locking init*Event() down more is nicer.

**Comment by darinadler** [comment]
We could even consider going further and not having init*Event functions do anything when called on an event unless the event was created by calling createEvent. It’s hard to define exactly what the correct behavior would be if you received a mouse event from the browser and then called initEvent on it to change its type, for example. What should be done to browser-internal properties in that case.

I know we’d have to do some research about web compatibility if we wanted to go that far, but I think it’s worth considering.

**Comment by annevk** [comment]
I think concern 1 is invalid since script could modify Event.prototype.type as well. Concern 2 seems somewhat reasonable (although it not being clearly defined that there's a "platform internal" slot of sorts seems like a bug).

Wonder what @smaug---- thinks.

**Comment by smaug----** [comment]
I think I've seen events to be reused for different types, though could have been some Firefox only code.
And reuse isn't totally crazy idea in some games for example where one might want to avoid garbage as much as possible.
But I don't have really strong opinion on this.

**Comment by hayatoito** [comment]
I don't any strong opinion on this.

I've seen several tests (WPT and layout tests in Blink) which re-use an event object in initEvent, however, I don't see any production code which re-uses an event object, however, my experience would be limited.

> I know we’d have to do some research about web compatibility

Yup, we have to do.

**Comment by annevk** [comment]
@cdumez do you want to propose a concrete set of changes and figure out if shipping them breaks the web? Or shall we just leave this as-is?

**Comment by annevk** [comment]
Closing this due to lack of follow-up.
