### ISSUE TITLE
Element.prototype.once for event listeners

### ISSUE THREAD

**Issue by caub** [whatwg/dom#524]
Would there be a plan to introduce this shorthand, for handling an event once more easily?

```js
element.once('click', e => {
  console.log('click', e.target);
})
// vs
element.addEventListener('click', function clickHandler(e) {
  element.removeEventListener('click', clickHandler);
  console.log('click', e.target);
})
```

One issue is the naming difference with add/removeEventListener, it would be great to shorten them to .on, .off (and possibly add this to HTMLCollection/NodeList)

**Comment by inexorabletash** [comment]
It's already there:
```js
element.addEventListener('click', e => { ... }, {once: true});
```
https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions

**Comment by caub** [comment]
Ah ok thanks, sorry
