### ISSUE TITLE
"node's tree" seems to be an undefined concept

### ISSUE THREAD

**Issue by smaug----** [whatwg/dom#526]
Does node's tree mean the tree in which node is in, or does it mean the tree which is rooted by the node?

The spec just says about : "A tree is a finite hierarchical tree structure."

Then there are clarifications for "participates" or "root", but what is node's tree?

**Comment by annevk** [comment]
The tree in which node is in. The one rooted by node is the subtree. Making this more explicit is probably a good idea.

**Comment by smaug----** [comment]
Looks like node's tree is used only in couple of places when dealing with slots, so perhaps the spec could use some existing language there, like that "tree in which the node participates", if that is right.
(I'm not 100% sure about https://dom.spec.whatwg.org/#concept-node-insert 7.6. what the spec should say)

**Comment by annevk** [comment]
Yeah, an alternative might also be to pass in the root and iterate through its inclusive descendants in tree order.
