### ISSUE TITLE
Why don't we have CSS VR?

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#527]
WebVR is webgl-only technology. Why don't we give love to CSS 3D and make it possible to make VR scenes out of DOM? This article explains it better: http://keithclark.co.uk/articles/css-vr/

If I want to mix WebGL content with CSS 3D DOM content, I can do that by layering a canvas on top of DOM content and rendering both in the "same 3D space", although they are separate layers.

[For example](jsfiddle.net/trusktr/jc6j1wmf).

But when I want to take this "mixed mode" scene into VR, I can't, because WebVR doesn't let me. :(

The only way I can achieve this is if I split the web page into two parts, and render it like in the mentioned article, but I can only support devices where we stick a phone into a headset this way, but not _real_ VR like Oculus and others.

It would be awesome to be able to specify a DOM element other than canvas to render in WebVR, so that the matrices are slightly modified for each eye. Another option could be to accept two DOM trees with separate transforms (for each eye), and we are in charge of supplying the DOM content for each eye.

If not here, where is the place to get official momentum on such a project?

**Comment by annevk** [comment]
I recommend asking this in the WebVR repository. This doesn't seem related to the DOM Standard.

**Comment by annevk** [comment]
(If you have high-level questions, asking on https://wiki.whatwg.org/wiki/IRC would be appreciated. That doesn't ping the hundred or so people following this repository with something that's off-topic.)

**Comment by trusktr** [comment]
It's tricky though, because CSS and something like CSSVR is directly related to DOM (there would be no CSS if there were no DOM for it to operate on).
