### ISSUE TITLE
Use mixins in IDL definitions

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/dom#529]
[Mixins](https://heycam.github.io/webidl/#idl-interface-mixins) have been added to Web IDL to replace the [[NoInterfaceObject](https://heycam.github.io/webidl/#NoInterfaceObject)] extended attribute + `implements` statement.

See https://github.com/heycam/webidl/pull/433.

/cc @tobie

**Comment by annevk** [comment]
Does Bikeshed support them? Last I checked https://github.com/heycam/webidl/issues/450#issuecomment-336053127 that was unclear.

**Comment by tobie** [comment]
Not yet. Filing all issues this morning. Sorry for the delay.

**Comment by tobie** [comment]
It would help quite a bit if this was closed as a dup of #532 (as that what is tracked from heycam/webidl#472). Sorry for the noise.

**Comment by annevk** [comment]
That's fine with me.
