### ISSUE TITLE
Touch/Trackpad finger position

### ISSUE THREAD

**Issue by felipenmoura** [whatwg/dom#534]
Hi.
I hope this is the right place to mention this. If it is not, could you please point in the right direction?

What would it require for us to have an API to get the exact position of fingers/touches from the trackpad? I mean, touches even if not pressed, the equivalent to "mousemove" in the trackpad.

For example, let's say someone wants to write a WebApp in which you could sign something, or simply use a (good) handwriting feature instead of pressing/clicking.

Example:
Let's say I draw an "A" in the left side of my trackpad, then I draw a "B" in the right side of the trackpad. On the screen, they will overlap, with both letters in the same place.
That's why I'm talking about the touch position **in the trackpad**.

This is a feature that is supported for native apps...I wonder why shouldn't it be for the web :)
As I can see, the OS passes this info down to native applications (I saw some Java and Objective C doing that), so, browsers could be able to use this info and provide an API for that.

Thanks.

**Comment by annevk** [comment]
Heya, I'm not sure but https://github.com/w3c/pointerevents or https://github.com/w3c/uievents would be good places to start I think. Hope that helps. If they don't help you out, let me know and I'll start poking some folks.
