### ISSUE TITLE
Upgrade addedNodes and removedNodes to FrozenArray?

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#54]
It'd be great if we could use normal array things on them.

**Comment by sicking** [comment]
We might need to solve the lack of .item() first :(

Once we do, a whole host of interfaces can probably be converted to real arrays (or subclasses thereof)

**Comment by domenic** [comment]
Ah right :(.

I am at least very hopeful that nobody is using .item() on MutationObserver properties, since it is new enough and rare enough that those item()-users probably haven't gotten to it. So I think if someone was up for trying this, they should. @foolip? :)

**Comment by sicking** [comment]
There's definitely some uses out there. I'll leave it to others to judge if there's enough that breakage would be a problem.

https://www.google.com/search?q=addedNodes.item

**Comment by domenic** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by foolip** [comment]
For some CSS and TextTrack *List interfaces I added use counters for the `item()` method and some of them have had negligible usage, but this is `NodeList`, used all over the place, and some of them are even live...

Because of the live stuff, the chances of replacing `NodeList` with arrays entirely seem pretty slim, but it could certainly work in specific contexts. Almost all of them are return values from functions though, only these two and `Node.childNodes` are as attributes, if that makes any kind of difference.

**Comment by foolip** [comment]
I think we just won't be able to get rid of many *List interfaces unless we come up with a good way of adding things like `item()` to the arrays. There is `[LegacyArrayClass]`, but as the name suggests that's no longer in vogue. Implemented as JS it would be trivial&mdash;just set `array.item = function (n) { return this[n]; }` before freezing it, not sure if this is a serious option or not. (It would move `item` from the prototype to the object, but that's pretty likely to be web compatible.)

**Comment by domenic** [comment]
Right, I guess I was thinking some kind of use counter for `item()` called on `addedNodes` and `removedNodes` specifically. But, as @sicking says in IRC, maybe a better time investment to just work on a subclass with item() than trying to wack-a-mole item() usages everywhere.

I agree that in the general case we're not going to be able to kill NodeList.

**Comment by foolip** [comment]
For use counters of that sort you can take inspiration from `DOMStringList` in Blink, where @inexorabletash added some tracking to see in which contexts `DOMStringList` can be killed, because there is still hope that it can be killed entirely.

**Comment by annevk** [comment]
I'm going to close this. Once we have subclassing in browsers we can go through all the various cases that could maybe be replaced and do it and file clear issues with the new IDL and processing model. Until that time I'm not sure it's worth tracking these individually.
