### ISSUE TITLE
"A slotable has an associated name" should read slot instead of name

### ISSUE THREAD

**Issue by juliandescottes** [whatwg/dom#563]
https://dom.spec.whatwg.org/commit-snapshots/676fcbe6f1f9a3acab9e47aa6425715a818826a0/#light-tree-slotables

> A slotable has an associated name \(a string\)\. Unless stated otherwise it is the empty string\.

Should this read "A slotable has an associated slot [...]" rather than "name" ? Name is also used several times in the attribute change steps (eg "then set element’s name to the empty string."), where I believe it should also be "slot". I can submit a PR if this is a valid issue.

**Comment by annevk** [comment]
No, a slotable can be a slot, it doesn't have one associated with it. The "superglobal" `slot` attribute sets the name of a slotable.

We should perhaps have some more examples around this.
```
<div id=host>
 <p id=slotable1 slot=hi>Example
 <p id=slotable2>Elsewhere
</div>
<script>
const sr = document.getElementById('host').attachShadow({ mode: "closed" });
sr.appendChild(document.createElement("slot"));
const slot = sr.appendChild(document.createElement("slot"));
slot.name = "hi";
</script>
```
(`id=host` also contains some other slotables, the text nodes surrounding the paragraphs.)

**Comment by juliandescottes** [comment]
@annevk thanks for the answer. 

I now understand that the "slot" attribute of a slotable sets the slotable "name". Everywhere else in the document, a slotable's "name" refers to what is set in the "slot" attribute, so everything is consistent. I was just confused that an attribute named "slot" could set something called a "name" and assumed this was an error.

Not sure more examples are needed here. If a slotable's name was referred to as "slotName" instead of "name", it would have been easier to understand for me but I am not used to read specs. 

Closing this, thanks for taking the time to answer!
