### ISSUE TITLE
`cloneNode` should preserve element prototype

### ISSUE THREAD

**Issue by bigopon** [whatwg/dom#565]
At the moment `cloneNode` acts like creating new element with the same name and then recursively copying attributes / chidlren from source to new target. This doesn't live up to its meaning as prototype of the cloned node is not preserved.

Test:

```js
const customProto = Object.create(HTMLElement.prototype, {
  value: {
    set(v) { this._value = v; },
    get() { this._v; }
  }
});

const a = document.createElement('a');
Object.setPrototypeOf(a, customProto);

const b = a.cloneNode(true /* This doesn't matter */);
customProto.isPrototypeOf(b) === false; // <-- true
```

Tests - clone node preserving prototype:

* [x] Chrome
* [ ] IE11
* [ ] Firefox
* [ ] Edge

Edit: Maybe it could take a second arguments, that is when strictly equals `true`, will also preserve the prototype

**Comment by annevk** [comment]
Heya, thanks for your report.

Given how https://dom.spec.whatwg.org/#concept-node-clone is defined Chrome is definitely wrong here. I'll add some tests and file a Chrome bug.

If you really think this needs to be a feature I'd prefer tracking that in a new bug. But the main way that feature would be defined would be as if doing a setPrototypeOf call afterwards so it'd be interesting to know if there are many libraries out there that have that kind of behavior.

**Comment by annevk** [comment]
I cannot reproduce this in Chrome so I ended up not filing a bug.

**Comment by bigopon** [comment]
Hi thanks for checking. I was testing with Chrome and definitely saw this behavior, so I thought it was a feature. I assume it would be nice to have this as a feature, so cloned template can have defined behaviors associated with it, via preserved prototype. But I think it's not that important as most of lib / frameworks can handle it just fine.

**Comment by annevk** [comment]
Do you have a test that shows that behavior in Chrome? Because if I run OP I indeed get true for the last line, and not false.

**Comment by bigopon** [comment]
I can no longer reproduce this on my Chrome. Guess it's ... gone. Probably you need old version of Chrome to have this. I think this can be closed.

**Comment by foolip** [comment]
See https://github.com/w3c/web-platform-tests/pull/9987#issuecomment-381440785, tried to reproduce on Chromium builds up to a year old and couldn't, so I wonder if the problem was something else which was accidentally removed from the reduced test case?
