### ISSUE TITLE
DOM ready is error prone, still requires libs, could be simpler: a document#ready Promise

### ISSUE THREAD

**Issue by danbeam** [whatwg/dom#568]
Use case: initializing application code safely (especially dynamically loaded application code).

I think it's common to accidentally write some variant of this code:
```js
window.addEventListener('DOMContentLoaded', initApp);  // contents of init.js
```
while assuming `DOMContentLoaded` will always fire and `initApp` will always be called.

However, if init.js runs after the including context's `DOMContentLoaded` event (i.e. a dynamic script tag added later), `initApp` will never fire as the `DOMContentLoaded` event has already passed.  Same goes for `load`.

This forces web authors to load their scripts earlier to guarantee they're run before the `DOMContentLoaded` event (which isn't generally great for performance), or third-party widget authors change their code to something like:

```js
function initAppIfReady() {
  var ready = /interactive|loaded/.test(document.readyState);
  if (ready) initApp();
  return ready;
}
if (!initAppIfReady()) {
  document.addEventListener('readystatechange', function f() {
    if (initAppIfReady())
      document.removeEventListener('readystatechange', f);
  });
}
```
to make the code agnostic to how it was loaded.

I see code similar to this being discussed by [Dean Edwards / John Resig in 2006](http://dean.edwards.name/weblog/2006/06/again/) and I'm not aware of a platform solution to this yet.  Sorry if it's already been discussed.

Code like this also lives in [jQuery's src/core/ready.js](https://github.com/jquery/jquery/blob/bd984f0ee2cf40107a669d80d92566b8625b1e6b/src/core/ready.js#L60-L84), a common way to kickstart webapps safely.:
```js
jQuery(document).ready(initApp);  // same as $(initApp)
```

You also see it in [YUI3's `'domready'` event](https://github.com/yui/yui3/blob/master/src/event/js/event-ready-base-ie.js):

```js
YUI().use('event-base', function(Y) {
  Y.on('domready', initApp);
});
```
And a bunch of other popular libraries (including some [simply dedicated to this matter](https://github.com/ded/domready)).

I don't believe `Promise` existed in a useful/standardized way for use in DOM or ECMAScript when building blocks like the `load`, `DOMContentLoaded`, or `readystatechange` events were designed (or `Document#readyState`).  I think this could be _specified_ in a less error prone way.

If `Promise` did exist, I think it'd make a lot of sense to do something like:

```idl
partial interface Document {
  readonly attribute Promise<boolean> ready;
  readonly attribute Promise<boolean> loaded;  // if desired
};
```

The status of these Promise attributes would be set to resolved by the user agent at an appropriate time (strawman: synchronously in the same turn after handling `readystatechange` to `interactive` or `complete` [respectively] or asynchronously right after?).

Either way, I think encouraging authors/new code to do:

```js
document.ready.then(initApp);
```

is simpler and less error prone and actually what this API strives for to begin with.  DOM libraries could easily check for the existence of this code and use it until it's more standardly supported (and libraries aren't needed at all).

And yes: this can be implemented in terms of existing technology, but so could the `DOMContentLoaded`/`load` events be implemented in terms of polling `Document#readyState` with `setTimeout` (doesn't mean it's a good idea :wink:).  Here's an example polyfill:

```js
// polyfill Promise if necessary
document.ready = new Promise(function(resolve) {
  function resolveIfReady() {
    var ready = /interactive|loaded/.test(document.readyState);
    if (ready) resolve();
    return ready;
  }
  if (!resolveIfReady()) {
    // could wrap onreadystatechange if really necessary
    document.addEventListener('readystatechange', function f() {
      if (resolveIfReady())
        document.removeEventListener('readystatechange', f);
    });
  }
});
```

If interest is shown in this, I could certainly write web platform tests (and possibly implement in Chrome or find somebody to poke about it).

**Comment by domenic** [comment]
See https://github.com/whatwg/html/pull/1936. If you're willing to implement in Chrome, I think we'd be willing to merge. It even has multi-implementer interest and tests; it's just missing any implementer actually prioritizing it highly enough.

**Comment by freshp86** [comment]
+1. I think this would be a nice improvement. Note that newer APIs like the `customElements.whenDefined()` already use Promises to signal one-time events. Perhaps there should be one for each state of the document, like `whenReady()`, `whenInteractive()` etc.

**Comment by annevk** [comment]
I'm going to close this in favor of the issue/PR referenced by @domenic. Loading documents is by-and-large defined by HTML, so that's the place to pursue a proposal like this. Please leave a comment if that doesn't work for some reason. Thanks!
