### ISSUE TITLE
Extend `attachShadow()` safelist

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#571]
We've got requests for:

- [ ] `<a>` / `<area>`: https://github.com/w3c/webcomponents/issues/511
- [ ] <s>`<map>`: https://github.com/w3c/webcomponents/issues/734</s>

**Comment by rniwa** [comment]
I don't think we should support shadow root on either `a` or `area`. We would be opposed to it.

**Comment by TakayoshiKochi** [comment]
For the `<map>` element the reporter withdrew the intention, so we can close that here as well.

**Comment by Peeja** [comment]
What about `<ul>`, `<ol>`, and `<li>`, as [requested previously in an `html` issue](https://github.com/whatwg/html/issues/3883)?
