### ISSUE TITLE
Replacing a child in its parent doesn't correctly queue mutation records

### ISSUE THREAD

**Issue by nox** [whatwg/dom#59]
https://dom.spec.whatwg.org/#concept-node-replace

Step 13 states that the mutation record's previous sibling should be `child`'s previous sibling, but `child` was removed from its parent on step 10. There should be a step between 9 and 10 where its previous sibling is bound to a variable and reused in step 13.

**Comment by annevk** [comment]
> previousSibling will be wrong if node == child, AFAICT
