### ISSUE TITLE
Clarify behaviour of constructor in `class Foo extends Event {}`

### ISSUE THREAD

**Issue by jakearchibald** [whatwg/dom#598]
```js
class Foo extends Event {
  hello() { return 'hello'; }
}
const foo = new Foo('bar');
console.log(foo.constructor);
```

Chrome & Firefox say `Foo`, Edge & Safari say `Event`.

```js
console.log(foo.hello());
```

Chrome & Firefox say `hello`, Edge & Safari throw (undefined is not a function).

The Chrome/Firefox behaviour is preferable, as it allows you to create custom event objects.

**Comment by jakearchibald** [comment]
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=183629
Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16379447/

**Comment by annevk** [comment]
@domenic why is it again that we can just say "Interface() returns a new Interface" in prose and the subclassing falls out naturally? It seems a little weird.

**Comment by jakearchibald** [comment]
In Safari/Edge, it seems like `new Event()` is behaving like:

```js
class Event {
  constructor() {
    return Object.create(Event.prototype);
  }
}
```

Which you could argue is correct according to:

> **event = new Event(type [, eventInitDict])**
> Returns a new event…

Although this is in a non-normative section. There aren't any normative steps for the event constructor.

**Comment by annevk** [comment]
There are: https://dom.spec.whatwg.org/#constructing-events. They seem to cover the inheritance aspect actually. But we don't cover it for `EventTarget` so it's still a little weird all around how to go about this.

**Comment by jakearchibald** [comment]
Ah, sorry. The constructor in the IDL links to the non-normative section.

**Comment by domenic** [comment]
This is all defined in the IDL for [Constructor]. I can find it when back at a computer.

**Comment by annevk** [comment]
https://heycam.github.io/webidl/#interface-object I guess, though I can't quite figure out where that deals with subclassing.

**Comment by annevk** [comment]
> The constructor in the IDL links to the non-normative section.

It links nowhere in the IDL. The non-normative version links to the IDL though. That seems worth fixing.

**Comment by domenic** [comment]
Hmm yeah I guess that's broken right now. @tobie and I talked about how to fix it a month or so ago. (Roughly, instead of converting R to O, O should be created by ObjectCreate(new.target.prototype), and save R as an internal [[IDLValue]] slot.)

**Comment by jakearchibald** [comment]
I can write some tests for `Event` (and I'll check there's some for `EventTarget`). Or do we need to do something more general?

**Comment by annevk** [comment]
Just for Event for now I think (pretty sure EventTarget is covered). Thanks!

**Comment by jakearchibald** [comment]
Turns out it's already covered http://w3c-test.org/dom/events/Event-subclasses-constructors.html

**Comment by annevk** [comment]
\o/
