### ISSUE TITLE
Should early return for relatedTarget take cancelable flag into account

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#602]
The early return in the event dispatch algorithm takes the cancelable flag into account in Safari, but not in Chrome. What do we want here?

cc @rniwa @smaug---- @hayatoito

**Comment by annevk** [comment]
We could fix this as part of #585 I suppose, but raising it separately for now so that PR doesn't get too confused as it's already tackling so much.

**Comment by smaug----** [comment]
I don't understand this. Why should cancelable flag have anything to do with early return?

**Comment by annevk** [comment]
@smaug---- should we return false if the canceled flag is set? (This is what Safari does.)

**Comment by smaug----** [comment]
Safari's behavior makes sense here.

**Comment by annevk** [comment]
I updated #585 to avoid the early return altogether.
