### ISSUE TITLE
More bikeshed problems

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#62]
In https://github.com/whatwg/dom/commit/8f812e6b16ba31270ba60568fb0bdbb78949348e I found it unclear how to link to the URL specification. It should be `<a spec=url>URL</a>` according to the documentation, but that creates an internal link.

Furthermore, it ended up adding `<li><a href="#concept-document-type">dfn for Document</a><span>, in §4.5</span>` for something that should really be labeled "type" I think.

@tabatkins, ideas?

**Comment by tabatkins** [comment]
Are you trying to link to the URL spec itself, or to the definition of URL in the URL spec?  For the former, use a biblio link.  For the latter, I just put URL in the Shepherd database, so it wouldn't have been usable previously, but should hopefully now work.  (I haven't tried it out yet.)

For the second one, which biblio entry are you referring to, exactly?  There is such a line underneath the "type" biblio entry - there are a lot of definitions for the term "type", so it provides a sublist for all of the definitions with a disambiguator, which is what you're seeing.

**Comment by annevk** [comment]
I want a link to https://url.spec.whatwg.org/#concept-url ideally.
