### ISSUE TITLE
Flag refs in preventDefault()'s description missing "context object’s" qualifier

### ISSUE THREAD

**Issue by cvrebert** [whatwg/dom#627]
https://dom.spec.whatwg.org/commit-snapshots/07c110c87b8e4b1f7ecae09727b859bb75b17a73/#dom-event-preventdefault

> The preventDefault\(\) method, when invoked, must set the canceled flag if the cancelable attribute value is true and the in passive listener flag is unset\.

Compared to the rest of the spec, this seems to me to be the only place that refers to "the X flag" (twice) rather than "**context object’s** X flag", in relation to a DOM event's flags.

**Comment by annevk** [comment]
Thanks, I might solve this as part of #626 by making this share an algorithm with returnValue.
