### ISSUE TITLE
"Let capture, passive, and once be the result of flattening more options"

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#633]
https://dom.spec.whatwg.org/commit-snapshots/c80e0176d9565d2832ae3d535414faff7f6e7dda/#interface-eventtarget

> Let capture, passive, and once be the result of flattening more options\. 

What if options isn't passed?

**Comment by annevk** [comment]
I'm pretty sure that since it can be a dictionary it'll be a dictionary in that case.

**Comment by domenic** [comment]
You're right:

> Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified.
