### ISSUE TITLE
"Otherwise, if hasSeenCurrentTarget is true and ..."

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#642]
https://dom.spec.whatwg.org/commit-snapshots/4b2633f0b79aa4b49245e6a5022baf6a2b5dffe6/#interface-event

> Otherwise, if hasSeenCurrentTarget is true and struct’s root\-of\-closed\-tree is true, then increase hiddenSubtreeLevel by
> 

Some Bikeshed issue here is causing this to have a nested "1."

**Comment by annevk** [comment]
Yeah, duplicate of #564.
