### ISSUE TITLE
createElement() does not put things in the HTML namespace correctly

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#643]
https://dom.spec.whatwg.org/commit-snapshots/4b2633f0b79aa4b49245e6a5022baf6a2b5dffe6/#example-5ffcda00

> Let namespace be the HTML namespace, if the context object is an HTML document or context object’s content type is "application/xhtml\+xml", and null otherwise\. 

Consider the following code:

```js
const doc = new Document();
const a = document.createElement("a");
console.log(a.constructor.name);
```

This logs `HTMLAnchorElement` in all browsers.

However, per spec this should log `Element`. `new Document()` creates a new XML document, with content-type application/xml. So createElement() should use the null namespace. So when you go to look up the element interface to use, you just get the default, Element.

This seems to have been changed and discussed previously:

- https://github.com/whatwg/dom/issues/264
- https://github.com/whatwg/dom/pull/213
- https://github.com/whatwg/dom/issues/217
- https://www.w3.org/Bugs/Public/show_bug.cgi?id=19431

**Comment by annevk** [comment]
It's not that simple, try: `data:text/xml,<script xmlns="http://www.w3.org/1999/xhtml">alert(document.createElement("a"))</script>`.

**Comment by domenic** [comment]
Sorry, I don't really understand why that response is related to my original post.

**Comment by annevk** [comment]
It's unclear what bit to use to decide between HTML namespace and no namespace. It also seems weird that an otherwise identical XML document (you can change the MIME type from text/xml to application/xml if you want) would yield different results.

**Comment by Comandeer** [comment]
I'm not sure, but shouldn't the code be more like:

```javascript
const doc = new Document();
const a = doc.createElement("a");
console.log(a.constructor.name);
```

?

In this case we get correct `Element`, as it's created inside newly created document. Creating it in default window's document (`document`) does not make sense to me. Am I missing something and creating new document should replace the existing one?

**Comment by domenic** [comment]
Wow, yeah, it seems like the web platform tests that I thought depended on this just have a typo. Thank you!
