### ISSUE TITLE
form.disabled to disable the form submission

### ISSUE THREAD

**Issue by caub** [whatwg/dom#646]
```html
<form id="form">
  <input name="foo">
  <input name="sb" type="submit">
</form>
```

Currently, it's possible to disable the submit button with `form.sb = true` to disable this form submission (either by clicking the submit button, or pressing enter in a field)

I'd like to propose that `form.disabled = true` behaves similarly, currently it does nothing to prevent submission

**Comment by annevk** [comment]
Heya, thanks for your proposal; unfortunately this is the wrong place. New HTML features should go to https://github.com/whatwg/html.

I also suggest reading through https://whatwg.org/faq#adding-new-features.

Hope that helps.
