### ISSUE TITLE
Iterable NamedNodeMap

### ISSUE THREAD

**Issue by a-tarasyuk** [whatwg/dom#648]
Based on Chrome, FF implementations `NamedNodeMap` can be iterable(`[Symbol.iterator]`)

![Chrome](https://user-images.githubusercontent.com/509265/40323131-2f0073ec-5d3d-11e8-9ab6-d8f2a3eba9ba.png)

![FF](https://user-images.githubusercontent.com/509265/40323110-23405446-5d3d-11e8-9ca1-954eb676f95f.png) 

```javascript
for (const attr of document.body.attributes) {
    console.log(attr);
}
```

however, in the spec, there is no mention about that. For instance [`DOMTokenList`](https://dom.spec.whatwg.org/#interface-domtokenlist) has `iterable<DOMString>`.

**Comment by domenic** [comment]
Per Web IDL, any indexed getter and length property makes you automatically get [Symbol.iterator].

**Comment by inexorabletash** [comment]
Specifically https://heycam.github.io/webidl/#es-iterators (since I had that on the clipboard for a reply before domenic's comment landed)

**Comment by a-tarasyuk** [comment]
@domenic 

> Per Web IDL, any indexed getter and length property makes you automatically get [Symbol.iterator].

Thanks, Is `iterable<DOMString>` useless in `DOMTokenList`?

**Comment by a-tarasyuk** [comment]
@domenic @inexorabletash thanks for the clarification.
