### ISSUE TITLE
Order of "contains" in removeEventListener

### ISSUE THREAD

**Issue by TimothyGu** [whatwg/dom#664]
> The <a href="https://dom.spec.whatwg.org/#dom-eventtarget-removeeventlistener">**<code>removeEventListener(*type*, *callback*, *options*)</code>**</a> method, when invoked, must run these steps:
>
> …
>
> 3. If the context object’s [event listener list](https://dom.spec.whatwg.org/#eventtarget-event-listener-list) [contains](https://infra.spec.whatwg.org/#list-contain) an [event listener](https://dom.spec.whatwg.org/#concept-event-listener) whose type is *type*, callback is *callback*, and capture is *capture*, then <a href="https://dom.spec.whatwg.org/#remove-an-event-listener">remove an event listener</a> with the context object and that event listener.

> A [list](https://infra.spec.whatwg.org/#list) [**contains**](https://infra.spec.whatwg.org/#list-contain) an [item](https://infra.spec.whatwg.org/#list-item) if it appears in the list.

What happens if there are multiple event listeners in the `EventTarget` object's event listener list that fit those searching criteria (type, callback, capture)? Is the searching process in ascending or descending order? Or are *all* the listeners that fit those criteria removed? The order is observable through the use of the [`passive`](https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-passive) and [`once`](https://dom.spec.whatwg.org/#dom-addeventlisteneroptions-once) options.

Inspired by nodejs/node#21635.

**Comment by TimothyGu** [comment]
Never mind, [add an event listener](https://dom.spec.whatwg.org/#add-an-event-listener) looks through the list using those criteria before appending, and exits if one exists already.

**Comment by annevk** [comment]
It seems reasonable to add a note.
