### ISSUE TITLE
"When a DOMTokenList object is created, then: ..."

### ISSUE THREAD

**Issue by TRowbotham** [whatwg/dom#666]
https://dom.spec.whatwg.org/commit-snapshots/32efc48fef28c34ed914b60cfb3c29807e617365/#interface-domtokenlist

> When a DOMTokenList object is created, then:​
> 
>     1. Let element be associated element\.
> 
>     2. Let localName be associated attribute’s local name\.
> 
>     3. Let value be the result of getting an attribute given null, localName, and element\.
> 
>     4. Run the attribute change steps for element, localName, value, value, and null\. 

In step 3, "getting an attribute" links to the [get an attribute by namespace and local name](https://dom.spec.whatwg.org/#concept-element-attributes-get-by-namespace) algorithm, which returns an `Attr` node or `null`. This is a problem because in step 4, value is passed to the "attribute change steps" as the oldValue and value arguments, which only accept a `string` or `null`. So, step 3 should either link to the [get an attribute value](https://dom.spec.whatwg.org/#concept-element-attributes-get-value) algorithm or operate on the returned `Attr` node's value. Not really sure which is more appropriate here.

**Comment by annevk** [comment]
Making it use "get an attribute value" seems best. Might also be good to quickly look at blame to see if this regressed somehow or was always incorrect.

**Comment by TRowbotham** [comment]
I had to read it a few times, but I \*think\* the steps prior to the above change were correct, but a bit more convoluted. It basically reads if the element has an attribute that is its associated attribute's local name, or if the element's associated attribute's local name is set, then set the list of tokens to the new value after being parsed by the ordered set parsing steps.
