### ISSUE TITLE
TreeWalker's nextNode() method can result in an infinite loop because the value of node never changes if it doesn't have a child

### ISSUE THREAD

**Issue by TRowbotham** [whatwg/dom#667]
Given the following:
```html
<doctype html>
<html>
  <head></head>
  <body></body>
</html>
```
```javascript
const treeWalker = document.createTreeWalker(document, NodeFilter.SHOW_ELEMENT, null);
treeWalker.nextNode();
```

A walk through:

Step 1) *node* is set to `document`
Step 3.1) *result* is `FILTER_ACCEPT` and *node* has a child so we enter the loop
Step 3.1.1) *node* is set to `document`'s `doctype`
Step 3.1.2) *result* is set to `FILTER_SKIP` so we continue on
Step 4.2) *sibling* is set to *temporary's* next sibling, which is the `<html>` tag
Step 4.3) *sibling* is non-null, so we break out of the loop
Step 5) *result* is set to `FILTER_SKIP`
Step 6) since *result* is not `FILTER_ACCEPT`, we return to Step 3

Since a `doctype` doesn't have children, we never enter the while loop at Step 3.1 again, which is the only place where *node* changes, leaving *node* permanently set to `document`'s `doctype`, and thus an infinite loop is born.

**Comment by annevk** [comment]
Looking at https://searchfox.org/mozilla-central/source/dom/base/TreeWalker.cpp#172-185 it seems like the fix might have to be a bit more involved and there's some other cases not covered here.

**Comment by oozcitak** [comment]
These are the steps proposed with 124d06d8f77a640d3cb501380563c1bcf38dc7c9 (differences from spec marked bold):

1. Let node be the context object’s current.
2. Let result be FILTER_ACCEPT.
3. While true:
    1. While result is not FILTER_REJECT and node has a child:
        1. Set node to its first child.
        2. Set result to the result of filtering node within the context object.
        3. If result is FILTER_ACCEPT, then set the context object’s current to node and return node.
    2. Let sibling be null.
    3. Let temporary be node.
    4. While temporary is non-null:
        1. If temporary is the context object’s root, then return null.
        2. Set sibling to temporary’s next sibling.
        3. If sibling is non-null, then __set node to sibling and__ break.
        4. Set temporary to temporary’s parent.
    6. Set result to the result of filtering node within the context object.
    7. If result is FILTER_ACCEPT, then set the context object’s current to node and return node.

And these are mozilla's steps (differences from spec marked bold):

1. Let node be the context object’s current.
2. Let result be FILTER_ACCEPT.
3. While true:
    1. While result is not FILTER_REJECT and node has a child:
        1. Set node to its first child.
        2. Set result to the result of filtering node within the context object.
        3. If result is FILTER_ACCEPT, then set the context object’s current to node and return node.
    2. Let sibling be null.
    3. Let temporary be node.
    4. While temporary is non-null:
        1. If temporary is the context object’s root, then __break__.
        2. Set sibling to temporary’s next sibling.
        3. If sibling is non-null, then break.
        4. Set temporary to temporary’s parent.
    5.  __If sibling is null, then break.__
    6.  __Set node to sibling__
    6. Set result to the result of filtering node within the context object.
    7. If result is FILTER_ACCEPT, then set the context object’s current to node and return node.
4.  __return null__

The cases where `temporary` and `sibling` are `null` are handled slightly differently, but both algorithms should produce identical results.

**Comment by annevk** [comment]
Duplicating into #787, see https://github.com/whatwg/dom/issues/787#issuecomment-551829951 for analysis.
