### ISSUE TITLE
TreeWalker::nextNode()'s implementation spec is incomplete

### ISSUE THREAD

**Issue by johan** [whatwg/dom#672]
Step 3.4.3 of the [`nextNode()`](https://dom.spec.whatwg.org/#dom-treewalker-nextnode) spec is missing an assignment (`node = temporary`) before breaking. Without one, the whole 3.4 loop step is a no-op.

**Comment by Codifier** [comment]
I think it is actually supposed to be `node = sibling`, right before `break`ing out of (or after) the `while` loop, when a non-null `sibling` is found. I believe `temporary` is merely used to climb back up the tree to find a suitable sibling.

**Comment by domenic** [comment]
FWIW our jsdom implementation appears to have a step like this, but also departs in (re)using _node_ instead of _temporary_ in a few places.

**Comment by pwombwell** [comment]
This fix isn't correct. Using this tree, where nodes are the order they should occur by stepping through nextNode():
```
           root
            / \
           1   7
          / \
         2   4
        /   / \
       3   5   6

```
if you are at node 3 and follow the algorithm, 'temporary' points to 2, and 'sibling' points to 4. So it would return 2. The fix is is to assign node=sibling before the break.

**Comment by annevk** [comment]
Let's merge this into #787.
