### ISSUE TITLE
Should the submit event be "magic" too?

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#678]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1477286.

This is very similar to the `click` event so maybe `submit` needs to have some activation behavior like thing as well. Sigh.

**Comment by domenic** [comment]
My reading of that bug (specifically comments 0 and 3) says that Firefox may be the only browser that does this, so the existing spec may be fine. Did I read it wrong?

**Comment by annevk** [comment]
Oh, yes. Thanks!
