### ISSUE TITLE
Factor getElementsBy* into ParentNode or NonElementParentNode?

### ISSUE THREAD

**Issue by travisleithead** [whatwg/dom#68]
For Shadow DOM, it would be nice to have these APIs available on ShadowRoot objects. Not sure why they aren't at the moment.

**Comment by domenic** [comment]
Hmm. What use cases do these support that querySelector/querySelectorAll do not support? I guess they are nicer if you have weird IDs or class names, as then you don't need to escape them...

**Comment by annevk** [comment]
The rationale was indeed that you should use `query*`. `getElementById()` we did want to support but it broke jQuery or some such.

**Comment by TakayoshiKochi** [comment]
@travisleithead maybe https://www.w3.org/Bugs/Public/show_bug.cgi?id=23620 contains more context on this?

**Comment by ArkadiuszMichalski** [comment]
Explain here:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27569
https://bugzilla.mozilla.org/show_bug.cgi?id=933193#c17

**Comment by travisleithead** [comment]
I think I'm just not buying into the initial premise that Live HTML collections are bad (which are returned by the getElementsBy* methods, thus we should avoid making them available to new derived objects like ShadowRoot. If they were so bad, why was getElementsByClassName added so [relatively] recently? Yes, querySelectors and family are generalizations of these APIs, but there is something to be said for being able to optimize a specialized API in implementation, and frankly to have a choice of usage is also good IMO. Finally, there is no implementation burden. All these points have been made before as I read the above links.

Yet, not having read those discussions initially, and after reviewing the Shadow DOM and DOM specs, this seemed like a glaring omission. I'm certain other JavaScript authors will see it the same way and wonder, "why not?".

**Comment by domenic** [comment]
How can you not say live HTML collections are bad? They are super-confusing for authors, who don't expect array-like things to change out from under them (e.g. while iterating them).

**Comment by annevk** [comment]
`getElementsByClassName()` was added as recent as `localStorage` was, iirc. I think your argument is invalid.

**Comment by travisleithead** [comment]
I guess I feel that it will be more confusing for authors *not* to find these APIs on Shadow roots in the future. As more and more authors adopt a component model design, the shadow root object becomes a stand-in for the traditional document object as far as a place to execute node searches. And with getElementById and querySelector available, but not the others, it will look like a spec oversight/bug in implementations.

I suppose I'm just echoing [this sentiment](http://lists.w3.org/Archives/Public/public-whatwg-archive/2013Oct/0102.html).

**Comment by annevk** [comment]
I was wrong above. `getElementById()` is available on `DocumentFragment`. It's not available on `Element`.

@travisleithead how about we first try it without for a while and then reevaluate? Shadow DOM hasn't really been cross-browser yet so we don't really know yet what will happen. I'm sure this will come up, but I also think that many developers will side with what @domenic said above. This is not just a purity argument, live lists are actually bad.

**Comment by travisleithead** [comment]
That's the second-best outcome I could have hoped for. If the public speaks (and we are listening) we can reopen this issue.
