### ISSUE TITLE
composedPath() is wrong

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#684]
@pmdartus discovered in https://github.com/jsdom/jsdom/pull/2347#discussion_r212829365 that the algorithm as-is exposes closed shadow nodes. This also happens in Firefox.

See `shadow-dom/event-composed-path.html` in wpt.

It seems to solve this we'd need to record for each item in an event's path what nesting level it's at and whether it's inside a closed shadow tree?

(This was missed in #535.)

cc @whatwg/components

**Comment by domenic** [comment]
It may be worth comparing to https://github.com/jsdom/jsdom/blob/aa8a1a624e277e3a37597352f95f73938ca4e38d/lib/jsdom/living/events/Event-impl.js#L83

**Comment by annevk** [comment]
I created a fix for this in #696, but note that this also requires changes to Indexed DB. I can make those if we can agree on the approach.

@domenic that seems to be basically the existing algorithm, which has the bug, no?

cc @inexorabletash

**Comment by domenic** [comment]
Not sure, I was just working off the comment which says that it doesn't implement the current algorithm. /cc @pmdartus.

**Comment by annevk** [comment]
Sorry, you're right, it seems equivalent to the WebKit approach, while also keeping some of the existing structures the specification has (not requiring a change to "get the parent"). Not entirely sure what's better.

**Comment by pmdartus** [comment]
You are right @annevk, the algorithms are sensibly the same. 

As far as I understand @rniwa's algorithm the shadow depth is computed in advance and added to the path, while in the jsdom implementation shadow depth is computed in the getComposedPath.

**Comment by inexorabletash** [comment]
re: Indexed DB - thanks for the heads up. PRs welcome!

**Comment by annevk** [comment]
So something has bothered me a bit and I'm not sure to what extent we should try solve it now. Before shadow trees you had node trees and event trees/paths. They were roughly analogous as you would only go up and down.

With shadow trees, node trees became more powerful, and some of that leaked into the event API. However, event trees/paths were still as powerful as before. The complexity of shadow trees ended up being a bunch of special cases in event trees/paths, rather than a generic mechanism that, e.g., something like Indexed DB could also use (or `new EventTarget()` once it exposes "get the parent").

The approach I took in #696 moves some of the shadow tree logic into "get the parent" so it's generalized and potentially reusable by other event trees/paths, but not all of it.

Is that a good direction to be heading in?

(If the answer is no, I should probably do the jsdom approach, which basically used the original dispatch and "get the parent" infrastructure to enable the same thing.)

**Comment by rniwa** [comment]
Extending *get the parent* seems rather invasive. If I were you, I would have defined the depth of shadow trees as a separate concept, and simply stored that depth. My implementation in WebKit doesn't use that precise definition of the depth because computing the depth of tree happens to be an expensive operation in WebKit but one could imagine another implementation can cheaply compute the depth of (closed) shadow trees and simply store that information while building up the event path.

**Comment by annevk** [comment]
It's invasive, but it would allow non-node trees to have the same capabilities as node trees. Or are you suggesting that depth would be a property of a node? That'd also be somewhat invasive probably.

**Comment by hayatoito** [comment]
@annevk 
Yeah, it is a little difficult for me to review the event dispatch steps and composed path steps in the standard. One of the reasons to me is Blink uses the different algorithm (but it should have the equivalent result), so I can't be confident with the correctness of each steps in the standard. :(

I have no concrete idea to make the situation better. Let me think somehow.

**Comment by rniwa** [comment]
> It's invasive, but it would allow non-node trees to have the same capabilities as node trees. Or are you suggesting that depth would be a property of a node? That'd also be somewhat invasive probably.

I don't know if that's all that important. I'm suggesting that the algorithm to build up the event path could simply check if a target is a node, and if so, compute the depth of the closed shadow tree at that point.

**Comment by annevk** [comment]
Okay, yeah, that's the status quo. So I guess it doesn't seem weird to you that the event API has node-specific stuff on it that cannot be used in non-node cases?

**Comment by rniwa** [comment]
Yeah, it's probably not that bad, and the spec would be easier to read.

**Comment by rniwa** [comment]
FWIW, WebKit's change landed in https://trac.webkit.org/changeset/236103.

**Comment by annevk** [comment]
I created an alternative PR that effectively copies @pmdartus's approach in jsdom: #699 (with minor tweaks). That would not affect "get the parent" or Indexed DB and keeps dispatch rather special.
