### ISSUE TITLE
Change `#time-origin` to `#sec-time-origin` for <anchor> tag.

### ISSUE THREAD

**Issue by payingattention** [whatwg/dom#688]
Reading https://dom.spec.whatwg.org/commit-snapshots/28cdb47e557c814fcca60759f4cce43e9c0e9a47 an error: the <anchor> tag for "#time-origin" (https://w3c.github.io/hr-time/#time-origin) does not point to "#sec-time-origin" (https://w3c.github.io/hr-time/#sec-time-origin).

I do not know if to `blame` (https://git-scm.com/docs/git-blame) W3.org or WHATWG.org specifically. I am scared to do the code (just lines https://github.com/whatwg/dom/blob/28cdb47e557c814fcca60759f4cce43e9c0e9a47/dom.bs#L36, https://github.com/whatwg/dom/blob/28cdb47e557c814fcca60759f4cce43e9c0e9a47/dom.bs#L570 {basically add/remove of "`sec`" is the language/spelling problem?} I think?), honestly I need a second opinion publicly before I make a change like that.

Automatic bug generation text [From "File an issue about the selected text." tool]:

https://dom.spec.whatwg.org/#ref-for-time-origin

> time origin

**Comment by annevk** [comment]
I think we want https://w3c.github.io/hr-time/#dfn-time-origin even. I suspect this changed in High Resolution Time at some point, but it's rather hard to determine as git doesn't hold the generated HTML.

A good way to fix this would be to make High Resolution Time export its definitions so we don't have to include a "hard coded" link.

cc @igrigorik

**Comment by domenic** [comment]
I don't think ReSpec specs have a notion of "exporting a definition", or of stability over time in general.

**Comment by igrigorik** [comment]
Indeed, you want the hr-time definition. Paging @marcoscaceres for input on respec. :)

**Comment by annevk** [comment]
@payingattention if you are willing to sign https://participate.whatwg.org/agreement and want to fix that'd be great. `type:dfn; text: time origin` needs to become `type:dfn; text: time origin; url: dfn-time-origin`.

**Comment by payingattention** [comment]
Okay, signed w/ https://github.com/whatwg/participant-data/commit/f36dee22d752491c60d1a0fe3dcf9b5360397885. Roger. Definitely thank you (tripped by `dfn` vs. `sec` apparently). Give me a sec.

**Comment by marcoscaceres** [comment]
@domenic, you know I love you, but...

> I don't think ReSpec specs have a notion of "exporting a definition",

We are working with @plinss to get Shepherd integration. We are all busy people tho, and these things take time. 

>  or of stability over time in general.

That's  unfair and uncalled for (and demonstratively false!). ReSpec has been used for longer than BikeShed and it's actively maintained and quite stable. In particular, folks here could tell you that I always respond promptly and work speedily to fix any issues that arise. Please refrain from 💩ing on ReSpec - as BS has its own set of problems (no software is perfect - and ReSpec and BikeShed serve different needs/communities).
