### ISSUE TITLE
Assign slotables for a tree should be invoked on node and not node's root in node remove

### ISSUE THREAD

**Issue by pmdartus** [whatwg/dom#691]
https://dom.spec.whatwg.org/commit-snapshots/28cdb47e557c814fcca60759f4cce43e9c0e9a47/#concept-node-remove

> 12.2. Run assign slotables for a tree with node’s root.

In the remove node algorithm, the root of the node at this point (12.2.) is always the node itself since it has already been detached from the tree (9.). It should run assign slotable for a tree on the node and not the node's root.

See: https://github.com/jsdom/jsdom/pull/2347#discussion_r212805887

**Comment by annevk** [comment]
See also https://github.com/w3c/webcomponents/issues/764.

cc @whatwg/modules

**Comment by annevk** [comment]
Created a PR for this as on reflection this is simply an editorial change.

**Comment by rniwa** [comment]
Note that in the browsers that do implement mutation events & unload events in iframes, the root node can still be different.
