### ISSUE TITLE
Clarify whether a connected callback should be enqueued for the insertion in parser 

### ISSUE THREAD

**Issue by EdgarChen** [whatwg/dom#694]
See https://html.spec.whatwg.org/multipage/parsing.html#insert-a-foreign-element.

The spec doesn't mention a connected callback should be enqueued for the inserted node (Or actually it miss the link referencing to the right place). But it seems test cases has different expectation:

1. https://github.com/web-platform-tests/wpt/blob/7e6d78de85f3fe71cc7c46fbaed17a8cd76f7d44/custom-elements/parser/parser-sets-attributes-and-children.html#L75-L80 expects the node has no child when the connected callback is called, since the reaction will be excuted after the insertion. This means it expects connected callback should be enqueued for the insertion.

2. But https://github.com/web-platform-tests/wpt/blob/7e6d78de85f3fe71cc7c46fbaed17a8cd76f7d44/custom-elements/connected-callbacks-html-fragment-parsing.html#L26-L28 expects the node has children appended when the connected callback is called. This means it doesn't expects connected callback be enqueued for the insertion.

Filed this issue to clarify whether a connected callback should be enqueued in https://html.spec.whatwg.org/multipage/parsing.html#insert-a-foreign-element.

**Comment by annevk** [comment]
Step 3.2 there does "Insert" which is https://dom.spec.whatwg.org/#concept-node-insert. HTML generally does a bad job at referencing those operations directly. (This should probably be filed against whatwg/html as it's a problem with HTML not DOM.)

**Comment by EdgarChen** [comment]
> (This should probably be filed against whatwg/html as it's a problem with HTML not DOM.)

Ah, thanks. And https://github.com/whatwg/html/issues/1706 probably cover this?

**Comment by annevk** [comment]
Yeah, let's dupe it against that, thanks!
