### ISSUE TITLE
Spec event.keyCode for keypress events

### ISSUE THREAD

**Issue by miketaylr** [whatwg/dom#701]
It turns out implementing `window.event` without `event.keyCode` for `keypress` breaks sites. 😢 

https://bugzilla.mozilla.org/show_bug.cgi?id=1479964

Masayuki suggested Firefox follow what Chrome does here: https://bugzilla.mozilla.org/show_bug.cgi?id=1479964#c3.

Seems reasonable to me?

**Comment by annevk** [comment]
Yeah, this should be defined by https://github.com/w3c/uievents though. The DOM Standard doesn't cover keyboard input.

**Comment by miketaylr** [comment]
OK, thanks. I'll move the issue.
