### ISSUE TITLE
[spec bug?] Element with name attribute breaks Document

### ISSUE THREAD

**Issue by petamoriken** [whatwg/dom#708]
https://html.spec.whatwg.org/multipage/dom.html#dom-document-nameditem

Modern browsers except Edge expose `Element` with name attribute more preferentially than a property already defined in `Document` WebIDL. Since this behavior seems to be dangerous, IMHO, it is better to design specifications that preferentially return defined properties if there is no compatibility problem. 

```html
<title>This is Document Title</title>
<form name="title"></form>
<script>
  console.log(document.title);
  // <form name="title"></form> in Chrome, Firefox, Safari
  // "This is Document Title" in Edge
</script>
```

code: https://codepen.io/petamoriken/pen/zmaRJX
(appendix) `WindowProxy` version: https://codepen.io/petamoriken/pen/MPXNJe

**Comment by annevk** [comment]
This is defined in the HTML Standard, so if you could refile this over at https://github.com/whatwg/html/issues/new that'd be appreciated. It's interesting though that browsers diverge here and there might be a way to get slightly better behavior.

**Comment by petamoriken** [comment]
Thanks! I moved.
https://github.com/whatwg/html/issues/4112
