### ISSUE TITLE
This text needs to be proof-read for phrasing and grammar.

### ISSUE THREAD

**Issue by kizerkizer** [whatwg/dom#718]
https://dom.spec.whatwg.org/commit-snapshots/23ec6421f47ab629bd14dfc6d4910414dc443d0b/#introduction-to-dom-events

> Throughout the web platform events are dispatched to objects to signal an occurrence, such as network activity or user interaction\. These objects implement the EventTarget interface and can therefore add event listeners to observe events by calling addEventListener\(\):​
> 
> obj\.addEventListener\("load", imgFetched\)
> 
> function imgFetched\(ev\) \{
>   // great success
>   …
> \}
> 
> Event listeners can be removed by utilizing the removeEventListener\(\) method, passing the same arguments\.
> 
> Events are objects too and implement the Event interface \(or a derived interface\)\. In the example above ev is the event\. **It is passed as argument to event listener’s callback** \(typically a JavaScript Function as shown above\)\. Event listeners **key off** the event’s type attribute value \("load" in the above example\)\. **The event’s target attribute value returns the object** to which the event was dispatched \(obj above\)\.
> 
> **Now while typically** events are dispatched by the user agent as the result of user interaction or the completion\.\.\.

**Comment by kizerkizer** [comment]
"**Lets** look at an example"

**Comment by kizerkizer** [comment]
"If an event listener was registered for the span element, eventPhase attribute’s value would have been AT_TARGET."

**Comment by studdugie** [comment]
My 2 cents:

It is passed as an argument to the event listener's callback function ...

Now, ...

**Comment by annevk** [comment]
Thanks, would you be willing to PR this?

**Comment by studdugie** [comment]
I'm sorry but I haven't spent a lot of time w/ Github or its workflow. So though I think "PR" means pull request I'm not sure what the exact steps are that I need to take. If you can explain what I need to do I shall.

**Comment by js-choi** [comment]
Did a quick pull request correcting the typos. I realize now that doing so before @studdugie had a chance to try themselves might have been impolite—sorry, @studdugie, if it was.

**Comment by annevk** [comment]
Thanks @js-choi, I'll leave some time to @kizerkizer and @studdugie to review your work. It looks good to me.

@studdugie for a future PR, https://github.com/whatwg/meta/blob/master/CONTRIBUTING.md has a number of guidelines. For help around GitHub, it's probably best to read GitHub's own documentation: https://help.github.com/articles/creating-a-pull-request/.

**Comment by studdugie** [comment]
@annevk Thanks for the links and does this mean that you still want me to do a pull request or did you decide to just incorporate my 2 cents manually?

**Comment by annevk** [comment]
@studdugie if there's something #723 does not address another PR would be welcome, but I think your suggestion might have been covered there already. I mostly wrote that for future reference.

**Comment by kizerkizer** [comment]
Looks good to me! Thanks @js-choi !
