### ISSUE TITLE
Make createAttribute() lowercase the input in HTML documents

### ISSUE THREAD

**Issue by foolip** [whatwg/dom#72]
The context for this can be found in https://bugzilla.mozilla.org/show_bug.cgi?id=1176313 and the bugs mentioned therein.

In summary, this looks like the best option for getting the case handling of attribute names in a somewhat consistent state, by lowercasing input where needed, and it avoids case-insensitive lookups.

**Comment by annevk** [comment]
Duplicate of #41?

**Comment by foolip** [comment]
Yes, sorry.
