### ISSUE TITLE
Can the `options` argument to `EventTarget::addEventListener` be omitted?

### ISSUE THREAD

**Issue by amn** [whatwg/dom#726]
The [interface `EventTarget`](https://dom.spec.whatwg.org/#interface-eventtarget) specifes the `options` argument to its `addEventListener` method as `optional (AddEventListenerOptions or boolean) options` , which I take as meaning the argument may be omitted.

However, the [actual procedure for how `addEventListener` shall behave](dom-eventtarget-addeventlistener), further down the same document, does not appear to specify how to treat the case of omitted `options` argument.

Is this by design -- implementations are free to behave in a manner they find suitable with regard to omitting the argument, or is this an oversight in the publication?

**Comment by annevk** [comment]
Indeed, I filed https://github.com/heycam/webidl/issues/602 to consider changing the syntax here to make this behavior more explicit. Hope that helps.
