### ISSUE TITLE
Bad "good first issue" labels

### ISSUE THREAD

**Issue by David263** [whatwg/dom#729]
One or more issues here, like #671 and its associated #675, are marked with the "good first issue" label. As a beginner GitHub user, I disagree. The technical issue of testing document.createElementNS() arguments may be simple (and moot due to deprecation), but the failure of GitHub to accept the pull request is not at all obvious to a git beginner.

I have tried to remove the "good first issue" labels, but I don't seem to have permission since I'm not the owner. I request that the owner make this fix. And please accept merges to the DOM Standard that are blocked only on GitHub procedural issues.

**Comment by annevk** [comment]
Thanks, I've removed the label. Next time please only leave a single comment as now everyone subscribed got quite a few notifications for this.
