### ISSUE TITLE
Dispatching slotchange within a compound microtask

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#734]
HTML requires that "execute a compound microtask subtask" is used to invoke callbacks within a "compound microtask", as I understand it. However, we don't do this for the slotchange event. And it's not clear to me that we can, since dispatching the slotchange event can result in multiple listeners being triggered, each with their own callback. Surely we don't want to weave "execute a compound microtask subtask" through all that?

So how do browsers implement the last step of https://dom.spec.whatwg.org/#notify-mutation-observers today?

cc @whatwg/components

**Comment by rniwa** [comment]
WebKit's code: https://trac.webkit.org/browser/trunk/Source/WebCore/dom/MutationObserver.cpp#L259

I don't think we even implement compound microtask subtask.

**Comment by smaug----** [comment]
Gecko's code looks pretty similar, but I think not exactly the same if there also some promises around.
If I read the code right, webkit loops over [mutationobservers, slotschanges] until there aren't any, but
Gecko it is more like loop all microtasks, where one can be [mutationobservers, slotchanges.]
But perhaps I'm missing where webkit deals with 'performing a microtask checkpoint' flag

**Comment by annevk** [comment]
@rniwa how does _deliveryInProgress_ work? I wonder when the conditional will return true.

**Comment by annevk** [comment]
https://github.com/whatwg/html/pull/4437 to investigate removing compound microtasks from HTML.

**Comment by annevk** [comment]
FYI: based on the HTML PR thread the conclusion here seems to be that we remove the compound microtask infrastructure. This results in a minor simplification of the DOM Standard shown in #741.
