### ISSUE TITLE
Wrong return type of Node::getRootNode()

### ISSUE THREAD

**Issue by SetTrend** [whatwg/dom#739]
The WhatWG page on [Node::getRootNode](https://dom.spec.whatwg.org/#interface-node) states that this function returns an object of type `Node`. Yet, shouldn't it state, instead, that this function returns an object of type `ShadowRoot`?

The `Node` interface lacks, for instance, the [`host`](https://dom.spec.whatwg.org/#interface-shadowroot) property, which is documented to be a property of the return value of `Node::getRootNode()`.

/see also: /mdn/sprints/issues/1204

**Comment by domenic** [comment]
> which is documented to be a property of the return value of Node::getRootNode().

What documentation is that referring to? It's not in the spec, which says that the return value is of type `Node`.

Anyway, `getRootNode()`'s specification is correct. If you look at the algorithm, in https://dom.spec.whatwg.org/#dom-node-getrootnode , you'll see it can return the root node, which can be a `Document`, which is not a `ShadowRoot`. Try it in your own browser: type `document.body.getRootNode()` and see what it returns.

**Comment by SetTrend** [comment]
I found all this:

- https://stackoverflow.com/a/41310417
- https://stackoverflow.com/a/41377576
- https://stackoverflow.com/q/55226473
- https://polymer-library.polymer-project.org/3.0/api/legacy/legacy-element-mixin#LegacyElementMixin-property-domHost
- https://github.com/haltu/muuri/issues/235

Chrome and Firefox return valid values when evaluating `this.getRootNode().host` from within a web component having a Shadow DOM attached.

**Comment by domenic** [comment]
Yes, sometimes it does return a ShadowRoot. Sometimes it returns a Document, or HTMLDocument, or SVGDocument, or similar. All of these are different types of Node. That is why the return value is Node.

**Comment by SetTrend** [comment]
Ah, I see. Thank a lot for clarifying!

**Comment by annevk** [comment]
It can also return any other kind of node, if the node or one of its ancestors isn't connected.
