### ISSUE TITLE
Definition of valid shadow elements is ambiguous

### ISSUE THREAD

**Issue by MatsPalmgren** [whatwg/dom#745]
https://dom.spec.whatwg.org/#dom-element-attachshadow
Item 2 in the list says:
> If context object’s local name is _not_ a valid custom element name, "article", "aside", "blockquote", "body", "div", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "main" "nav", "p", "section", or "span", then throw a "NotSupportedError" DOMException. 

The above sentence is ambiguous. The enumeration can be read both as a list of valid names, or as a list of invalid names.  The sentence is also unnecessarily complex.  I would suggest:

If context object’s local name is _not_ a valid custom element name, then throw a "NotSupportedError" DOMException.  The only valid names are: "article", "aside", "blockquote", "body", "div", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "main" "nav", "p", "section", and "span".

**Comment by annevk** [comment]
I'd also support a list:

> If context object’s local name is not one of
> * a valid custom element name
> * "article"
> * "aside"
> * ...
>
> then throw ...

(Note that the rewording in OP is incorrect.)

**Comment by MatsPalmgren** [comment]
Oh, so "a valid custom element name" was intended to be one of the alternatives in that enumeration?  Then it's even worse than I thought, because that meaning didn't even occur to me. I might have understood it like that if there had been a colon after the "not", maybe. @rniwa's first suggestion have that same problem IMO.  The second suggestion is better but still rather convoluted.  Perhaps making an explicit listing of alternatives is better:

Context object’s local name must be one of the following:
* a valid custom element name
* "article", "aside", "blockquote", "body", "div", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "main" "nav", "p", "section", or "span"

If it's not, then throw a "NotSupportedError" DOMException.

**Comment by Yash-Handa** [comment]
Hey @annevk, I would love to help in editing the dom.bs.

BTW, for clarification the following should be done:

> this’s local name must be one of the following:
> - a valid custom element name.
> - `"article"`, `"aside"`, `"blockquote"`, `"body"`, `"div"`, `"footer"`, `"h1"`, `"h2"`, `"h3"`, `"h4"`, `"h5"`, `"h6"`, `"header"`, `"main"`, `"nav"`, `"p"`, `"section"`, or `"span"`.
> 
> If it's not, then throw a "NotSupportedError" DOMException.

A suggestion though (a less verbose option):

> If this’s local name is not an `"article"`, `"aside"`, `"blockquote"`, `"body"`, `"div"`, `"footer"`, `"h1"`, `"h2"`, `"h3"`, `"h4"`, `"h5"`, `"h6"`, `"header"`, `"main"`, `"nav"`, `"p"`, `"section"`, `"span"`, or any valid custom element name, then throw a "NotSupportedError" DOMException.

Do let me know which one should be used : )

**Comment by annevk** [comment]
Thanks @Yash-Handa!

I'd suggest:

> If this's local name is not one of the following:
>
> * ...
> * ...
>
> then throw a ...
