### ISSUE TITLE
The dispatch algorithm should account for changing the target to the associated labeled control, if available

### ISSUE THREAD

**Issue by mbrodesser** [whatwg/dom#749]
There's a separate [issue](https://github.com/whatwg/html/issues/4516) for adapting the whatwg/html spec.

When a label has an associated [labeled control](https://html.spec.whatwg.org/#labeled-control), the [dispatch algorithm](https://dom.spec.whatwg.org/#concept-event-dispatch) should adjust the target to the labeled control. See for instance the first example at https://html.spec.whatwg.org/#the-label-element. It seems this would match the behavior of at least Firefox, Chrome and Safari (tested on Windows, Ubuntu and OSX -- obviously, where the OS supports the browser).

E.g.:
```
data:text/html,<label id="cb-label">CB <input type="checkbox" id="cb"></label> <script> e = new MouseEvent("click"); document.getElementById("cb-label").dispatchEvent(e); </script>
```

**Comment by annevk** [comment]
I'm going to close this per analysis in https://github.com/whatwg/html/issues/4516#issuecomment-481665362. As far as I can tell the label element can cause another event to be dispatched, but it cannot change the course of a dispatched event.
