### ISSUE TITLE
Add forEach to HTMLCollection interface

### ISSUE THREAD

**Issue by oliverdunk** [whatwg/dom#757]
With `NodeList` now implementing `iterable<Node>`, I went looking to see why we don't get it on a collection. I couldn't find a reason - so while I'm assuming it's already been discussed, I'm opening this to suggest it on the off chance it hasn't.

There's a Chrome bug about it here, and the idea wasn't immediately dismissed: https://bugs.chromium.org/p/chromium/issues/detail?id=435862

The use case for this is easily iterating over the results of something like `getElementsByClassName`. I saw someone using array spread as a hacky way to do this, and this would be a much nicer solution.

Spec: https://dom.spec.whatwg.org/#interface-htmlcollection

**Comment by annevk** [comment]
I found https://www.w3.org/Bugs/Public/show_bug.cgi?id=26183#c20 and also https://www.w3.org/Bugs/Public/show_bug.cgi?id=5851. The general gist is that something might be feasible, but we don't want to add named string properties (which `iterable<Node>` would) as they'd clash with the named getters the object already has.

**Comment by domenic** [comment]
I also think we shouldn't extend HTMLCollection further, especially given its live nature, and should instead encourage people to use querySelector() and NodeLists.

**Comment by oliverdunk** [comment]
@domenic If I already have a class name stored in a variable, using `getElementsByClassName` seems like the most expressive choice. I agree that `querySelector` would work but it seems unfortunate to encourage building a selector string which will be parsed back into a class name moments later.

**Comment by domenic** [comment]
Nah, given how poorly optimized getElementsByClassName and HTMLCollection is, you're much better off using querySelector(All).

**Comment by oliverdunk** [comment]
Wasn't aware of that, thanks. Is it not optimised because the spec makes that hard, or just because it hasn't been done yet? In the former case I'd agree that we should just let `getElementsByClassName` die, but in the latter, it feels like we should make the function more useful to motivate improving it.

It goes without saying - I'm very new to this so you're probably right, but I want to understand the decision as best as I can :)

**Comment by domenic** [comment]
Because the spec makes it hard, indeed. In particular the liveness of HTMLCollection is much worse than the static NodeLists returned by querySelectorAll.

(And no worries, happy to help!)

**Comment by annevk** [comment]
FWIW, we have live `NodeList` objects that can be iterated, but I do recall us being okay with `HTMLCollection` not getting it due to all the APIs using it in general being discouraged.

**Comment by oliverdunk** [comment]
Happy with the verdict here, so closing the issue.
