### ISSUE TITLE
Implementation status for DOMError?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/dom#766]
https://dom.spec.whatwg.org/#domerror

The spec says *Implementations conforming to this specification will not support them* but still both Firefox and Chrome exposes `DOMError` interface. Are there some compatibility issues about the removal or is it just forgotten?

**Comment by annevk** [comment]
Forgotten might be it as I cannot find any bugs asking for removal. Might also lack historical tests?

**Comment by inexorabletash** [comment]
Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=460725

It's been a few years since I looked into removal. Probably time for another look, but I won't get to it any time soon.

**Comment by saschanaz** [comment]
>Might also lack historical tests?

https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/dom/historical.html has a nuke test for DOMError.

**Comment by annevk** [comment]
Closing this as at least Firefox removed this now.
