### ISSUE TITLE
Add note that "A ShadowRoot node has no parent."

### ISSUE THREAD

**Issue by mbrodesser** [whatwg/dom#770]
The spec:

https://dom.spec.whatwg.org/commit-snapshots/b5eac4d624b229232e8c2e347d6b532172f73439/#interface-node

already notes:
> An Attr node has no parent\. 

It'd be helpful if the note additionally contained "A ShadowRoot node has no parent.".

**Comment by annevk** [comment]
I'm going to remove these Attr node notes, but I'll fix https://dom.spec.whatwg.org/#node-trees instead. That seems like a better place to put all the information about parent/child relationships nodes can have. It already seems adequate for DocumentFragment/ShadowRoot, but #1004 will make it better still.
