### ISSUE TITLE
"Remove a node from a parent" reaction callback stuff needs to be conditional on the node being connected before the operation

### ISSUE THREAD

**Issue by emilio** [whatwg/dom#773]
https://dom.spec.whatwg.org/#concept-node-remove step 14 says:

> If node is custom, then enqueue a custom element callback reaction with node, callback name "disconnectedCallback", and an empty argument list. 

This is wrong, it should be conditional on the parent node being connected before the removal (or something of that sort spec-wise), otherwise you get too many callbacks when removing a node from a disconnected parent.

See https://github.com/servo/servo/issues/23716.

**Comment by emilio** [comment]
cc @annevk @jdm

**Comment by emilio** [comment]
All browsers (but Servo, I expect), log `disconnected` only once in this test-case:

```html
<!doctype html>
<div id="custom-element-parent">
  <custom-element></custom-element>
</div>
<script>
customElements.define('custom-element', class extends HTMLElement {
  disconnectedCallback() {
    console.log("disconnected");
  }
});
onload = function() {
  const p = document.getElementById("custom-element-parent");
  p.remove();
  setTimeout(() => p.firstElementChild.remove(), 100);
}
</script>
```

**Comment by annevk** [comment]
Blame for this points to when this got added. It seems the fix here would be to create a boolean before this step that stores whether _parent_ is https://dom.spec.whatwg.org/#connected. And then modify this step and the subsequent step for queueing this specific callback to be conditional upon that boolean. I suspect we don't need new tests.

cc @domenic
