### ISSUE TITLE
MutationObserver callbacks should be called before executing defer scritps

### ISSUE THREAD

**Issue by zbraniecki** [whatwg/dom#78]
(Cloned from https://bugzilla.mozilla.org/show_bug.cgi?id=1180927)

This doesn't seem to be spec'ed currently (I filled a W3C bug [0]) but if would be nice to follow the implementation of Chrome and Safari here and execute Mutation Observer callbacks before we execute deferred scripts.

That would allow us to prototype API's with shims that rely on Mutation Observer.

[0] https://www.w3.org/Bugs/Public/show_bug.cgi?id=28920

**Comment by annevk** [comment]
DOM doesn't define when mutation observer callbacks run.
