### ISSUE TITLE
MutationObserver characterData:true and input value property changes

### ISSUE THREAD

**Issue by bobOnGitHub** [whatwg/dom#781]
Would it be possible to have characterData change MutationRecords/events raised for `input `element `value `property changes where the change was made directly in javascript via the native `value `property API/setter ?

Currently you cannot observe changes to an `input `element's `value `property with MutationObservers (because it's a property... though you would think there is characterData buried in there somewhere).

You can use "input" or "change" events on the element for user/keyboard changes to the `value `but there is no all-situations way of catching a change to the `value `made directly in javascript ;  you can override the `value `property setter but there are reasons you may not be able to do this (in a way that would otherwise solve the immediate problem).

So, would it be possible to have characterData change MutationRecords/events raised for `input `element `value `property changes where the change was made directly via the native `value `property API/setter ie. in js (as opposed to via the UI which would have issues in that you would still need timeouts etc to know when the data was all in)  ?

**Comment by annevk** [comment]
I don't really understand the threat model. Why can you manipulate the `value` property setter but not the `input` element itself or the `MutationObserver` object (or its constructor)?

**Comment by bobOnGitHub** [comment]
Hi again annevk,

(edited the original text above slightly)

I'm observing 3rd party pages from a browser extension / client-script.

Changes to the setter/constructors etc made in my code don't exist in the page's context where the changes to the input.value are being made.

The only way to get the changes into the page code's context would be to have a script loaded into the 3rd party page's context at doc load time which might not be suitable ( eg. from the user's perspective it affects all pages not just those selected as being of interest)

Something like the "change" event on the element would do if it fired when the input.value was set in JS - as it is, "change" only fires when the user makes the change through the UI ( you don't however want something that fires while the user is actively entering data ).

**Comment by annevk** [comment]
In that case I recommend raising this with the extension API developers. Extensions are not in scope for standards.

**Comment by bobOnGitHub** [comment]
Apologies, false alarm .
I was wrong about "The only way to get the changes into the page code's context..." -  it is possible to modify the code in the page context from the content-script at arbitrary points in time/the page life-cycle (https://stackoverflow.com/a/9517879/4779501).
