### ISSUE TITLE
Read-only OS time formatting preferences

### ISSUE THREAD

**Issue by zbraniecki** [whatwg/dom#79]
All operating systems allow user to select time format. Usually between 12h, 24h or follow automatic.

Firefox OS is currently providing `navigator.mozHour12` that can take true/false/undefined values and that nicely fits into Intl API:

```
(new Date()).toLocaleString(navigator.languages, {
  hour12: navigator.mozHour12,
  hour: 'numeric',
  minute: 'numeric'
});
```

When "use default" is used, `mozHour` is undefined and Intl uses the default `hour12` value for the given locale. If `mozHour` is specified to either `true` or `false`, Intl API follows that.

There's also an event associated with it: `timeformatchange` that is dipatched on `window`.

**Comment by zbraniecki** [comment]
There a several similar preferences that the API should either expose now, or be able to add in the future - timezone selection manual/automatic, showing/hiding dayperiod (am/pm) for 12h clock, showing/hiding seconds etc.

**Comment by annevk** [comment]
This is out-of-scope for DOM. I recommend filing this against whatwg/html.

**Comment by zbraniecki** [comment]
ugh, sorry! Filed in HTML: https://github.com/whatwg/html/issues/171
