### ISSUE TITLE
Export next and previous sibling?

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/dom#791]
The [ContentEditable spec](https://w3c.github.io/contentEditable/) currently talks about the {{Node/nextSibling}} IDL attribute, but I think it really wants to "next sibling" and "previous sibling" concepts, which are not exported from DOM. 

Should we export those concepts? Happy to send a PR, but wanted to check first.

**Comment by annevk** [comment]
Sounds good to me!

**Comment by marcoscaceres** [comment]
Apologies, it turns out they were already exported (for tree). For some reason I didn't see them yesterday when I was searching for them.
