### ISSUE TITLE
Avoid enqueuing tree mutation record when there is no mutation

### ISSUE THREAD

**Issue by pmdartus** [whatwg/dom#796]
Currently, the [replace all](https://dom.spec.whatwg.org/#concept-node-replace-all) steps queues a tree mutation record even when `addedNodes` and `removedNodes` are empty. When following the spec strictly, the [childList Node.textContent: textContent no mutation](https://github.com/web-platform-tests/wpt/blob/master/dom/nodes/MutationObserver-childList.html#L103-L107) fails.

IMHO, the replace all step should only enqueue a tree mutation record when either `addedNodes` or `removedNodes` is not empty. In fact, servo implementation already add [this extra branch check](https://github.com/servo/servo/blob/5ab2d4ea835374c2ca88f5d9b50100669f142273/components/script/dom/node.rs#L2008-L2016).

**Comment by annevk** [comment]
That's somewhat weird as we did decide that `e.setAttribute("x", e.getAttribute("x"));` would create a mutation record.

cc @rniwa @smaug----

**Comment by smaug----** [comment]
Hmm, indeed, that wpt test doesn't follow the spec, and browsers have the behavior the wpt expects.
https://wpt.fyi/results/dom/nodes/MutationObserver-childList.html?label=experimental&label=master&aligned

I agree the current spec makes more sense, but not sure it is worth to change implementations.
Though one can think the attribute setting case differently - there one is after all setting a value, it just doesn't matter whether value is the same as before.
In this case one is replacing nothing with nothing.

Anyhow, I'd be ok to change Gecko's behavior if webkit and blink are also ok with that.
But I don't feel too strongly about this.

**Comment by annevk** [comment]
Given those results, let's change the specification. @pmdartus interested in writing a PR?
