### ISSUE TITLE
Editorial: revert [hr-time] workaround

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#802]
It seems @Exe-Boss is tackling this per https://github.com/tobie/specref/issues/571, but until that lands I'm going to reference [hr-time-2] for a bit to unblock some work.

**Comment by ExE-Boss** [comment]
<https://github.com/tobie/specref/issues/571> has&nbsp;now been&nbsp;merged.

**Comment by annevk** [comment]
That's great, though it doesn't seem to have propagated through all the tooling just yet.

**Comment by ExE-Boss** [comment]
This&nbsp;has now&nbsp;propagated through all&nbsp;the&nbsp;tooling and&nbsp;the&nbsp;build for&nbsp;<https://github.com/whatwg/dom/pull/807>&nbsp;has&nbsp;passed.
