### ISSUE TITLE
Add '// historical' to initCustomEvent IDL?

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/dom#811]
Given that `CustomEvent` has a constructor, should we add a `// historical` comment to `initCustomEvent` IDL?

**Comment by annevk** [comment]
Yeah, I'm supportive of that. The whole `CustomEvent` setup is kinda dated.

**Comment by vinyldarkscratch** [comment]
Thanks for the quick response!  In that case, we'll keep the feature marked as "deprecated" in the MDN browser compat data (basically the reason this issue was opened).
