### ISSUE TITLE
Proposal: MutationObserver.unobserve method to selectively stop observing a specific Node

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#812]
We currently have the `MutationObserver#observe(node, options)` method for selectively observing a certain `Node`, but we do not have a reciprocal `MutationObserver#unobserve(node, options)` method to selectively stop observing a specific `Node`.

At the moment, the `MutationObserver#disconnect()` method stops observing all `Node`s that a `MutationObserver` instance is observing, which can be useful in some cases, but isn't always what we want.

**The main downside of having no `MutationObserver#unobserve` method** is that we must then create one `MutationObserver` per `Node` for every `Node` that we may want to selectively stop observing, as opposed to having only a single `MutationObserver` for all said `Node`s.

**The upside of having `MutationObserver#unobserve`** would be that we could re-use a single `MutationObserver` on many nodes while having ability to clean up observation of specific `Node`s, which would reduce memory and CPU usage.

**Comment by annevk** [comment]
Isn't this a duplicate of #126? Also, https://whatwg.org/faq#adding-new-features is well worth reading.

**Comment by trusktr** [comment]
I'm not sure what I was thinking when I decided to make a duplicate.
