### ISSUE TITLE
Proposal: querySelector() take many selectors 

### ISSUE THREAD

**Issue by regseb** [whatwg/dom#817]
Hi,

I have a proposal for the `querySelector` method: it could take a list of selectors and return the element from the first matching selectors.

Here is a polyfill of this new implementation ([JS Bin](https://jsbin.com/yobularahi/edit?html,js,console)):

```javascript
const querySelector = (that, ...selectors) => {
    return selectors.map((s) => that.querySelector(s))
                    .find((e) => undefined !== e) ?? null;
};
```

The point is to be able to prioritize the selectors. For example to return the secure URL of the video or by default the standard version (in Open Graph metadata):

```javascript
document.querySelector(`meta[property="og:video:secure_url"]`,
                       `meta[property="og:video:url"]`);
```

**Comment by annevk** [comment]
Is there a lot of precedent for this in libraries?

**Comment by regseb** [comment]
I don't know of any library that provides this feature.

**Comment by annevk** [comment]
In that case I recommend exploring that first. We should only expand the standard library with things that will see wide adoption. https://whatwg.org/faq#adding-new-features might also help.

Thanks!
