### ISSUE TITLE
Clarify intro text on non-normative sections

### ISSUE THREAD

**Issue by RByers** [whatwg/dom#83]
From [here](https://github.com/RByers/EventListenerOptions/issues/20#issuecomment-143238689):

@rbyers:

> Ok, thanks. I'm a little confused by [this sentence](https://dom.spec.whatwg.org/#conformance):
> 
> > All diagrams, examples, and notes in this specification are non-normative, as are all sections explicitly marked non-normative. Everything else in this specification is normative.
> 
> Should it be changed (since there aren't actually any sections explicitly marked non-normative as far as I can see?).

@annevk:

> We should maybe change that paragraph, yes. Or consistently markup non-normative sections I guess. Meh. Follow up issue?

**Comment by annevk** [comment]
I'm closing this since that section is no longer there (instead we rely on Infra to clarify all this).
