### ISSUE TITLE
"slotable" should probably be spelled "slottable"

### ISSUE THREAD

**Issue by dbaron** [whatwg/dom#844]
I was looking at the DOM spec during the TAG meeting last week and I noticed the widespread use of the term [slotable](https://dom.spec.whatwg.org/#concept-slotable) in a number of places.  I don't think it is exposed in any APIs yet, though, but I could be missing something.

I immediately had a strong reaction that this was misspelled, and should instead be spelled as "slottable".  (My intuition is that "slotable" would likely be pronounced with a different vowel sound from "slot", i.e., with the vowel sounding like "float", and that the doubling of the "t" is needed to retain the original pronunciation of "slot".)

I checked the introductory sections of Webster's Third New International Dictionary (3 volumes, 1981) and it appears to agree with my intuition on the spelling.  In particular, the most relevant bit is this section 1.4.2 from page 21a:

![IMG_20200310_123156](https://user-images.githubusercontent.com/248721/76352172-d6cf1480-62cb-11ea-8a50-d77da57ef54b.jpg)

although I would note that this section 2.1 on -able/-ible suffixes (from page 23a) may also be of interest more generally:

![IMG_20200310_123210](https://user-images.githubusercontent.com/248721/76352272-fb2af100-62cb-11ea-9960-453bdb086543.jpg)

While it seems painful to change the spelling of a term... it might be worth doing before that term becomes part of an expose API (if it hasn't already).

(I'd also note that the title and initial comment of #677 uses the 2-t spelling.)

**Comment by annevk** [comment]
This was a great read, thanks! I created #845 to address this. If that's okay I'll also PR the HTML Standard.
