### ISSUE TITLE
Regular expressions do not allow spaces where they should.

### ISSUE THREAD

**Issue by jaroslavtavgen** [whatwg/dom#854]
I would like to propose solving the following issue:

"aaab".match(/a{1, 2}/g) currently gives the result "null".  Because there is a space after comma. While "aaab".match(/a{1,2}/g) will work just fine (["aa", "a"]).

My proposal: spaces after commas should be ignored in regular expressions and "aaab".match(/a{1, 2}/g) or "aaab".match(/a{1,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2}/g) should provide the result ["aa", "a"].

Setting spaces after commas is often recommended and encouraged both in code and in common texts. IMO, it would be logical to invoke that in regular expressions as well.

**Comment by annevk** [comment]
The DOM Standard does not define regular expressions. You probably want https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md.
