### ISSUE TITLE
lookupNamespaceURI('xml')

### ISSUE THREAD

**Issue by tkent-google** [whatwg/dom#857]
Specification: https://dom.spec.whatwg.org/#locate-a-namespace https://dom.spec.whatwg.org/#dom-xpathnsresolver-lookupnamespaceuri https://www.w3.org/TR/DOM-Level-3-XPath/xpath.html#XPathEvaluator-createNSResolver

Chrome, EdgeHTML, and Safari follow the current definition of `Node.lookupNamespaceURI()` and `XPathEvaluator.createNSResolver()`.  That is to say, `Node.lookupNamespacURI()` has no special handling for 'xml' prefix, and an object returned by `createNSResolver()` has it.

On the other hand, Firefox's `Node.lookupNamespaceURI('xml')` returns the XML namespace if the node is an `Element`, and Firefox's `XPathEvaluator.createNSResolver()` just returns the specified node.

I prefer the Firefox behavior because of its simplicity.

Demo code:
```html
<!DOCTYPE html>
<html>
<pre></pre>
<script>
function t(header, node) {
  document.querySelector('pre').textContent += header + ':\traw=' +
      node.lookupNamespaceURI('xml') + '\twrapped=' +
      document.createNSResolver(node).lookupNamespaceURI('xml') + '\n';
}
document.querySelector('pre').textContent += 'Wrapped type: ' +
    document.createNSResolver(document).constructor.name + '\n';

t('Document', new Document());
t('DocumentType', document.doctype);
t('DocumentFragment', document.createDocumentFragment());
t('Attr', document.createAttribute('attr'));
t('Text', document.createTextNode('t'));
t('Element', document.createElement('div'));
</script>
</html>
```

**Comment by tkent-google** [comment]
@cdumez or @rniwa What do you think about following the Firefox behavior?

**Comment by shvaikalesh** [comment]
@tkent-google I believe Chrome and Safari implement "correctly resolving the implicit xml prefix" wording of [the spec](https://www.w3.org/TR/DOM-Level-3-XPath/xpath.html) this way.

Firefox behavior seems more straightforward and, more importantly, is web-compatible. If Chrome will drop special handling of `"xml"` as well, I will submit WebKit patch when [the tests](https://github.com/web-platform-tests/wpt/pull/24371) are merged.

**Comment by annevk** [comment]
Note that Firefox does this for both `xml` and `xmlns`. If we special case `xml` here we should do the same for `xmlns`.

**Comment by tkent-google** [comment]
>  Firefox does this for both xml and xmlns.

Thanks!

So the change will be:
* Add `xml` and `xmlns` special handling to the Element section of https://dom.spec.whatwg.org/#locate-a-namespace
* Change the return value of `createNSResolver()` to `Node`

WebKit people, do you have an objection?

**Comment by annevk** [comment]
@tkent-google @shvaikalesh works on WebKit. (As do I nowadays, but I'll defer to him. 😊)

**Comment by cdumez** [comment]
No objection.
