### ISSUE TITLE
When iterator collection is set?

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#86]
"Each NodeIterator object has an associated iterator collection , which is a collection rooted at root, whose filter matches any node."
https://dom.spec.whatwg.org/#iterator-collection

But when this collection should be setting, after creating NodeIterator, or in some steps in createNodeIterator() method (before return this object, but after setting root and filter)?
https://dom.spec.whatwg.org/#dom-document-createnodeiterator

**Comment by annevk** [comment]
A collection is a continuous thing, lifetime isn't really defined anywhere as far as I know.

**Comment by annevk** [comment]
I'm going to close this since we don't really define this for any live collections. I'm somewhat hesitant to define live collections in terms of insert/remove/etc. since that'd be a lot of error prone work.
