### ISSUE TITLE
Node.setChildren()

### ISSUE THREAD

**Issue by pakastin** [whatwg/dom#862]
`element.insertBefore(child, reference)` and `element.appendChild(child)` are not the most convenient way to update for example a list of items. `element.setChildren(children)` would make it so much easier to work with updating children.

What comes to frameworks / view libraries, they all have different ways to update children. Would make so much more sense to have single optimized way to do that, so that all frameworks / view libraries would benefit.

Here's an example solution for updating the children elements of a parent Node:

```js
function setChildren (parent, children) {
  let traverse = parent.firstChild;

  // go through children and place if not in place
  for (let i = 0; i < children.length; i++) {
    const child = children[i];

    if (traverse === child) {
      // already in place
      traverse = traverse.nextSibling;
    } else if (traverse) {
      parent.insertBefore(child, traverse);
    } else {
      parent.appendChild(child);
    }
  }

  // remove all the rest
  while (traverse) {
    const next = traverse.nextSibling;
    parent.removeChild(traverse);
    traverse = next;
  }
}
```

Backwards-compatibility could be provided easily with a polyfill.

**Comment by annevk** [comment]
We recently added `replaceChildren()` (not yet in browsers I suspect). Is that not sufficient?

**Comment by pakastin** [comment]
Oh, can't find that from MDN?

**Comment by pakastin** [comment]
Ah yeah, found it from tests – seems good fit, so closing!
