### ISSUE TITLE
HTMLFieldsetElements::elements should probably be HTMLFormControlsCollection, too

### ISSUE THREAD

**Issue by amn** [whatwg/dom#871]
[`HTMLFormElement::elements`](https://html.spec.whatwg.org/#the-form-element:htmlformcontrolscollection) is a `HTMLFormControlsCollection`, while [`HTMLFieldsetElement::elements`](https://html.spec.whatwg.org/#the-fieldset-element:htmlcollection) is a `HTMLCollection`.

Are there plans to use the former type for both properties? After all, the set of controls that are descendants of a `fieldset` element, are by extension form controls, too, no?

The particular effect of this that made me create this issue is that with a `HTMLFormControlsCollection` you can elegantly access multiple controls that share the same name, through a `RadioNodeList` (peculiar choice for a collection of controls that may or may not be "radio nodes", but probably historic reasons?) object. You can't do that with `HTMLCollection` -- accessing an element of a fieldset by name always returns *the first element with that name*, instead. This disparity is very odd and far from ideal, I think.

Am I onto something here?

**Comment by annevk** [comment]
Generally all of these interfaces are "legacy" in some way and I doubt there's much interest changing things around as it's likely to break things.

**Comment by amn** [comment]
I think if these "legacy" interfaces aren't maintained, including fixed where applicable, their use will decline due to limited utility as applications grow in capability, until they're practically dead weight or appendage, and the withering will spread to the entire "HTML forms" specification -- forms will be useless for anything but "legacy" fallback application.

But forms _are_ useful -- without being associated with one controls don't validate properly, with a form you get more or less "automatic" fallback to HTTP processing of form data, etc.

So I am not sure what you are trying to communicate here -- is this the beginning of the end of HTML forms? Are we going to switch over to HTML Web components that re-implement what forms have given us, as many authors have done already? If we can't fix things without breaking old things, are we going to live with slightly broken HTML forms?

Just to mention, a related issue is that elements that are descendants of a `fieldset`  element, are not associated with the form the `fieldset` element is associated with. This is again strange, if not for historic reasons, since a fieldset isn't submittable itself, and effectively then "hides" all controls it contains, from submission or even access through the form itself.

Maybe a DOM version compliance specification by a DOM application (HTML, being one) could help maintain legacy code while allowing new applications to make use of updated interfaces and functionality? Just throwing things out there now, admittedly.

**Comment by annevk** [comment]
Yes, forms are useful and are not going anywhere. But that does not mean that every part of their API has stood the test of time or warrants maintaining beyond ensuring it's properly defined. There are many different ways to navigate a node tree, not all of them are worth iterating further.

The related issue seems worth raising a separate issue for I think.

**Comment by yosunkayag** [comment]
Huawei telefonumdan gönderildi-------- Orijinal mesaj --------Gönderici: Anne van Kesteren <notifications@github.com>Tarih: 12 Haz 2020 Cum 15:45Al: whatwg/dom <dom@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Konu: Re: [whatwg/dom] HTMLFieldsetElements::elements should probably be HTMLFormControlsCollection, too (#871)
Generally all of these interfaces are "legacy" in some way and I doubt there's much interest changing things around as it's likely to break things.

**Comment by tkent-google** [comment]
It was HTMLFormControlsCollection, but we changed it to HTMLCollection.
Please refer to https://github.com/whatwg/html/issues/200

**Comment by annevk** [comment]
Thanks for looking that, closing this then.
