### ISSUE TITLE
_Which_ unit of related similar-origin browsing contexts?

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#88]
Mutation observer algorithm steps say:

> Let notify list be a copy of unit of related similar-origin browsing contexts' list of MutationObserver objects. 

and

> append it to the unit of related similar-origin browsing contexts' list of MutationObserver objects, and then return it.

This seems pretty ambiguous to me. Shouldn't be trying to go from e.g. entry settings object to browsing context to unit of related similar-origin browsing contexts, or something?

Maybe HTML needs to define "current unit of related similar-origin browsing contexts"?

**Comment by annevk** [comment]
Yeah, that could work. Or IDL defines it as a thing you can grab at anytime.
