### ISSUE TITLE
Adding a return value to `controller.abort()` which represents abort completion

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#881]
Consider the following code we're adding as an example to the Streams Standard in https://github.com/whatwg/streams/pull/1059:

```js
const controller = new AbortController();
const pipePromise = readable1.pipeTo(writable, { preventAbort: true, signal: controller.signal });

// ... some time later ...
controller.abort();

// Wait for the pipe to complete before starting a new one:
try {
 await pipePromise;
} catch (e) {
 // Swallow "AbortError" DOMExceptions as expected, but rethrow any unexpected failures.
 if (e.name !== "AbortError") {
  throw e;
 }
}

// Start the new pipe!
readable2.pipeTo(writable);
```

Wouldn't it be nice if we could do this instead?

```js
const controller = new AbortController();
const pipePromise = readable1.pipeTo(writable, { preventAbort: true, signal: controller.signal });

// ... some time later ...
await controller.abort();

// Start the new pipe!
readable2.pipeTo(writable);
```

The idea here is that the piping operation communicates back to the AbortSignal when the abort completes, and whether it did so successfully. And this can be surfaced as the return value of `abort()`.

API idea for JavaScript `AbortSignal` consumers:

```js
signal.addEventListener("abort", e => {
  e.respondWith(promise); // must be called synchronously during dispatch of "abort"

  e.respondWith(promise2); // causes a Promise.all() on promise and promise2 to be communicated back.

  // Promise fulfillment values are ignored; controller.abort() always returns Promise<void>.
});
```

(a similar thing would exist for spec consumers of AbortSignal.)

Question: what is the default behavior if there are no calls to `respondWith()`? I think probably we return an immediately-fulfilled promise, indicating that the abort request succeeded and nobody signaled that it would take a long time or that it would fail. Alternately, we could have it be forever-pending, under the logic that you need to call `respondWith()` to properly signal that the abort succeeded... but that doesn't seem very user-friendly.

**Comment by annevk** [comment]
How would this change https://fetch.spec.whatwg.org/#abort-fetch? It currently doesn't try to figure out success. (I'm also not sure we should use `repondWith()` if this can be a sequence. At least the precedent for that name is that you can call it once, right?)

**Comment by annevk** [comment]
So I pass a signal to two fetches, one fetch results in a network error, and then I invoke `abort()`. What happens?

**Comment by domenic** [comment]
It uses Promise.all() semantics (the OP captures this as `// causes a Promise.all() on promise and promise2 to be communicated back.`). So in that case `abort()` will be rejected with a network error as soon as that network error happens.

**Comment by annevk** [comment]
Isn't that a bit confusing as it'll still end up aborting the other fetch? It seems allSettled might be more useful?

**Comment by domenic** [comment]
Well, I want failures to be bubbled using a simple `await controller.abort()`, like in the OP. If we had `allSettled` semantics I'd have to do something like

```js
const results = await controller.abort();
if (results.some(r => r.state === "rejected")) {
  throw new Error("Failure during aborting: " + r.reason.message);
}
```

to get that back. So that would really hurt the single-fetch use case.

I do agree that `allSettled` is probably more theoretically "correct", in that it communicates all the potentially-relevant information. But in terms of the use I envision, where this is a way to conveniently rethrow any errors that prevented normal aborting, `all` semantics are more helpful.

Relatedly, we probably would want to mark the returned promise as handled, so that consumers which _don't_ want to rethrow such errors don't get bothered by unhandled rejection warnings. That fits with how this is a supplementary failure channel that just makes it easier to extract failure information that you could get via other means, e.g. by saving the promise returned by `fetch()` or `pipeTo()`.

**Comment by domenic** [comment]
OK, at the risk of forking the thread and losing the fairly nice design work we've been doing so far, here's an alternate solution that involves a lot less moving parts:

```js
const controller = new AbortController();
const pipePromise = readable1.pipeTo(writable, { preventAbort: true, signal: controller.signal });

// ... some time later ...
controller.abort();
await DOMException.ignoreAborts(pipePromise);

// Start the new pipe!
readable2.pipeTo(writable);
```

It's a little rough (e.g., slightly more to type; not a huge fan of the name `ignoreAborts` but I want it to be short; it's a bit strange that a function with a generic name like "ignoreAborts" specifically operates on promise arguments...). But it's probably a cleaner separation of concerns, whereas my original suggestion mixes things up a decent bit in the name of convenience.

**Comment by MattiasBuelens** [comment]
I like how in the current design of abort signals, there's only *one-way* communication from the `AbortController` to the `AbortSignal`. An `AbortSignal` can observe and get notified on the state of its parent `AbortController`, but it can in no way alter its parent's state or behavior. This allows developers to freely pass `controller.signal` around to whatever user-defined or platform-defined function (or functions), without worrying about them affecting the controller.

With the original proposal, that would break: an abort signal would now be able to change if, how and when the promise from `controller.abort()` would resolve or reject. Throw in [signals following other signals](https://dom.spec.whatwg.org/#abortsignal-follow), and you get a lot of "action at a distance".

Also, how would this interact with something like `Promise.race()`?

```js
const controller = new AbortController();
const promise = Promise.race([
  fetch("/fast", { signal: controller.signal }),
  fetch("/slow", { signal: controller.signal })
]);
// after "/fast" has been fetched:
const abortPromise = await controller.abort();
// `promise` resolves with result from "/fast"
// `abortPromise` rejects with an AbortError from "/slow"... but should it really? 😕
```

---

> ```js
> await DOMException.ignoreAborts(pipePromise);
> ```

This proposal could work. I'm already using a similar helper in my own code:
```js
function rethrowUnlessAbortError(e) {
  if (e.name !== "AbortError") {
    throw e;
  }
}

await promise.catch(rethrowUnlessAbortError);
```
Not sure about the name `ignoreAborts`, but I don't have anything better either. 🤷‍♂️

**Comment by domenic** [comment]
Closing this, and filing my latest suggestion at https://github.com/heycam/webidl/issues/933
