### ISSUE TITLE
Using [Exposed=Window]

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#89]
According to Web IDL default global is primary global interface (Window), so there is no need to use [Exposed] only for Window:
http://heycam.github.io/webidl/#Exposed
but even if it is going to use them, then I see that for some interface is still missing:
DOMTokenList, DOMSettableTokenList, MutationObserver, EventListener. I'm not sure what should be done for MutationCallback (callback function http://heycam.github.io/webidl/#idl-callback-functions), [Exposed] can/should be use here or not?

I check some other specs and most of them don't use [Exposed] only for Window (even in HTML, but see one exception HTMLHyperlinkElementUtils).

**Comment by foolip** [comment]
The `HTMLHyperlinkElementUtils ` case in HTML is no more: https://github.com/whatwg/html/pull/303

**Comment by annevk** [comment]
I would prefer to just use `[Exposed]` everywhere and get rid of `[PrimaryGlobal]`. I think due to `[PrimaryGlobal]` folks often forget to consider workers.

**Comment by foolip** [comment]
FWIW, I would be OK with always using `[Exposed]`, but there's a lot of specs to update before WebIDL could mandate it...

**Comment by dstorey** [comment]
I believe this can be closed now

**Comment by annevk** [comment]
Indeed, https://github.com/whatwg/dom/commit/da7b3ec5d9a4cbd857f0dc6c5ef164331ae156be and https://github.com/whatwg/dom/commit/c9544325095195c3afdf6284c29b26e84ce572aa fixed this. Thanks!
