### ISSUE TITLE
getElementsByTagName needs to be clearer on when the same object can or can't be returned

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/dom#90]
In particular, it looks to me like at call-time the `getElementsByTagName` call captures the HTML-ness of _root_'s node document at the time it's called.  So if that HTML-ness changes, a new object needs to be returned.

I put a testcase at http://web.mit.edu/bzbarsky/www/testcases/dom-queries/test_getElementsByTagName_1.html which tries to exercise some of the edge-cases here.

**Comment by annevk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=492933 has potential other strategies (and what Gecko implements now).

**Comment by annevk** [comment]
This got fixed by https://github.com/whatwg/dom/commit/4c4456228f0282cc0d981b02e3600037b1801bfc but I referenced the wrong issue. 😟

**Comment by bzbarsky** [comment]
That's actually a stronger restriction than what Gecko implements (or wants to implement).  It's OK to return the same list as long as the HTML-ness of the root's node document doesn't change...
