### ISSUE TITLE
Dead key symbols not included in KeyboardEvent

### ISSUE THREAD

**Issue by CendioOssman** [whatwg/dom#900]
The current standard states that dead keys should set `key` to the value `"Dead"` no matter which dead key is pressed. This unfortunately makes dead keys completely undetectable by applications such as noVNC which need to know the proper symbol to send to the remote end:

https://github.com/novnc/noVNC/issues/350

The standard currently refers to using composition events, but they are not a replacement as they only give you the current composed state, not the symbol that was just included to update the state.

Composition events also only work on input fields, not other keyboard event targets such as a canvas. So even if they did contain the proper information, they would still not be a valid replacement.

**Comment by cvrebert** [comment]
You appear to have filed this issue against the wrong specification. I believe the relevant specification for your complaint is https://w3c.github.io/uievents/

**Comment by CendioOssman** [comment]
Oh, sorry about that. How can I best get the attention of an admin that can move the issue?

**Comment by cvrebert** [comment]
Issues can't be "moved" in GitHub, AFAIK.
You'll want to file a new issue in https://github.com/w3c/uievents/issues/

**Comment by CendioOssman** [comment]
They can, actually. As long as it is between repositories for the same organisation. This is better than reopening a new issue as it makes sure all links continue working (and preserves history and such). We do this quite a bit for the noVNC project.

That said, since uievents is not hosted by @whatwg, but rather by @w3c, it would not work in this case.

I've now opened https://github.com/w3c/uievents/issues/343 over there. Thanks.
