### ISSUE TITLE
Why does `preventDefault()` in `pointer` events break `mouse` events?

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#917]
Here's a working demo:

https://codepen.io/trusktr/pen/gOMjELg

In the following demo, `event.preventDefault()` is called in a `pointerdown` event, and that (seemingly inexplicably from an end user perspective) breaks `mouseup` events:

https://codepen.io/trusktr/pen/GRqBeWr

This has been a source of difficult-to-track bugs in an application I'm working on. It really isn't intuitive that one set of events (`pointer*` events) has such an effect on an unrelated set of events (`mouse*` events).

And even if `pointer` and `mouse` events _are_ grouped together, it is not at all clear why `event.preventDefault()` within `*down` event handlers should stop `*up` event handlers from firing.

Furthermore, `click` events are not damaged while `mouseup` events are, leading to further unintuitive and confusing behavior.

The following is the same demo with `pointerdown` calling `event.preventDefault()`, but the demo works because it uses `click` instead of `mouseup`:

https://codepen.io/trusktr/pen/VwjBRXj

**Comment by annevk** [comment]
You should raise this with those defining these events. The DOM specification does not.
