### ISSUE TITLE
Formatting attributes and methods in prose

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#92]
What was happend for formatting attributes and methods? Some of them don't have surrounding CODE element, and presents different style (but it's very inconsistent)

**Comment by annevk** [comment]
`bikeshed` happened. 😟 Someone would have to go through to clean this up. I haven't made it a priority so far.

**Comment by tabatkins** [comment]
Hm? What's wrong?

**Comment by annevk** [comment]
@tabatkins the issue we discussed with `<code>` being removed from `<dfn>` all over.

**Comment by tabatkins** [comment]
Oh. Just style them! You can target the `dfn.idl-code` selector.

**Comment by annevk** [comment]
That's not very semantic.

**Comment by tabatkins** [comment]
It's super marginal and doesn't matter?

**Comment by annevk** [comment]
I think it does, but I'll fix this slowly over time, unless someone comes up with a pull request.
