### ISSUE TITLE
Element.matches(selectors) seeming typo / missing step

### ISSUE THREAD

**Issue by danburzo** [whatwg/dom#921]
In the [definition of `Element.matches(selectors)`](https://dom.spec.whatwg.org/#dom-element-matches), _element_ from step 3 has not previously defined. Probably should be replaced with `this`?

**Comment by danburzo** [comment]
Oops, thanks @domenic, I need to stop logging issues after a day of staring at specs. Makes sense now why my "search" in GH issues on "matches" didn't yield any of the expected results :-)

**Comment by annevk** [comment]
Thanks @danburzo, PR up for review at #923.
