### ISSUE TITLE
When cloning a custom element, `element.outerHTML !== element.cloneNode().outerHTML` appears

### ISSUE THREAD

**Issue by mantou132** [whatwg/dom#922]
example:

```js
class AppElement extends HTMLElement {
  constructor(appTitle) {
    super();
    Object.defineProperty(this, "appTitle", {
      set(v) {
        if (v) {
          this.setAttribute("app-title", v);
        } else {
          console.log(
            "Attribute has been cloned:",
            this.hasAttribute("app-title")
          );
          this.removeAttribute("app-title");
        }
      }
    });
    this.appTitle = appTitle;
  }
}
customElements.define("app-root", AppElement);
const app = new AppElement("title");

// false
console.log(app.outerHTML === app.cloneNode().outerHTML);
```
[CodeSandbox](https://codesandbox.io/s/muddy-tdd-r8zno?file=/src/index.js)

I read [this](https://dom.spec.whatwg.org/#concept-node-clone-ext), it should be `true` if you create the element first and then copy the attribute

**Comment by annevk** [comment]
It seems you missed "with the synchronous custom elements flag unset".

**Comment by mantou132** [comment]
@annevk Thanks for the answer, i am read wrong.

But I am curious why the "synchronous custom elements flag" is not set in cloneNode? In the above example, it seems more reasonable to execute the constructor and then copy the attribute.

**Comment by annevk** [comment]
We don't want to execute JavaScript during those operations as that leads to all kinds of complexity. I'm going to close this as this is working-as-designed.
