### ISSUE TITLE
concept-range-bp-set should compare root nodes before bp relative position

### ISSUE THREAD

**Issue by edg2s** [whatwg/dom#924]
In https://dom.spec.whatwg.org/#concept-range-bp-set:

> If bp is after the range’s end, or if range’s root is not equal to node’s root, set range’s end to bp.

(and similar for "set the end")

This implies that implementations should check if "bp is after the range’s end", however the first step of comparing boundary points is to "Assert: nodeA and nodeB have the same root.".

I would suggest this be re-ordered to:

> If range’s root is not equal to node’s root, or if bp is after the range’s end, set range’s end to bp.

(and similar for "set the end")

**Comment by chansuke** [comment]
Hi, this is my first contribution. I'd like to have a try.

**Comment by annevk** [comment]
@chansuke that's great! Please go for it, you'll have to create a pull request and be able to sign https://participate.whatwg.org/agreement.

**Comment by chansuke** [comment]
@annevk Thank you for the comment! Signed it and sent a PR.
