### ISSUE TITLE
Another interop problem with capturing/bubbling

### ISSUE THREAD

**Issue by domenic** [whatwg/dom#926]
https://wpt.fyi/results/dom/events/Event-dispatch-listener-order.window.html?label=master&label=experimental&aligned&q=event-dispatch-listener-order

https://github.com/web-platform-tests/wpt/blob/master/dom/events/Event-dispatch-listener-order.window.js

Firefox and Chrome do bubbling before capturing, for the target itself; Safari and the test do capturing then bubbling.

Safari makes more sense, so this is probably just browser bugs, but I wanted to double-check.

/cc @reillyeon

**Comment by domenic** [comment]
This also seems to show up in the last row of https://wpt.fyi/results/dom/events/EventTarget-dispatchEvent.html?label=master&label=experimental&aligned

**Comment by annevk** [comment]
Pretty sure this is the same as #916. I suspect that if you look at the history for that test it'll show that as well.

**Comment by domenic** [comment]
Yep, OK, confirmed.
