### ISSUE TITLE
ShadowRoot's delegatesFocus

### ISSUE THREAD

**Issue by annevk** [whatwg/dom#931]
@sideshowbarker discovered that Chrome exposes `delegatesFocus` on `ShadowRoot`. This hasn't really appeared in any specification as far as I can tell (e.g., dglazkov-era's https://www.w3.org/TR/2015/WD-shadow-dom-20151215/#the-shadowroot-interface doesn't have it), but given that we expose other state that can be set when creating a shadow root, such as `mode`, it might well be reasonable to add.

@rniwa @smaug---- @rakina thoughts?

**Comment by rniwa** [comment]
Readonly attribute?

**Comment by sideshowbarker** [comment]
> Readonly attribute?

I assume so (and so it wouldn't require more than fairly minimal changes to the spec, to essentially just expose the value of the internal flag which is already there).

**Comment by annevk** [comment]
https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/dom/shadow_root.idl has `readonly attribute boolean delegatesFocus;` which is what you'd expect here.

**Comment by smaug----** [comment]
I guess the attribute shouldn't be harmful, even if if wasn't used frequently.

**Comment by rakina** [comment]
Yeah looks like this was added in the [initial impl of delegatesFocus](https://codereview.chromium.org/1174893002) but wasn't part of the [explainer](https://github.com/TakayoshiKochi/tabindex-focus-navigation-explainer/blob/master/TabindexFocusNavigationExplainer.md). Sounds reasonable to keep around.

**Comment by rniwa** [comment]
I'll be in the favor for adding this readonly attribute to make the API more interoperable. I don't think trying to remove it in Blink is productive course of action given there isn't really a downside to it.

Tangentially, maybe we should make it writeable. There isn't much downside to making it possible to update this flag after shadow root creation but we should probably track that in a separate issue once this is addressed.

**Comment by foolip** [comment]
I noticed this today as well, so I sent https://github.com/whatwg/dom/pull/974 + https://github.com/web-platform-tests/wpt/pull/28593, and I've filed https://github.com/whatwg/dom/issues/975 about making the attribute mutable.

**Comment by rniwa** [comment]
This has been implemented in WebKit as of https://trac.webkit.org/r276585
