### ISSUE TITLE
how to read dom.ds in vscode?

### ISSUE THREAD

**Issue by anlexN** [whatwg/dom#938]
it is not formatted. very difficult to read.
![image](https://user-images.githubusercontent.com/8686739/103216641-822b8180-4951-11eb-933f-cc4c1720abda.png)

**Comment by annevk** [comment]
Presumably https://stackoverflow.com/questions/29973619/how-to-make-vs-code-to-treat-other-file-extensions-as-certain-language addresses this? It's a dialect of HTML so using HTML should work well for most of it.

**Comment by anlexN** [comment]
thank you, but why whatwg does not use markdown? I've never heard of .bs extension name. oh my god.

**Comment by annevk** [comment]
We use https://github.com/tabatkins/bikeshed because we have more complicated requirements.

**Comment by anlexN** [comment]
i think it is very edge, and not so good.

**Comment by annevk** [comment]
Okay. You're certainly welcome to demonstrate a better approach that still addresses the same use cases. That's somewhat out-of-scope for the DOM Standard though so I'll close this.
