### ISSUE TITLE
"ownerElement"

### ISSUE THREAD

**Issue by gwagner57** [whatwg/dom#941]
https://dom.spec.whatwg.org/commit-snapshots/57ddc0f32f8e567d0f5bb92970dccd2df9d04a47/#ref-for-element④⑥

In the explanation text of https://dom.spec.whatwg.org/#attr, it is stated that "Attributes have a [...], value (a string), and **element** (null or an element)".

But it should rather be "... and **ownerElement** (null or an element)".

**Comment by pshaughn** [comment]
It looks to me that ownerElement is just the name of the getter in the IDL, not a term that's otherwise used anywhere in the specification. Getter names are often slightly different from names used in specification prose.

**Comment by annevk** [comment]
Indeed, objects have associated fields (basically the private state) and IDL describes the public API which typically returns and manipulates the associated fields.

I suspect OP was looking for https://dom.spec.whatwg.org/#dom-attr-ownerelement which indeed returns the element field of this.

Happy to answer any follow-up questions, but I'll consider this closed for now.
