### ISSUE TITLE
Missing Documentation - WebGLContextAttributes

### ISSUE THREAD

**Issue by mrchantey** [whatwg/dom#942]
It seems there is no documentation for the WebGLContextAttributes dictionary.
The missing documentation results in gaps in auto-generated documentation for rendering libraries, i.e [Babylon.js - EngineOptions](https://doc.babylonjs.com/typedoc/interfaces/babylon.engineoptions). 

My limited understanding of what's going on is that Babylon extends Typescript Definitions and Typescript in turn fetches comments from whatwg.

WebGLContextAttributes definitions can be found on the [WebGL Context Attributes Spec](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2).

**Comment by annevk** [comment]
What made you file this against the DOM Standard?

**Comment by mrchantey** [comment]
Ah my apologies it looks like I'm in the wrong place. I was researching how Typescript generates comments for the [lib.dom.ts](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/master/baselines/dom.generated.d.ts) file and assumed they are all fetched from whatwg. I suppose this is khronos business, will keep looking.
