### ISSUE TITLE
Define criteria for StaticRange validation

### ISSUE THREAD

**Issue by sanketj** [whatwg/dom#947]
Because static ranges are not kept up-to-date during DOM mutations, UAs/authors need to validate the static ranges before actually using them. The criteria for checking if a StaticRange is valid seems to be:
- The start and end containers of the static range should be in the same (non-flat) DOM tree.
- The start offset is between 0 and the start container’s node length (inclusive).
- The end offset is between 0 and the end container’s node length (inclusive).
- The position of the start boundary point should be before or equal to the position of the end boundary point.

My questions are:
(1) Should we include these criteria as part of the StaticRange spec so that all UAs and authors can follow the same?
(2) If the answer to (1) is yes, I wonder if it is also worth having a public DOM API that does this, something like: `StaticRange.IsValid`?

Note that I'm only talking about specifying _what_ the validity criteria should be, not _when_ these validity checks should be run. The _when_, in my opinion, should be left up to the individual use case. (Ideally, validity is checked on-demand, only when necessary.)

**Comment by sanketj** [comment]
cc: @annevk @rniwa @domenic

**Comment by annevk** [comment]
When and where do user agents validate static ranges? If we have callers of that operation within the web platform, I agree it would make sense to define that operation in the DOM Standard.

Separately, it might make sense to then expose that operation to userland. I would probably put the method on the prototype so you can use it directly from an instance.

cc @smaug----

**Comment by sanketj** [comment]
For the [highlight API](https://www.w3.org/TR/css-highlight-api-1/), before we can paint a StaticRange-backed highlight, we have to first check if it is valid.

That's my use case, not sure if there are others. But I can imagine most (future) features that want to use StaticRange would need to do this.

**Comment by annevk** [comment]
Alright, it looks like that has multiple implementers on board so https://whatwg.org/working-mode#changes won't be much of an issue. I suggest you start with defining the operation and then we can consider the API question once more people have had a chance to weigh in?

**Comment by smaug----** [comment]
At TPAC 2019 it was discussed that highlight API would internally need to keep basically a live range.
StaticRange would be used just as a way to pass the data about highlight area without keeping (live) Range object alive in JS land
(since live Ranges tend to slow down DOM operations, especially if there are many of them around).
I guess that idea hasn't materialized.

I think keeping the range alive inside highlight API implementation would also solve issue 7 mentioned in the spec.
And issue 7 isn't the only issue StaticRange + validating later approach brings.
It isn't clear to me how StaticRange + validating later can work given all the possible DOM mutations.

**Comment by sanketj** [comment]
Issue 7 (discussed here: https://github.com/w3c/csswg-drafts/issues/4598) is an additional validation criterion specific to highlights. If we resolve to not support that scenario, before painting a highlight, we need to ensure that the backing StaticRange is valid and that this additional criterion is met. Issue 7 should not generally apply to StaticRange, and the validity checks I am proposing are a generic set of checks that should apply to static ranges in all cases.

As another (hypothetical) example, imagine if a UA/author wanted to implement StaticRange.toString. The API would first need to check if the static range is valid. If it isn't, toString should throw an error or perhaps just return an empty string. If it is valid, then it may return a result in a manner similar to Range.toString.
