### ISSUE TITLE
Evolution of DOM API to a higher level of abstraction.

### ISSUE THREAD

**Issue by alejsanc** [whatwg/dom#957]
I think it would be convenient for the DOM API to evolve to a higher level of abstraction as some Javascript libraries allow with high level and chainable methods.

Example:

     paragraph.appendElement("a").setAttribute("href", "/article");

**Comment by WebReflection** [comment]
FWIW, this works already

```js
paragraph.appendChild("a").setAttribute("href", "/article");
```

**Comment by alejsanc** [comment]
Those examples that you put are more complex than my example. That's why people use libraries and not the DOM directly.

**Comment by annevk** [comment]
Hey @alejsanc, thanks for your interest in improving the DOM Standard. I recommend working with the https://wicg.io/ community to turn this into a concrete proposal we can evaluate.

**Comment by alejsanc** [comment]
Thanks for the info annevk.
