### ISSUE TITLE
Missing references for class Elements members description.

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#96]
In IDL box we don't have any references for query and queryAll, so we cant jump to description (the same is for listing at the end od spec). And 'Elements' after 'class' hasn't any id (missing dfn).

I don't know why, but in dom.bs file I see this: `<pre class='idl' data-no-idl>`, so maybe this `data-no-idl` is responsible for that.

**Comment by annevk** [comment]
IDL doesn't support subclassing of Array, is what the problem is here.

**Comment by ArkadiuszMichalski** [comment]
Understand, but PRE still use class="idl" which is a bit misleading. If it will not be soon repaired may use links directly (#dom-elements-query, #dom-elements-queryall)?

**Comment by annevk** [comment]
Seems like too much effort for something that is still basically broken until IDL is fixed.

**Comment by tabatkins** [comment]
fwiw, one of the #whatwg regulars was complaining about this a few days ago, too.

**Comment by annevk** [comment]
Hmm, patches welcome I guess. But none of this really works without some new IDL stuff that hasn't been defined, as explained in that section.

**Comment by tabatkins** [comment]
Whether or not IDL accepts some concepts is irrelevant - this just needs to enable stuff within DOM and elsewhere to autolink the interface name and its methods.  Patch submitted to do so.

**Comment by annevk** [comment]
Thank you @tabatkins!
