### ISSUE TITLE
HTMLCollection.item() and passing string

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [whatwg/dom#99]
Firefox, Chrome, IE, Opera (Presto) support this variant, I can't determine why, it's covered per actual DOM?

```
<!DOCTYPE html>
<html>
<body>
	<div id="id1" name="name1">DIV1</div>
	<div id="name1" name="id1">DIV2</div>
	<p id="info"></p>
	<script>
		var collection = document.getElementsByTagName("div");
		var info = document.getElementById("info");
		info.innerHTML += "Result:<br><br>" + collection.item("name1").textContent + "<br>";
		info.innerHTML += collection.item("id1").textContent + "<br>";
	</script>
</body>
</html>
```
and output:
Firefx, Chrome, Opera (Presto): DIV1 DIV1
IE11: DIV2 DIV1

**Comment by jdm** [comment]
It's the `getter Element? namedItem(DOMString)` in [the spec](https://dom.spec.whatwg.org/#htmlcollection), where `getter` is defined in [WebIDL](http://heycam.github.io/webidl/#idl-special-operations).

**Comment by ArkadiuszMichalski** [comment]
Hmm, now realized it's IDL action, string was converted to 0, so `item()` always get 0 if we pass anything other than numbers, it doesn't meant that `item()` accept string (but in IE11 do this), ok, can close.
